### ISSUE TITLE
Unable to access sessions

### ISSUE THREAD

**Issue by user1658** [drawpile/Drawpile#1018]
I downloaded Drawpile so I could participate in community drawing sessions, but except for the first couple sessions about a year ago, everytime I've tried to join a session it tells me that I have the wrong password.  

-I currently have Drawpile 2.1.20, though I update it with each session if there's one available. The first version I had was 2.2.17. 

-The password is available in community announcements and changes each session. I've tried copying and pasting the passwords, but it never works.  

-I've also tried pressing enter on my keyboard vs clicking the button to join, but neither work.  

-I'm not using the same username with each session. I didn't think it'll be a problem since the password is different anyway, but if it is I don't know what to do since I can't remember what name I used before it stopped working. 

-I have searched the issues and found #660 which seems close to what I'm experiencing, but there's no solution there.

**Comment by user1658** [comment]
Well, I almost managed to join a session today (probably the username), but it gets stuck catching up, then the loading bar actually resets after some time.

**Comment by Wade821** [comment]
GitHub is not intended for providing support. If you have questions about how to use Drawpile or technical issues, Drawpile's Discord server is the best place to get assistance. You can join the Discord by using the invite link found on the lower left corner of the website. Are you able to access the main website https://drawpile.net/ by any chance, or no? This might be relevant to your problem. If you can't, here's the Discord invite link - https://discord.gg/M3yyMpC

Regarding the session, without more details about what exact screen you're getting, it could be that you're picking already registered usernames even though you're using a different username each time. You should be able to paste a screenshot here of the prompt you're getting when you attempt to access the session.

**Comment by user1658** [comment]
Well googling the issue led me here so I figured it wouldn't be a problem. Anyway, I think I'll stick with the username that worked. Figured the loading issue was about the time (it had been nearly 3 hours since the session started).

**Comment by Wade821** [comment]
Github is primarily intended for feature requests and noting bugs, so that way there is a sort of "to do" list for resolving problems with the programs. As such, the idea is to limit the number of open issues so that way it can be kept focused on its primary functionality. 

Also, if you have a username that worked, it implies the other names you were trying were registered to other users. Regarding the long load time, if people aren't doing a session reset (session, moderation, reset...) and the MB number in the lower left is high, this can cause connectivity issues for users. It is recommended not to turn off auto reset (Edit, preferences, Network, Automatically reset when space is low should be checked) or make use of the manual reset when people are trying to connect into the session.
