### ISSUE TITLE
can not start the appimage

### ISSUE THREAD

**Issue by fadi123go** [drawpile/Drawpile#1019]
here is the output in the terminal:

./Drawpile-2.0.10.AppImage 
Opening log file: /home/pc/.local/share/drawpile/drawpile/drawpile-2.0.10-٢٠٢٢-٠٢-٠٢.log
Unable to open logfile
Enabling custom XInput2 tablet event filter
Auto configuration failed
140034084989056:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140034084989056:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140034084989056:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140034084989056:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
QMutex: destroying locked mutex
 
the system used is mageia . hardware used is
video card: Vendor: ‎Intel Corporation
Description: ‎Mobile 4 Series Chipset Integrated Graphics Controller
Media class: ‎VGA compatible controller

processor :Celeron(R) Dual-Core CPU       T3000  @ 1.80GHz

**Comment by notfood** [comment]
That's a really really old appimage and it's unsupported. The recommended way to install it is via flatpak
https://flathub.org/apps/details/net.drawpile.drawpile

**Comment by Wade821** [comment]
Fixed in the beta client, closing this issue since the beta includes compatibility mode.

I also don't believe it will be used for the older version explicitly. Please feel free to comment if you have any remaining concerns on this issue.

Latest version available here:
https://github.com/drawpile/Drawpile/releases

Last release on website (out of date):
https://drawpile.net/download/#Beta
