### ISSUE TITLE
Having a bug issue where the art on my layers are being deleted.

### ISSUE THREAD

**Issue by fryder11** [drawpile/Drawpile#1021]
Hi, i'm having trouble making a piece and as of yesterday and today, the art on my layers are being deleted. Ive applied Fixed onto them to test if theyre being deleted but nope, its just the art. I've always saved after making changes, and never changed the file type to png or anything like that. Infact, it started with only one specific layer being altered (the background) but it's gone on to change a ton of more important layers. Another problem is that this happens every time i close the tab, when i reopen it, more is gone. It even stopped showing the full image unless i resized it down to 60000, ruining the image. I was aware of there being a size limit but this wasnt a problem up until now. I tried to see if i have ever clicked Hide from self, and it worked with one layer but, not any others.

I just want to know if anyone is having a similar problem and how to fix it, because this took me days to do. Thank you.

**Comment by Wade821** [comment]
Are you using 32 bit Drawpile or 64 bit? If your board is big, you really should be using the 64 bit version. The difference between the two versions is that 64 bit is capable of handling larger board canvases because it can use more computer memory. 

Also, 60,000 pixels is ABSOLUTELY massive for Drawpile and unusable for most people in online sessions (as this causes a lot of lag if the board is too big or has too many layers). As such, it might be better to just draw in another program if you're using that large of a canvas. Maybe the Drawpile rust version (whenever that comes out) will be better about handling such large canvases, but for right now that is really outside the range of usability for most people. I'd say 5k by 5k to 10k by 10k is about the biggest most people use.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

No response in a year, closing this.
