### ISSUE TITLE
Unable to draw on touchscreen

### ISSUE THREAD

**Issue by ZandPatchwork19** [drawpile/Drawpile#1042]
My laptop is a touch screen and I use it entirely for all of my art, and I saw my friend was using Drawpile and I wanted to join.

However, I found I couldn't actually do anything but move the canvas since it doesn't appear to be touch screen friendly.

If I am doing something wrong, please let me know, but if this isn't intended then please update it where touchscreen users can use this amazing looking system.

**Comment by Wade821** [comment]
Drawpile has built in touch support, but under the assumption that touch is intended to move the canvas and that you have a drawing pen with which to use. So the behavior you're describing is intentional. If you don't have a pen, then you need simply to go to edit, preferences, and uncheck "Scroll with finger" in order to be able to draw with your finger.

In the future, I suggest joining the Discord for help related questions, for which the invite link can be found on the lower left corner of the website and you'll get faster responses. 

Github is intended primarily for bug reporting, feature requests, and usability issues. Feel free to respond to this issue, but I'm going to close it, so it doesn't clutter up Drawpile with existing issues that need to be handled.
