### ISSUE TITLE
[2.2.0-beta.4] mysteriously reverts to 2.1 compatibility mode or locks operators out

### ISSUE THREAD

**Issue by Charmandrigo** [drawpile/Drawpile#1093]
I am not sure how I triggered this.
I ran a session that has "persist without users" on, by the second day online it is starting to slowly bug out, it first marked my session as being ran on Drawpile 2.1 (despite I hosted it right from the beta 4 and so all my invites should be running the same version to join). So This locked out the MyPaint tools, so this is essentially forcing me to have to re-host the canvas again in hopes it shows it again as version 2.2 beta 4.

By the second day it has locked me out of my own permissions despite I am operator on the session, I can't edit other's layers, can't create new folders now, can't delete either. But duplicate works, except I can't erase the duplicates but using Undo (CMD+Z) deletes them. I re-checked the session permissions and both general and own layer editing is set for everyone, so I have no idea why I am now locked from making edits to other's layers, organize layers or create more layer folders

**Comment by askmeaboutlo0m** [comment]
Yeah, this has been reported by some other people as well. I've never run into it with any sessions during like the past half year, so currently I'm not sure why it would happen. I'll probably have to put in some additional logging for the next beta and see if I can get some more information on what's going on. Something about the permission state is getting messed up, that's what keeps track of the compatibility mode too.

Duplicate probably doesn't *actually* work, if permissions are borked, then it might show up for you locally, but other clients won't see it.

**Comment by Charmandrigo** [comment]
My canvas session resetted while on this bugged state and over 85% of the canvas wiped out in the process, locally I saved a copy at least but this bug appears to also destroy most of the work on the canvas if the Operator was on it while the reset happens, not sure if this all happened because I am on the Mac version or it happens on windows too

**Comment by askmeaboutlo0m** [comment]
Hmm, I poked around in the code a bit and it could actually be a *server* issue too. If you have access to the server such a broken session is hosted on, the `.session` and the beginning of the `.dprec` file associated with it would be helpful with verifying if there's anything wrong on that side. If it's hosted on an official community server, I can probably also shake those files out of whoever owns the server.

If the permission state is busted, I wouldn't expect a reset to work, since that will also run into permission issues, causing various commands during the reset to get thrown on the floor.

**Comment by Charmandrigo** [comment]
Shoot... I ended the session before reading this, I ended up re-hosting the backup copy canvas, this appears to have resolved the issues again and the session is back to be hosted on the current beta.
if it happens again, I will notify.

My session was hosted on sofurrydrawpile.chickenkiller.com server, maybe it can be debugged on that same server

**Comment by askmeaboutlo0m** [comment]
No worries, I figured it was too late at this point. I have the admins of that server within reaching distance, so if it happens again, I'll give them a poke. Actually, maybe that's why I haven't seen the issue before, sofurrydrawpile is running on a Raspberry Pi with an ARM CPUI, while all of the servers in the past have been on boxes with a regular Intel CPU.

**Comment by askmeaboutlo0m** [comment]
I'm just bad at computer, it's a blindingly obvious bug. It just uses the protocol version of the last session hosted on the server, rather than the one of the session you're actually joining. In testing it was never noticed because the sessions always happened to be the last ones hosted, so it seemed like it was working correctly.

This is fixed now and we'll probably do another beta release very soon to get this out.
