### ISSUE TITLE
Hitting session size limit breaks session entirely

### ISSUE THREAD

**Issue by Charmandrigo** [drawpile/Drawpile#1097]
I am operator of a session that was running for 4 days now, the size limit reached, apparently going to 99mb before finishing loading the session, so it didn't finished and can't get to see me logged in or reset, or end the hosted session completely.
<img width="516" alt="image" src="https://github.com/drawpile/Drawpile/assets/30424766/cc2770ae-5fe1-47d1-9324-26fa01929e6b">
<img width="171" alt="image" src="https://github.com/drawpile/Drawpile/assets/30424766/496d059e-a566-4c70-a7ce-73ab783a05ee">

All my controls are locked out, and since i can't seem to finish loading the session it appears like I am not going to be able to reset it or end it unless the server admins reset the server or end the session remotely.
There should be a failsafe for this, or other session operators may get stuck from moderating their own session because the size limit happened before finishing loading the session itself

**Comment by askmeaboutlo0m** [comment]
Controls being locked out may be a manifestation of #1093, we'll look at it.

**Comment by askmeaboutlo0m** [comment]
Okay, it's a different bug that's probably been around for a long time. Running the session into its space limit means the server won't ever tell you that your user exists, leaving you in a weird limbo state you can't get out of.

Various fixes come out of this:

- [ ] Make the client understand this limbo space emergency state and give you a way to get out of it by enabling a few select controls: becoming operator, unpersisting the session and resetting the session.
- [ ] Fix the server refusing to send *any* information when there's a space emergency. It needs to still relay chat messages, user joins/leaves and permissions.
- [ ] Maybe prevent users from setting the session size limit to ridiculous values that go beyond the server-side limits and will cause this state in the first place.

**Comment by askmeaboutlo0m** [comment]
For what it's worth, I managed to partially implement point 1 and get the session unstuck. Currently, you can avoid getting into this state by not setting the session size limit to ginormous values. The hard limit on sofurrydrawpile is 99 MB, so you probably shouldn't set it above 50 MB, to give some leeway.

**Comment by Charmandrigo** [comment]
for what I remember it had the default values on moderation, which was 20mb (+the session current size) so I suppose it got too big it got stuck on a limbo

**Comment by askmeaboutlo0m** [comment]
Hmm, it sounds like it allows oversized resets then, which it probably shouldn't. I would have expected it to refuse to accept the reset when it's above 20MB (or whatever the limit you set is), since I saw some code to that effect, but maybe that doesn't work right or uses the hard limit instead.

**Comment by Charmandrigo** [comment]
By the last time I logged in it said something about 20mb (+57mb) or so

**Comment by Charmandrigo** [comment]
The only solution I can think of is that the server software simply automatically re-hosts the current .ora file before reaching the size limit, this cleans entirely the memory and goes back to the session having a small size, the only thing that could be added is just keep the permissions intact and chat history if it was enabled

**Comment by askmeaboutlo0m** [comment]
The server doesn't have an understanding of what the canvas actually looks like, it just relays commands. That's why you can run a public Drawpile server on a Raspberry Pi without issue, it doesn't need much processing power. But that also means it can't manipulate the canvas in any way, all it can do is ask the client to give it a new starting point with an initial set of commands (a "reset".)

But really, it's just a bug, the problem is that it stops communicating *anything* when you run it out of space, including important information like the "you're an operator" command. It should continue to send those commands, they don't take up any extra room in the session.

**Comment by askmeaboutlo0m** [comment]
This is fixed server-side now. When a session hits the size limit, it will continue to store important commands for another while. Important commands are joins, leaves and becoming operator, since those are needed to get the session out of this situation. So that lets you actually reset the session once it hits the limit.

It also now locks the canvas when the session is out of space and doesn't spam the chat like it used to do, instead it sends an alert at most every 10 seconds.

Thanks for reporting it!
