### ISSUE TITLE
blurry canvas when at an angle

### ISSUE THREAD

**Issue by guiguizada** [drawpile/Drawpile#1102]
whenever the canvas is rotated not by 90° multiples the lines get really fuzzy until the grid shows, is there a way around this?

**Comment by Wade821** [comment]
This is actually related to issue #803. The problem there exists here because of interpolation and how pixels display images. And given there are different interpolation methods depending on the type of media being used (lineart, photos, color art, etc), there is likely to be no good answer to this particular issue.

As such, I fear there's no good answer for this particular problem, so I'll leave it for a dev to answer.

**Comment by askmeaboutlo0m** [comment]
Yeah, it's changed now. It now doesn't blur unless you zoom out from 100% percent, which seems like a more reasonable behavior.

You can try it out in the development version of 2.2: <https://github.com/drawpile/Drawpile/releases/tag/continuous>
