### ISSUE TITLE
Aliased / Pixel brush strokes are not smooth

### ISSUE THREAD

**Issue by t3hm00kz** [drawpile/Drawpile#1105]
Uncertain if this is improper set-up or if this is intrinsic to the current systems, but the aliased / pixel brush doesn't feel like it properly represents my intended strokes, and I can't place my finger on why. based entirely on feel, my speculation is:

- 0 pixel minimum size is treated as 1 pixel
- Interpolation between pressure weights appears to snap from integer to integer (I.E. 1 pixel directly to 2 pixel width, rather than sub-pixel estimations)

I'm attaching a comparison of Drawpile v.s. Clip Studio, both using similar settings, and with Lazy Nezumi Pro for brush smoothing.

If this is user error, let me know.

https://github.com/drawpile/Drawpile/assets/16449436/a3f49cbb-93c1-4b4b-956f-923145da32d5

![image](https://github.com/drawpile/Drawpile/assets/16449436/dc1084aa-9b7c-4d9a-bafa-36bbd5780f8b)

![image](https://github.com/drawpile/Drawpile/assets/16449436/b5e35941-fe25-4444-9190-d9e69abf98ef)

**Comment by t3hm00kz** [comment]
Build: 2.2.0-beta.3-1055-g476b8dc1
OS: Win10
Tablet: Cintiq 13HD
Pen: Wacom Pro Pen Gen1
Line smoothing from Lazy Nezumi Pro

**Comment by askmeaboutlo0m** [comment]
The minimum size thing is a bug that is fixed in [the continuous release](https://github.com/drawpile/Drawpile/releases/tag/continuous) now. Pixel brushes will now go down to zero pixels if you set them that way.

The lack of smoothness is actually pixel snapping, which is an intentional feature of the Drawpile pixel brushes and can't be changed without both breaking people's workflows and compatibility with Drawpile 2.1. But I don't think that's necessary, since MyPaint brushes already solve it, they don't snap to pixels. There's three MyPaint pixel brushes that ship with Drawpile, they are a pretty good starting point for editing further to fit.

Thanks for finding the issue! I think that resolves so I'll close it, but if you disagree or find further issues or anything else, feel free to reopen it.

![image](https://github.com/drawpile/Drawpile/assets/13625824/2041eade-731a-4388-a0ad-0b7dce196c1b)
