### ISSUE TITLE
Shared/global values/settings for Brushes (Suggestion)

### ISSUE THREAD

**Issue by Kvothen** [drawpile/Drawpile#1119]
Next to the Pressure sensitivity button there to be a "Linked" button, so that Brushes share settings.

**Comment by askmeaboutlo0m** [comment]
I don't think this makes sense conceptually, since you may have different brush slots with different types of brushes that don't even share the same properties. For example, pixel brushes don't have a Hardness setting, MyPaint brushes don't have a Color Pickup setting, so the link would be both invisible and inoperable while you have such a brush selected.

It's also unclear how this would interact with loading a brush presets, it can't guess if you want to apply parts of it to multiple slots or if you meant to unlink those settings beforehand, since otherwise it will clobber a bunch of settings all at once when you pick a brush.

Lastly, space is precious in docks, I don't think the feature would be sufficiently useful to give it room. And we also can't hide it away because then people would activate it accidentally and get terribly confused why their brush settings are changing behind their back.

So I think that's too many downsides to make it into the program.

**Comment by Kvothen** [comment]
Hm, alrighty, it's just that in my personal use i often switch between Eraser and Freehand Pressing E every few seconds, so working with "Addition and subtraction" workflow similar to that of sculpting, slowly shifting/iterating the shape. 
(i come from sculping)
![image](https://github.com/drawpile/Drawpile/assets/63468153/8ec1f712-3799-43f2-93a0-45ab177bba73)
 
Tho yeah... there are quite some problems to address for such a thing.

**Comment by Kvothen** [comment]
Ok, I'm doubling down on this. Would be very useful for the eraser to mirror the brush settings.

**Comment by Wade821** [comment]
Doubling down does nothing to address the aforementioned issues. And I agree, too niche of a use case. 

> I don't think this makes sense conceptually, since you may have different brush slots with different types of brushes that don't even share the same properties. For example, pixel brushes don't have a Hardness setting, MyPaint brushes don't have a Color Pickup setting, so the link would be both invisible and inoperable while you have such a brush selected.
> 
> It's also unclear how this would interact with loading a brush presets, it can't guess if you want to apply parts of it to multiple slots or if you meant to unlink those settings beforehand, since otherwise it will clobber a bunch of settings all at once when you pick a brush.
> 
> Lastly, space is precious in docks, I don't think the feature would be sufficiently useful to give it room. And we also can't hide it away because then people would activate it accidentally and get terribly confused why their brush settings are changing behind their back.
> 
> So I think that's too many downsides to make it into the program.

**Comment by askmeaboutlo0m** [comment]
If an eraser version of your brush is what you want, there's an "eraser mode" toggle. By default it's bound to Ctrl+E. It just switches the blend mode of your current brush to Erase and back.

![image](https://github.com/drawpile/Drawpile/assets/13625824/1890dd4f-468d-4392-a6a3-4ad09e824c19)
