### ISSUE TITLE
add HSL in the 'color sliders' dock

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#1127]
It would be more advantageous to have hsL instead of hsV in the colors sliders dock since the V only goes from black to the color and the L goes all the way from the black to the color then to white. We already have it in the options for the color wheel. It would be nice to have this option for the color sliders dock too.

How it is:
![HSV](https://i.postimg.cc/PLmfkMpg/HSL-a.png)
How it would be:
![HSL](https://i.postimg.cc/ZB4bYy6C/HSL-b.png)

**Comment by askmeaboutlo0m** [comment]
Definitely makes sense that the sliders would follow the color model you choose for the wheel, yeah.

**Comment by askmeaboutlo0m** [comment]
Actually, turns out other color models don't make sense when used for the sliders because there's invalid colors in those color spaces. For example, in HSL the saturation only goes to 100% when the lightness is at exactly 50%, otherwise it is capped. A HSL color with, say, lightness 25% and saturation 100% doesn't exist. The HCL model has similar issues, the channels are interdependent.

This leads to awfully confusing behavior when putting it into the sliders, because changing one of them causes the other to move as they have to stay within the valid specturm, which makes them outright unusable when trying to select a color with them. It's also why e.g. Krita doesn't offer anything except RGB and HSV for their sliders, the other modes just don't work properly.

**Comment by leandro2222** [comment]
I dont get why you say that a 25%/100% color wouldn't exist in HSL? You can add these values in any device and it will output a valid color example: hsl(125, 100%, 25%)
examples:
https://www.w3schools.com/colors/colors_hsl.asp
https://hslpicker.com/

**Comment by askmeaboutlo0m** [comment]
Okay, I looked it over. There's two different HSL color models, one (that Drawpile, Krita and Qt use) caps the saturation, the other one (that e.g. browsers use) scale the saturation instead so that 100% is just whatever the maximum saturation at the current lightness allows. It still needs various hacks because of ambiguous colors and the inaccuracies caused by scaling the saturation like that, but it does work that way.

**Comment by askmeaboutlo0m** [comment]
This is implemented and available in the continuous release now: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for suggesting and following up on it!
