### ISSUE TITLE
Bundle ffmpeg on Windows

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#1129]
Im using the v2.2 beta

BUG:
In the timeline player there is a 'export video' button.
In the 'export video' window the options mp4, webM and custom FFmpeg are not working with the error message:
"**ffmpeg executable not found**"

**Comment by askmeaboutlo0m** [comment]
You mean the recording player. Yeah, we currently don't ship ffmpeg with the Windows version of Drawpile and installing it there manually for other programs to be able is, like so many things on Windows, a nightmare. So the solution would be for Drawpile to bring its own copy of ffmpeg along.

**Comment by askmeaboutlo0m** [comment]
Partially fixed by letting you pick the path to an ffmpeg executable now. If you try to run it and it can't find ffmpeg, it now tells you what you can do about it: download it from ffmpeg.org on Windows, install it via Homebrew on macOS and install it through the package manager on Linux.

But it would still be nicer if Drawpile just shipped with ffmpeg so you don't need to jump through this extra hoop.

![image](https://github.com/drawpile/Drawpile/assets/13625824/9e95aaff-ab0e-4366-bda7-78f10105be85)

**Comment by askmeaboutlo0m** [comment]
Superseded by #1320. We'll be integrating libav instead, so having a separate (and very large) ffmpeg executable along won't be necessary anymore to render out videos.
