### ISSUE TITLE
Emotes on chat?

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#1130]
It would be cool if we could use emotes such as these ones: https://www.frankerfacez.com/emoticons/wall on chat!

**Comment by askmeaboutlo0m** [comment]
Pretty hard to make work because it needs a pile of backend infrastructure and also has licensing issues. Since Drawpile is not a chat application, making the chat fancier has very low priority over making the drawing parts better. That's too many negative points to ever make it into the program. Plus, the canvas is right there, you can draw or even copy a face on it if you want to react to something.

**Comment by Wade821** [comment]
This isn't necessary to be added in to Drawpile directly anyway. Most modern operating systems have shortcuts built into the system to put in emotes. 

Windows is Windows key + Period.
Mac is Ctrl + Command + Spacebar.

**Comment by askmeaboutlo0m** [comment]
That's emoji, the emotes mentioned are more like stickers.

**Comment by Wade821** [comment]
I saw that after I posted, but felt it was still useful as a lot of people don't seem to know about those shortcuts so I left the comment.

**Comment by leandro2222** [comment]
so maybe, at least, you could increase the font size of emojis (currently its really hard to see if you use a big resolution)

**Comment by askmeaboutlo0m** [comment]
That's reasonable! I've added it and it's available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>
