### ISSUE TITLE
inner viewer

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#1134]
It would be better if, when clicking on image or youtube links at chat, the content get displayed in a pop-up window inside drawpile (instead of open in an external browser)

For example the user bob sends a youtube link, i click on his link and watch it in a pop-up window while drawing (never leave the drawpile software to watch it)

**Comment by CodyEakins** [comment]
An alternative version of this feature would be a warning prompt that would notify the user that they're opening an external website on click, with DNS/diagnostic information for transparency. That's a more common pattern seen across other apps.

**Comment by askmeaboutlo0m** [comment]
Yeah Drawpile is a drawing program, not a link previewer. It is not equipped to render web stuff, nor does it want to be, since that would rope in a host of security issues.

I also don't think that those "you clicked a link" popups do any good, to a normal user they read as "do you really want to tech tech the techy tech", their eyes glaze over and they just mash the "yeah sure whatever" button immediately. The more useless dialogs like these we show to them, the less likely they are to read any of them. A technical user could figure out how to check a link themselves anyway, so not much use for them either. So I'd leave it to the browsers to figure that stuff out, they got malicious site protections and whatnot.
