### ISSUE TITLE
The way to check the ping could be easier...

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#1136]
Currently, to check the current ping I need to right click on the host address text in the status bar then select statistics (hard to find, specially for new users).
The ping value could be directly in the status bar instead. Or at least, left mouse click instead of right mouse click would make this data more acessible.

**Comment by Wade821** [comment]
I'm not sure that's something that always needs to be visible to the end user, because there's a lot of things that already happen that are delayed on purpose to make incoming drawing strokes more smooth. Combined with a few difficult issues like undo and retcon logic, it might give users the wrong impression about what is going on with the drawing board/server. But we can leave this open for the dev to consider.

In the meantime, the menu was made available in the 2.2 beta version under Tools, Developer Tools, Statistics. You can get the latest version of the 2.2 beta here:
https://github.com/drawpile/Drawpile/releases/tag/continuous

**Comment by askmeaboutlo0m** [comment]
Yeah I don't think looking at techy information like your latency is useful in general. The only relevant thing that latency affects is how long undos and redos take, but you'll notice that without needing a number to tell you about it. So I don't see a reason to make it permanently visible or give easier access to it.

I did make the developer tools shortcuttable now though. So if you want quicker access to the statistics dialog, you can now assign a hotkey to them.
