### ISSUE TITLE
Duplicate color swatches

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#1137]
In the continuous release there's color swatches on the Color Wheel and Palette. I wouldn't think the Palette having it as well would be necessary.

![duplicate color](https://github.com/drawpile/Drawpile/assets/51433534/2126c347-eded-4aba-8ba5-7370064d7e41)

**Comment by askmeaboutlo0m** [comment]
That's intentional, since not having it there breaks workflows. A lot of people have the color wheel, sliders and palette on top of each other, since that's how it was in Drawpile 2.1 and it's how it works in some other programs too. If the swatch is missing from one of the three, they can't work properly anymore, they have to keep toggling between the palette and a random other color docker just to get the swatch.

There was the thought of moving the swatch to a separate dock, but the color wheel and color sliders don't have anything else they could put in that spot, so it would just waste precious space to do it that way. So just having it in all three was deemed the best option to solve this.

So I'll close this, but if you have other ideas on how to solve it, feel free to suggest one.

**Comment by vipperz** [comment]
Oh, makes sense. I wasn't sure if it was a bug or not, but I can live with it if it's more functional. Thanks for clarifying.

**Comment by askmeaboutlo0m** [comment]
No worries, thanks for going through the effort of reporting it anyway!
