### ISSUE TITLE
Crashes when choosing certain brushes [android]

### ISSUE THREAD

**Issue by VeeBeeArt** [drawpile/Drawpile#1140]
I know I'm using an unstable version, but just wanted to let you know about this. 
I also attached the log files

I'm using version 2.2.0-beta.6 and my device is a Samsung Tablet S7    

[CrashLog.txt](https://github.com/drawpile/Drawpile/files/12422958/CrashLog.txt)
[CrashLog (1).txt](https://github.com/drawpile/Drawpile/files/12422955/CrashLog.1.txt)

**Comment by Wade821** [comment]
Are you using any programs in accessibility mode in Android? 

Give me a few to find the issue that might be related.

**Comment by askmeaboutlo0m** [comment]
The crash logs look very much like there's another program interfering with Drawpile. For example, there's errors like

```
Error preparing statement 'select id from preset order by LOWER(name) limit 1 offset ?':
    near ">": syntax error
```

Not only does the statement not contain `>` anywhere, there is *no query at all* in all of Drawpile that contains it. There's a lot of similar errors, including one that says "unable to execute multiple statements at a time", which points to something else messing with the brush database, corrupting it and causing Drawpile to crash.

Do you have any antivirus software or anything else installed that's supposed to "improve" things? As mentioned above, software that hooks into accessibility settings is also a common candidate.

**Comment by VeeBeeArt** [comment]
Uhm I'm honestly not sure how to check that? 

But I'll try turning off any accessibility programs

**Comment by askmeaboutlo0m** [comment]
You can usually find a list of installed applications and a list of accessibility features enabled in the settings, but where exactly depends on the flavor of Android you have, so it's hard to point to the exact steps to take.

After disabling anything suspicious, you might also have to clear Drawpile's storage, since its database may have been corrupted. That's usually doable by long-pressing on its icon, going into the "app info" and find a "clear storage" button in there somewhere.

**Comment by askmeaboutlo0m** [comment]
Odd, but glad it's solved! If the problem reappears, feel free to reopen this issue. There would still be the option of just making Drawpile retry a few times whenever it gets an "impossible" error like this.

**Comment by askmeaboutlo0m** [comment]
While working on the mobile phone mode for Drawpile I've been getting a similar error on my phone. I'm not sure if it's the same, since I'm not getting the funky logs about impossible queries, but there's definitely a bug here.

**Comment by askmeaboutlo0m** [comment]
Okay, I think the bug is the same one. There was a chance for two simultaneous accesses to the brush database, which caused all sorts of mayhem because they were stepping on each other. Not sure why moving it to the SD card helped, maybe it made the application just a teeny bit slower, enough for it to not run two things at once anymore.
 
It should be fixed now anyway, available in the continuous development release: https://github.com/drawpile/Drawpile/releases/tag/continuous

Thanks for reporting it!
