### ISSUE TITLE
Ability to create/delete brush slots

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#1141]
Rather than being restricted to 5 slots and one eraser setting by default, if able. 

I know that brush presets are something that makes it possible to have more brushes in general, but clicking onto them changes the slot settings you were specifically on before and not able to have the presets set to a command shortcut of their own. Having a slot created when clicking onto a preset or having a sort of add [+] button near the slot area/in the brush settings is something I've wondered about.

**Comment by askmeaboutlo0m** [comment]
Yeah, I've thought about the ability to increase (or decrease) the number of brush slots before, since having exactly 6 is weird and I would personally like to have no eraser slot because I only ever activate it accidentally and then get confused momentarily why my brush mode won't change anymore.

I wouldn't tie it to the brush presets though, we don't have room for extra UI elements in either brush dock and it would be too complicated I think. It can just be a setting where you can pick the amount of brush and eraser slots and then you can assign those on your own terms.

It's pretty low priority and high effort though, so I don't expect to be getting to it soon.

**Comment by vipperz** [comment]
Picking the amount to assign is definitely a recommendation for it.

It's something I've seen multiple people also gravitate issue with throughout the years, before mypaint brushes integrated, but I do agree it's not something immediate to implement. Highly anticipated, but no rush.

**Comment by askmeaboutlo0m** [comment]
You can now configure the number of brush slots in the tool settings, between 1 and 9, plus the everpresent eraser slot.

Presets also remember changes to them now, which means you don't actually *need* to use slots anymore, you could just use the presets exclusively. There still needs to be a way to assign shortcuts to presets to really make this comfortable, which is #1367.

Thanks for suggesting!

**Comment by vipperz** [comment]
Absolutely adore this feature. Thank you so much for your overall hard work and implementing this!!!
