### ISSUE TITLE
Reset warning box option/Help button causes cursor to lock

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#1142]
It gets a little tedious when you go into an active 2.1 board with 2.2 beta and you get the session reset warning every 10 minutes or so. It would be nice to have the option to not have it shown after every reset when you understand the risk yet don't plan to save the whole canvas.

Clicking onto the Help [ ? ] button on the pop up seems to also do nothing but cause the cursor to block or lock itself until you click onto a different area.
![Screenshot_2](https://github.com/drawpile/Drawpile/assets/51433534/6bf324af-fda2-4e15-906f-9294155dac42)

**Comment by askmeaboutlo0m** [comment]
I've rejected this so far because I don't think it's a valid complaint. You can't do anything during a reset anyway other than wait for it to complete. Without the box, you wouldn't know when it's complete. The box must be manually dismissed, otherwise you get "the computer flashed something in my face and it disappeared before I could read it" syndrome.

There's also a chance that all your work will be corrupted or even completely annihilated by the reset. So I won't put in the option to remove that seatbelt to save a singular click every 10 minutes.

Since the canvas has been reworked by now and is able to show HUD elements now, it could potentially be reworked into something other than a dialog though. Like, showing a loading bar on the screen and putting the notice about saving the canvas somewhere else where it can dismiss itself it notices that you're continuing to draw.

With regards to the help button, is this a Windows thing that's on all dialogs or is it just this one? Because I don't see what would make it show up on this one in particular, it's a dialog like any other.

**Comment by vipperz** [comment]
Does being corrupted imply that even if you were leave the board and return using 2.1 it would still look affected/disappeared? 

Something to having the box disappear after you move the cursor or clicking onto the canvas as a reaction is a thought maybe. How the box could still show itself while loading the canvas, but only show "Canvas Restored" once it's finished is a nice idea for the sudden flash syndrome. I haven't been in a recent 2.2 board to know if that's the default reset look for it.

For the help button, I've found that it's an issue with all or most dialogs as it does the same with Session -> Event Log / Layer -> Properties... / Brush Editor.

**Comment by askmeaboutlo0m** [comment]
A reset means that an operator takes what they see and make that the new starting point. In Drawpile 2.1, you have completely broken indirect mode on brushes and blending artifacts, so if an operator running 2.1 resets the session, the result can look anything from slightly different to completely ruined, depending on what exactly you were doing. That's "expected" corruption, since Drawpile 2.1 is just doing things wrong. There's also some rare cases where unexpected corruption occurs because of network issues or something.

The box looks the same in 2.2 sessions, just the message is different. It still gives you the option to save, because it might as well.

And alright, that makes sense. It looks like there's a way to disable that button anyway. I'll look into why it even exists, since it's totally alien to me on Linux, and either make it work properly or remove it.

**Comment by vipperz** [comment]
Understanding that the compatibility to each other is as limited as that, I do see how being asked to save can be a win to outdated wrongs. Having the box is a better advantage than having to reposition your view after a reset when using 2.1 at least.

Though, I'd imagine it to be more of a dialog message for operators/mods than for everyone, honestly. The average person wouldn't really save a large canvas as a whole for a small section of their own work (i.e a canvas with multiple backgrounds, layers, folders, etc.).

**Comment by askmeaboutlo0m** [comment]
Yeah, it's something that compatibility mode can't sensibly fix, since it would have to behave incorrectly to mirror the behavior, which goes a bit too far.

Maybe in persistent public sessions people don't save the whole thing, but in other kinds of sessions you definitely would. Like, most people I know usually host a session, fill up a canvas and then stop once everyone's drawn out. The result gets shared around. Since Drawpile can't guess what flavor of session you're in, it's safer to show the message to everyone.

**Comment by vipperz** [comment]
Makes sense. Thanks for explaining it.

Yes, those types of sessions typically don't have 15+ people involved for long periods of time, but there's also already a pop up to save a canvas when someone chooses to leave or they suddenly get disconnected and decide to close the window. Most I know when going into a public board choose to copy and paste their work onto an offline canvas or just save a screenshot of their work before erasing. There just seems to be added ways to save a canvas than to save a specific area of an individuals work, even if using 2.2 in a 2.2 session.

**Comment by askmeaboutlo0m** [comment]
The question mark is gone now. It's apparently part of a feature called "what's this?" that's basically an extended tooltip for a control. Pretty useless, so I think turning it off makes the most sense.

**Comment by askmeaboutlo0m** [comment]
The reset dialog has been transformed into something less disruptive. The progress bar is in the bottom-right corner, the notice about saving at the top of the canvas. If you continue to draw, it will dismiss itself automatically. So the functionality is still the same, but you aren't forced to interact with it anymore to keep drawing.

As usual, this is available in the continuous development release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for reporting it!

![image](https://github.com/drawpile/Drawpile/assets/13625824/68cfedc7-91f5-45a5-ba1a-5297fb980811)
