### ISSUE TITLE
Banned? Cannot join any servers

### ISSUE THREAD

**Issue by yeung-jin** [drawpile/Drawpile#1149]
Hi, I've barely ever used drawpile, just a handful of times to draw with a friend. I opened the program today and it seems that I am IP banned. Can I get any help? I can't see any reason why I would have a ban.

**Comment by askmeaboutlo0m** [comment]
Github might not be the right place for it, since you don't have a way of posting your IP address without making it visible to the public at large. But I gave a poke to the folks who deal with handling this stuff, they'll figure out a way. If you didn't do anything, it's probably just an accident because your IP falls into a range that's been abused before, which should be possible to solve.

**Comment by Wade821** [comment]
Yeah, really this issue should be discussed privately. Can you join the Discord server? The invite link is on the lower left corner of the website for future reference ( https://discord.gg/M3yyMpC ), can talk to Bluestrings there about this, or let me know if you have another way you'd like to communicate about this issue.

**Comment by yeung-jin** [comment]
Sure, thank you for your help.
