### ISSUE TITLE
Session settings still appearing in taskbar window

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#1150]
There's been an issue of a "ghost" preview of the session settings for me if I were to click [ Close ] instead of clicking onto the [ X ]. It's something still constant in the most recent continuous release and every other version. It disappears when I move the cursor away while I'm still in the specific session/click back into the session. Unsure if this happens to any other person on Windows.

Reopening the settings to click on [ X ] has been the workaround.

https://github.com/drawpile/Drawpile/assets/51433534/4be6aa1c-b81f-45a9-9dcd-c2826c7201f6

**Comment by askmeaboutlo0m** [comment]
Apparently this is [a bug in Qt since at least 2015](https://bugreports.qt.io/browse/QTBUG-48855). They closed it with no comment, it just says "out of scope" in the resolution. So I guess they don't care to fix it.

Since closing it with the X button works, there might be a difference between cancelling a dialog and closing a window. I tried switching to the latter, does that fix it? It's available in the continuous development release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

If not, then I don't think there's anything I can reasonably do about it from Drawpile's side unfortunately.

**Comment by vipperz** [comment]
Seems like it didn't really cause a difference in the outcome, unfortunately. Thanks for looking into it either way.

Although, would completely taking the Close button away for that specific setting window be optional? I imagine having the [ X ] button to focus on closing it would keep from having to use the other on impulse, since it possibly won't be fixed at all.

**Comment by askmeaboutlo0m** [comment]
Then unfortunately it's not something I can fix. And no, we can't rely on window decorations existing, the user might have those turned off or their window manager might not have them in the first place, which means they don't have an X anywhere they could click. So a button inside the dialog is required.
