### ISSUE TITLE
Drawpile 2.2 Beta 8 x86

### ISSUE THREAD

**Issue by notanartist888** [drawpile/Drawpile#1155]
Hi, sorry if here is not the place for it...
My daughter use the 2.1 version on a ASUS vivotab note 8 with a pen and she love to make animations on it. She read about the new timeline function added in the beta version and she want to try it but the link in the main page is for 64bits only, it´s possible to anyone to compile a 32bits Windows version of Drawpile 2.2 beta8?
Sorry again, I don´t know any where else to ask, thanks.

**Comment by Wade821** [comment]
No, this would be correct for it. While it is possible and something the developer would have to consider, I wouldn't recommend it for a number of reasons. While waiting for a response, here's my take on this situation.

Unfortunately, 32 bit operating systems are ancient by today's standards. And given the number of issues 32 bit Drawpile has with larger canvases even prior to the beta, it will probably be worse in 2.2 given the increased memory usage with 15 bit color. Furthermore, that device's operating system reached end of life support as of January 10th, 2023 (given it is probably running Windows 8.1), so it's not the best idea to continue using the device which may be susceptible to viruses/infections that could in turn affect other devices in your home network. As such, I'd actually consider replacing the device or switching to an alternate operating system, first and foremost. 

**If the specs listed here are correct:**
https://www.phonearena.com/phones/Asus-VivoTab-Note-8_id8288

**Then the processor is 64 bit capable.**
https://www.intel.com/content/www/us/en/products/sku/76759/intel-atom-processor-z3740-2m-cache-up-to-1-86-ghz/specifications.html

Which means in turn you could upgrade to Windows 10, 64 bit. Though that'd probably have to be a fresh install. I've included some instructions below on the path to upgrading the device, since I realize buying a new device is probably not practical in your case. 

**Alternate Resolution:**
Last I checked, I think the Upgrade Assistant is still functional for older devices to get the free upgrade. Unfortunately, I think you'd have to do the upgrade first since it will still be 32 bit. Once you have, that should "register" it with Microsoft as a valid licensed device. Then you'd need to wipe the device with a fresh install in order to switch over to 64 bit. You'd skip the prompt for a key installation from what I recall, and it would activate once connected to the internet and at desktop (since you got it upgraded to 10 with the 32 bit edition prior). Then you wouldn't need the 32 bit version for it and the system would be secure until Windows 10 end of life is reached on October 14th, 2025. 

https://www.microsoft.com/en-us/software-download/windows10

**Comment by notanartist888** [comment]
Hi, thanks for answer.
The current OS is win10 but Vivotab Note cannot be upgrade to a 64bit OS as I know because of incompatibility with the main board architecture I guest, I can´t remember right... (the cpu is 64bits but others of the main component are x86 only, or something like that)
She still using that tablet because it have a pen with it and she love to draw on screen (she tried with a graphic tablet but she say is not the same) She use Drawpile because she find to animate very intuitive on it, and the soft was very responsive when I tried too (I guess all the animations she made are 800x600 or some  like that).
May I can try to compile the code myself, but I have not idea of coding  >XP

**Comment by Wade821** [comment]
I don't believe that I've ever heard of a system locked due to the board not handling 64 bit. That's not a thing as far as I'm aware, it's only the processor which determines if you can handle 64 bit or not. If it couldn't upgrade, that's usually due to drivers. But since you're already on Windows 10, that should be a moot point. And worst case scenario, it refuses to boot from a 64 bit boot USB image. So trying it won't hurt. But I've never seen a system that the motherboard was the limiting factor in being able to go 64 bit or not. Even if the UEFI/BIOS itself was 32 bit, that just handles base system operations to get into the operating system and communicate with the processor. Past that, it should have no major influence on whether or not you can run 64 bit. It's strictly a concern of the processor. If you can load up a 64-bit only USB to even see if you can start the installation, then you can absolutely run 64 bit Windows 10 on it.

From that [same link above](https://www.microsoft.com/en-us/software-download/windows10), you should be able to create a bootable USB media for 64 bit windows, boot from the drive, and then see if you can boot up from the media. If it works, great, the system can run from 64 bit media. In that case, it *WILL* wipe everything, so you would want a backup of any desired data first. Then boot back into it, reinstall Windows 10 64 bit, and then you should be able to get it to run.

**Comment by Wade821** [comment]
I should also state that this is years of experience based on BIOS based motherboards. Newer UEFI motherboards might have different constraints that I'm not fully aware of just yet. But to me, it would seem pretty insane to have a 32 bit UEFI that can't recognize 64 bit bootloaders when 32 bit processors were stopped in manufacture for most devices years ago. ¯\_(ツ)_/¯ Also offering this information given that there may not be plans to make a 32 bit version available.

If that's really the case, then you're limited to either getting a new computer, a 32 bit version compiled, or using an alternate bootloader to handle loading that stuff for you, which is pretty ick for a tablet device. 

There are some bootloader options but this is not territory I have personal experience with if this really is the case, so you'd be on your own more or less if it fails to boot from 64 bit USB device. [Clover bootloader](https://sourceforge.net/projects/cloverefiboot/) is one I read about, I've used [Plop Bootloader](https://www.plop.at/en/bootmanager/download.html) before when I couldn't get USB boot as an option on a computer. 

I'll continue this thought in a moment, have to step away.

**Comment by askmeaboutlo0m** [comment]
Yeah, what Bluestrings said looks correct to me. Drawpile is possible to build in 32 bit mode and I've done so accidentally when building the Android version, but the automated infrastructure doesn't provide it.

Setting up a development environment on Windows is a medium to severe nightmare, so I wouldn't recommend it for a non-technical person. However, I have to fix some stuff about Windows building anyway, since apparently the documentation and reality of it have drifted apart in some way. So I'll have to do a Windows build from scratch anyway, might as well try to do that in 32 bit mode and see if something usable falls out. I don't know when I'll get to that at this point, but I'll give you a ping on any results.

I'll also duplicate this message into the Discord channel, feel free to respond wherever it's more convenient.

**Comment by askmeaboutlo0m** [comment]
Reported working. The next 32 bit verison will presumably be available with 2.2.0, as a manual build.
