### ISSUE TITLE
Fill tool restricted as a square

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#1157]
The fill tool being square in beta/continuous makes having to resize it to fill a certain section or even a circle a constant. Having the previous fill "dot" as an optional choice would be nice.

**Comment by askmeaboutlo0m** [comment]
The way it worked before was that it counted the amount of pixels filled and bailed out if it reached the amount of pixels squared given in the size limit. That made it impossible to set the size limit correctly, you can't calculate how many pixels squared a shape takes up in your head. So it won't be coming back.

While doing a circle shape would be possible, it seems unnecessary, given that you can just do multiple fills for weird shapes?

https://github.com/drawpile/Drawpile/assets/13625824/ddd3dc1f-0b10-446c-8d03-6c1fa19e7d23

It won't be happening for Drawpile 2.2, but I want to rework selections. Among other things, they should be allowed to persist when switching away from the selection tool, like they do in e.g. Krita or GIMP. That seems like it would also be an alternative for the fill tool size limit, letting you fence off the area you want to work in with a selection and using that as the "size limit".

**Comment by vipperz** [comment]
Rather than it being of selections (unless it actually is involved), I was more thinking of how 2.1 handles the fill tool as one click would fill in that whole ferret drawing you've shown, other than in 2.2 betas where having to do multiple clicks to fill it is necessary unless you make the square cover it whole. Reason I suggest of having it back as an option rather than having the fill only as a square.

https://github.com/drawpile/Drawpile/assets/51433534/65fc774e-8947-4cf4-bda5-0513e7d68929

**Comment by Wade821** [comment]
But that had its own problems is what they're saying. You had people increasing the pixel flood limit trying to figure out why it wouldn't fill, and then accidentally flood the entire canvas because there was a small gap somewhere. 

The old system essentially worked by a "square" fill as well, it just wasn't displayed as such. The difference between the new fill and the old fill is that you have a visual indicator on the max space it will possibly fill. That means that this is inherently better by default than the old one, since you couldn't visualize that information. 

Going back to the old one just brings back old problems, and thus shouldn't be brought back. The new one can be made more than large enough to fill any given desired area.

**Comment by askmeaboutlo0m** [comment]
Again, the way 2.1 handles the fill tool is impossible to understand because you can't set the size limit correctly. What it would do with my drawing is absolutely nothing, because the starting size limit is too small to fill it. So I'd have to increase the size limit by some random amount and hope that's enough. Or maybe I have a leak somewhere, in which case I'll keep increasing the size limit until it encompasses the whole canvas and I flashbang everyone.

So it won't be coming back, the old behavior was irreparably broken. You can't guess the size limit you need and you can't tell apart an inappropriate limit from a leak.

**Comment by vipperz** [comment]
Oh, well, I can understand that going back to it has issues and isn't possible to being the exact type of process back into how it was. I wasn't suggesting to specifically have it reverted, there just seems to have less simplicity in having pixels filled with the updated version if the square isn't covering the whole area/spot you're trying to fill. 

Krita, CSP, etc. have the type of fill tool that doesn't require resizing it like a brush for a specific section, so I was wondering if that similar type of thing can be implemented with the updated 2.2 as an option. Having a proper indicator of pixels and knowing it's limits is one thing, but having the option to fill a drawing/area quicker or as other drawing programs have isn't as easy.

**Comment by askmeaboutlo0m** [comment]
Those other drawing programs don't have other users drawing with you. But the option is already there: just set the size limit to a ridiculously huge value and the rectangle will end up encompassing the whole canvas.

But I don't recommend it. Magma/Aggie has a fill bucket without a size limit and every time someone uses it, they end up flashbanging everyone else because they got a leak somewhere, which is immensely disruptive, so you'll probably just make the other users upset.

**Comment by vipperz** [comment]
If it's the subject of unintentional canvas filling then I get it a bit more. Although, I'd say it would be more common to happen with the 2.2 square tool, if the size is big enough. In 2.1 it's been more common for the fill tool to not react if there's a gap ( I do remember it used to be similar to Magma/Aggie before), but 2.2 will fill in the whole square section if there's an opening.

2.1:

https://github.com/drawpile/Drawpile/assets/51433534/3849342e-885a-4d68-bcc2-778b3938fd02

2.2:

https://github.com/drawpile/Drawpile/assets/51433534/138081ed-0cdc-45be-867d-682f8f4b5057

**Comment by askmeaboutlo0m** [comment]
Yeah, the fill tool doing absolutely nothing in 2.1 was a common source of confusion. It's one of the things that made it so incomprehensible. The 2.2 fill tool will always fill to allow for the aforementioned multi-step fills, it's not an error to reach the edge of the chosen area. Since you can pick a sensible size limit, those spills aren't a problem, since it won't escape across the entire canvas (unless you set the size limit super high, in which case you get what you asked for.)

**Comment by askmeaboutlo0m** [comment]
Some changes on the fill tool will solve this issue. For one, selections are now persistent, so if you make one of those, it will be used as the size limit instead. Also, the fill tool will now preview fills and ask for confirmation instead of immediately doing its thing, which means you can safely disable the size limit entirely by turning the slider all the way up. If a fill spills, you can just cancel it without anyone else getting disrupted by it.

https://github.com/drawpile/Drawpile/assets/13625824/eb2ee140-0739-406d-97ae-84f82e1ff545

This isn't in the continuous release yet, since some other things still need to be implemented, but it should be there soonish.

**Comment by vipperz** [comment]
I think that's such a great alternative, especially with having the preview option. Really appreciate all the work you've put in, can't wait to see it implemented fully.

On a side note, would being able to click on multiple closed/cut off areas while it's still on preview and undoing each fill up to the first be a possible outcome? For example, there are multiple circles attached to each other or sections of a drawing are cut off by closed lines and need to fill all of them the same color. Having to preview and apply each takes longer and disrupts flow.

Having the apply action be clicking/double clicking on one of the filled in areas would be nice for it, if the idea could work of course.

**Comment by askmeaboutlo0m** [comment]
It's available in the continuous release now: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Letting you fill multiple points is interesting, there's not really a reason why the fill has to be restricted to start at a single point. But something I'd want to think on a bit more. I created a separate issue for it: #1319
