### ISSUE TITLE
Multi layer select and transform

### ISSUE THREAD

**Issue by CraicArReithe** [drawpile/Drawpile#1158]
would love to see an option for lasso select to select and move a part of the image across multiple layers (eg, moving image on line work layer together with colors layer etc) without having to flatten the image. even better if the current transform features had an option like this too  :)

**Comment by Wade821** [comment]
There's already a variety of open issues related to selection tool, which is planned on a revamp at some point (a list of some I found is noted below). No ETA for this feature at this time.

I've also already suggested the ability to move multiple layers in one selection at once (though that gets tricky with layer permissions that some users may not have access to be able to do that). 

#211
#292
#324
#609
#1009

**Comment by askmeaboutlo0m** [comment]
I'll write up what I think would need to be done to get something in this regard implemented.

Design-wise:

* You should be able to make and transform selections on layer groups. This just transforms everything in the group (as far as permissions allow.)
* Maybe allow selecting arbitrary layers to do a transform on. This would somehow need to let you mark one layer as the primary selected one and others as secondary selections. Maybe look at how Krita does it, they recently added like a checkbox to their layer stack that signifies this kind of secondary selection I think, which seems like a pretty good solution to me.
* Don't allow copying or cutting from multiple layers, since you can't sensibly paste it afterwards.
* Currently, you can move a floating selection to a different layer by clicking on another layer while you're transforming something. That's nonsensical when you're transforming multiple layers, so changing your selected layer should be disallowed while doing it. Changing the secondary selection while you're transforming it (i.e. checking or unchecking layers) would be okay though.
* Maybe split the selection tool into a selection mode and floating transform mode first, if that's easier to implement the above restrictions? Again, like Krita or GIMP do it. Drawpile kinda jumbles these two modes together, which is confusing to use, causes accidental deselection all the time and makes the code more complicated because the different states (selection on canvas, floating because you started transforming something and floating because you pasted something) aren't properly separated.
* If you don't have permission to alter one or more layers in the stack, it should disregard those layers. Maybe there should be a HUD message in the corner telling you that fact.

Code-wise:

* On the protocol level, no particular change is needed, we can just send a message for affected every layer. I think this is preferable over having it all lumped into a single message, since it would take the paint engine very long to process all of that in a single go, which would cause a big chug.
* In `paint_engine.c`, the `DP_paint_engine_preview_transform` would need to take multiple layers to do the transform on. Alternatively, you could call the function multiple times and allow having a dynamic number of previews, but I think that's harder to implement and would lead to worse results. Krita previews every layer individually like that and it's just a mess watching the layers jumble around.
* In `preview.c`, the `DP_Preview` struct needs to have its `int layer_id` property removed and stuck into the individual `DP_Preview*` "subclasses" instead, with `DP_PreviewTransform` getting a flexible array member `int layer_ids[]` to hold multiple of them. `DP_preview_apply` currently assumes that there's only a single layer, so that would have to become a function pointer instead that calls a type-specific implementation.
* There's some glue stuff in-between in `drawdance::PaintEngine` and `canvas::PaintEngine` that needs to take multiple layer ids. Not that exciting though, this is basically just a pass-through.
* The tool and model classes need to be adjusted to account for multiple layers. Unfortunately this is a part of the code that I'm not particularly firm on and I think some parts of it are even vestigial. So I'm not of much help here saying what needs to be changed.
* If you want to add a checkbox or something to the layer list elements, that's in `layerlistdelegate.cpp`.
* The layer list UI is in `layerlistdock.cpp`. There needs to be some connections here to signal changes to the selection state of layers. Also, there's `LayerList::currentLayerLock`, which currently unconditionally locks your tool if you have a group selected. This is called from `mainwindow.cpp`, which knows what tool is selected, so it could pass that in so that this particular lock is not applied.
* The layer list model is in `canvas/layerlist.cpp` (not `drawdance/layerlist.cpp`, that's related to `DP_LayerList`.) The `LayerListItem` may need a flag to indicate that it's secondarily selected. 
* `toolcontroller.h` also has an `m_activeLayer`, presumably that would need to get some friends `m_checkedLayers` or something, which `tools/selection.cpp` can use. Uh, try to use `int` for layer ids, not `uint16_t`, we shouldn't be lugging protocol implementation details into the higher tiers of the application.
* The copy and cut logic is in `mainwindow.cpp` and `document.cpp`. Presumably the former would be in charge of disabling those actions if you have multiple layers selected.

**Comment by askmeaboutlo0m** [comment]
Should wait for #1303 for now, since that changes how selections work fundamentally.

**Comment by askmeaboutlo0m** [comment]
This is implemented now. When transforming, checkboxes are shown in the layer list, where you can pick which layers you want to transform.

It's available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

(Currently there's a weird problem with the Windows installer (see #1201), so it might not install properly on the first go and you have to run the installer again and pick Repair.)
