### ISSUE TITLE
Remember size of external tool windows rather than use docked size

### ISSUE THREAD

**Issue by GreenReaper** [drawpile/Drawpile#116]
While playing with docking and undocking tool windows, a user expressed surprise that the external size of each tool window was reset from the size that it was when docked.

The user expected that the application would remember how big the window had been when they previously docked it, and to restore that size (probably bigger, e.g. large palette or layer window).

**Comment by Wade821** [comment]
I'm not sure about the viability of this suggestion. What happens if you have a user that removes two docks but only adds one back? Does it only remember the size/position of the very last dock that was removed? I think that's probably the most viable way of making this work without having a small coding nightmare on our hands.

_**As a side note**_, if you do have Discord, you can post suggestions there by joining it and even discussing the viability of such suggestions. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join, reference this suggestion and start a conversation! So we can maybe review in more detail or close it out.

**Comment by GreenReaper** [comment]
I'd expect the size and position to relate to each specific docked panel, e.g. the palette has one setting and when you undock it, it goes back to the position and size it was when last docked.

Ideally, the docked or undocked status and the position as size when undocked would be persisted over restarts (although I imagine you might want to make sure that it's still on the screen area so windows aren't lost due to workspace changes).

It's about having your tools in a specific place and scale (the minimum size not being the optimum size for some of them).

**Comment by Wade821** [comment]
Maybe I'm just tired. I've been up for 19 hours. Personally, I don't think is a big issue besides the fact that the navigator display dock should have a minimum size setting somewhere. That darn thing is always getting sized down to nothing. And I get wanting a consistent size, but the main dock that's always acting up for me on that is the Navigator display dock. Is there something you can be more specific about? Is it all docks? One dock in particular? Does this happen if you do a certain set of steps?

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Docks restore their size when undocking them unless you close the window in-between. Making them remember their undocked size across application restarts is something that would need to requested from Qt, the dock saving and restoring functionality can't be extended by Drawpile.

**Comment by GreenReaper** [comment]
Fair enough. For what it's worth, the issue was reported to me by an artist at a convention I was demonstrating the software at, so I didn't have answers to the follow-on questions from their perspective - I'm not a regular artist myself, I just host them and get their desire to have a consistent custom layout.

**Comment by askmeaboutlo0m** [comment]
For that particular purpose, I added a layouts dialog that lets you save and restore layouts, which I find convenient when e.g. switching between drawing and animating. So that would probably quench that desire: rather than manually docking and undocking stuff, you just load the appropriate layout, which will have the correct dock state, positions and sizes.

![image](https://github.com/drawpile/Drawpile/assets/13625824/6d93ac2f-36ad-4f36-85e2-5c7c8f67f9ad)
