### ISSUE TITLE
Crash when opening up .ora files bigger than 30 Mb [HarmonyOS/Android]

### ISSUE THREAD

**Issue by ariqhadiyan** [drawpile/Drawpile#1163]
I'm using the latest commit version and it always crash whenever I open up files bigger than 30 Mb-ish
Works fine when I open files smaller than that size

**Comment by askmeaboutlo0m** [comment]
Hmm, I can sort of reproduce this on my 5 year old phone, but only intermittently. Not too sure if it's because Android gets tired of waiting for the application to get done loading the file or if it's just running out of memory. I'll have a go at fixing the former by loading the file in the background instead.

**Comment by askmeaboutlo0m** [comment]
It now loads files in the background, showing a progress bar while it's doing so. It also no longer loads ORA files in parallel on Android, which is several times slower, but also uses that many times less memory. With this, I can load 90 MB ORA files without crashing on my phone.

It's available in the continuous release again: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

How does this behave for you, does it fix the issue?

**Comment by askmeaboutlo0m** [comment]
How does the crash happen, does it actually say "the application has stopped working" or does it just close without saying anything?

**Comment by askmeaboutlo0m** [comment]
Okay, yeah, then it's simply using so much memory that Android terminates the application. Which isn't something where much can be done about it, it just means the device doesn't have enough resources to deal with files of that kind of size without the operating system getting upset. Having a drawing open and then opening another one uses more memory than starting from a blank canvas, so that behavior also makes sense in that regard.

Hopefully using less memory during loading makes it reasonably usable anyway. Thanks for reporting it!
