### ISSUE TITLE
Zoom indicator disable option?

### ISSUE THREAD

**Issue by nagacoon** [drawpile/Drawpile#1170]
Haven't used 2.2 for a long time and just found theres no way to get rid of that popping up zoom window which has appeared in newest versions. May there be a way to hide this annoying thing like its possible with user avatars, unused docks and stuff? 
Anyway, DP already has other two zoom indicators at the very bottom and at navigator window so why actually we need more?
![изображение](https://github.com/drawpile/Drawpile/assets/154825905/d97ca35e-b521-45e7-962f-6f25e424c165)

**Comment by askmeaboutlo0m** [comment]
This is a feature taken from Kritahey don't have a way to turn those off either. It's not like the top-left corner of the canvas is particularly useful while you're zooming, rotating or flipping the canvas, so it's not interrupting anything useful and disappears again right after you're done manipulating the view. So it's neither potentially in the way of your drawing like user pointers are, nor is it a persistent element like docks, so it seems like you wouldn't get anything useful out of hiding it. But I'd happily hear the issues it causes and let myself be convinced otherwise, my own view is tainted from using Krita a bunch, so I'm very used to it.

There's several reasons for the on-canvas indicator. For one, it's just much faster to grasp, I have a way easier time spotting the on-canvas indicator than the controls at the bottom, especially with regards to if the canvas is flipped or mirrored. If you hid your docks (by default this is done by pressing Tab) or if you're in small-screen mode, those other indicators are nonexistent altogether, so the on-canvas indicator is the only thing you got in those cases. For people who draw on a screen, the bottom corners are very likely to be covered by their appendages, either their pen hand wrist if they're right-handed or by their off-hand wrist that's doing the zooming and rotating by touching, so the on-screen indicator is in a less contortive location.

**Comment by askmeaboutlo0m** [comment]
No response, so closing this.

The zoom indicator can be disabled by putting `suppresstransformnotices=true` under the [setting]` category anyway.

**Comment by askmeaboutlo0m** [comment]
Implemented now, since further, valid demand came up.

![image](https://github.com/drawpile/Drawpile/assets/13625824/84d40b2c-58ed-49b4-bebe-bb3b18e0f01a)
