### ISSUE TITLE
Make user cursors follow MyPaint brushes more closely

### ISSUE THREAD

**Issue by amoruwu** [drawpile/Drawpile#1178]
![image](https://github.com/drawpile/Drawpile/assets/78520579/b46b3c34-3ae4-4cad-8ad7-09b82eee930f)

Something similar has been suggested on discord. I'm mostly here to place it for consideration of fixing the jittering  for later And to suggest Giving 2.2 Brushes their own Receive delay option nevertheless of the jittering. Again for consistency! Also the lag and delay on 2.2 brushes

**Comment by askmeaboutlo0m** [comment]
This one is just visual smoothing, it's not related to any networking stuff like the receive delay is. Solution would be to actually recognize if the brush is jittering excessively and only smoothe out the cursor in that case, rather than doing it unconditionally and slowing down "normal" strokes for no reason.

**Comment by amoruwu** [comment]
Outside of recognizing when the slowing down might be actually be needed or not, I'm more suggesting giving 2.2 brushes their own Visual Smoothing value option like ' Receive Delay ' Or checkbox to turn it off and on.

**Comment by askmeaboutlo0m** [comment]
The algorithm has been replaced. Brushes without jitter should follow the cursor exactly now, brushes that do jitter should follow it faster than before.
