### ISSUE TITLE
Always show collaborator cursors

### ISSUE THREAD

**Issue by johannesCmayer** [drawpile/Drawpile#1194]
It would be really good I think if I could see the collaborators cursors all the time, instead of having to constantly switch between the pen tool and the laser pointer. I am using drawpile as a whiteboard, so we basically want to always see where the other peorson is pointing. Right now we need to manually switch back to laser pointer each time we are finished drawing something.

It would already be helpful if the laserpointer does not fade out after some time, such that you can gage whether the other person can see what you are drawing. Even more useful would be to overlay their viewport.

**Comment by askmeaboutlo0m** [comment]
This is a questionable feature. Drawpile is a drawing program, not a whiteboard, so showing other people's cursors permanently or superimposing their viewport would be outright disruptive to its purpose. I've only just implemented a feature to *hide* user cursors when they are close to where your own cursor is (enabled by default, but can be toggled off.)

Changing how long cursors or laser trails persist is something that could be implemented though. Which one are you talking about when you say "laser pointer", the user marker from it or the trails drawn by it?

**Comment by amoruwu** [comment]
Not sure but wouldn't it also cause more traffic?

**Comment by askmeaboutlo0m** [comment]
In the general case, yes, it would have to constantly send messages to update the pointer position. Not in this particular use case though, since everyone is intentionally switching back to the laser pointer anyway.

**Comment by johannesCmayer** [comment]
@askmeaboutlo0m I would like the user marker to be shown all the time.

**Comment by askmeaboutlo0m** [comment]
User pointer stay time can now be configured, the UI provides a few sensible values for it. For your use case, you'd probably want to set it to "Forever" (and disable "Hide From Cursor".)

It's available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for suggesting! I'll retitle this issue so that it reflects what was actually implemented.

![image](https://github.com/drawpile/Drawpile/assets/13625824/e11a3e62-e2ee-44be-b2ca-f446727c60ab)
