### ISSUE TITLE
Fill tool and Selection tool aren't working properly

### ISSUE THREAD

**Issue by Venesio** [drawpile/Drawpile#1197]
For some strange reason, i can't use the fill tool anymore
i can't click the icon, and the keybind just won't change to it

And selection tool doesn't work as it can't resize and i can't move the selected drawing too

**Comment by askmeaboutlo0m** [comment]
Which version of Drawpile are you using? Help > About Drawpile will say it at the top.

What does it mean that you can't click the icon, is the button disabled in some way?

**Comment by askmeaboutlo0m** [comment]
The most likely reason you can't do either of these things is because the session doesn't give you permission to use the fill tool or selections. You can check that in Session → Settings, in the Permissions tab. It's these top two permissions.

![Session permissions](https://github.com/drawpile/Drawpile/assets/13625824/e1ffe6d5-068e-4d17-9942-e9a437f9d401)

**Comment by Venesio** [comment]
OH THAT WAS THE ISSUE LOL

thank you, it's fixed now!

**Comment by askmeaboutlo0m** [comment]
Cool! It could definitely be clearer what's going on in those cases. I made an issue #1198 to get that fixed at some point.
