### ISSUE TITLE
Hardware-accelerated canvas

### ISSUE THREAD

**Issue by askmeaboutlo0m** [drawpile/Drawpile#1199]
The QGraphicsView-based canvas view is pretty slow, especially in the web browser. It also suffers from various bugs, like the background not resetting properly or pixels jittering.

This is largely because it uses a software renderer, which involves blitting pixels via the CPU. That's pretty silly though, because every device nowadays has graphics acceleration and can blast pixels to the screen way faster if using the proper interface.

A hardware-accelerated canvas view should be implemented, using Qt's QOpenGLWidget.

**Comment by askmeaboutlo0m** [comment]
Open issue: on Windows, it seems like opening a second window hangs.

**Comment by MorrowShore** [comment]
Could not reproduce the issue.
Both old and new windows function without issue.
![image](https://github.com/drawpile/Drawpile/assets/97566823/04624255-2462-4b98-a506-b4eddf218e2c)

**Comment by Wade821** [comment]
> Could not reproduce the issue. Both old and new windows function without issue. ![image](https://private-user-images.githubusercontent.com/97566823/320662640-04624255-2462-4b98-a506-b4eddf218e2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTg3NDQsIm5iZiI6MTcxMjYxODQ0NCwicGF0aCI6Ii85NzU2NjgyMy8zMjA2NjI2NDAtMDQ2MjQyNTUtMjQ2Mi00Yjk4LWE1MDYtYjRlZGRmMjE4ZTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDIzMjA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmOWY5NDVmMjAzZmFjYmNjMzQ4ZThjY2NlMGFhMTg2YjA3NTcwYWE2NzE3YjcyZmQ2YmFhZGRhODNhNWZmMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xGPbgTBMgh46uKPrkTNS550UO-Lbz8o2hT45rydGuOw)

If you open via shortcut, that spawns a new exe process and the behavior doesn't occur. If you use the reconnect banner on disconnect, or go to session, join/browse, the issue is triggered.

**Comment by MorrowShore** [comment]
With new reproduction steps:

1. Set renderer to hardware (& restart to apply)
2. Create / join an online session
3. Inflict change to canvas
4. Disconnect from the session (by disabling internet momentarily)
5. Reconnect to the session

The issue is reproduced.

![image](https://github.com/drawpile/Drawpile/assets/97566823/aa13dec8-4440-4754-9da8-c41ad3bb0676)
![image](https://github.com/drawpile/Drawpile/assets/97566823/bcb5bcae-fbe3-455f-9f7a-4f66150a34d3)
![image](https://github.com/drawpile/Drawpile/assets/97566823/fd0f1757-b86c-427e-b79a-5600e2f6abfb)
![image](https://github.com/drawpile/Drawpile/assets/97566823/eb414d1b-5122-41ee-b357-2542877c6569)
![image](https://github.com/drawpile/Drawpile/assets/97566823/c924b38f-4119-456d-96fe-2ab06688d915)
![image](https://github.com/drawpile/Drawpile/assets/97566823/7dc2428f-238c-4734-b061-e7d57e4f08d5)

**Comment by askmeaboutlo0m** [comment]
I've edited the reproduction steps above. Also happens on Linux that way.

Easier steps to reproduce: draw a stroke on the canvas, then attempt to open a file. Seems like it only doesn't happen when creating a new file.
