### ISSUE TITLE
CMake Error: "QT"

### ISSUE THREAD

**Issue by BssnakeMing** [drawpile/Drawpile#1271]
```
CMake Error at CMakeLists.txt:95 (find_package):
  Could not find a package configuration file provided by "QT" (requested
  version 5.12) with any of the following names:

    Qt6Config.cmake
    qt6-config.cmake
    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.
```
source code dir: C:/Users/Administrator/Drawpile
build binaries dir: C:/Users/Administrator/Drawpile/newBuild
Platform: Windows

Everything else is default, what do I need to do?

**Comment by askmeaboutlo0m** [comment]
Make sure you are running this in the "Visual Studio x64 Command Line", not just regular cmd. Otherwise the environment will not be set up to find any dependencies.

If that doesn't work, you didn't install the needed dependencies via vcpkg as described in the documentation, Qt is part of those. You can re-run step 4 of those and it should continue installing whatever is missing: <https://docs.drawpile.net/help/development/buildingfromsource#windows>
