### ISSUE TITLE
Reduction of unnecessary drop-down menus

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1279]
Drop-downs that involve 3 or less items should become buttons, 

This would reduce 1 unnecessary user interactions and improve user experience. 

![image](https://github.com/drawpile/Drawpile/assets/97566823/74f43cde-4f0b-4550-bc6e-6b6274aa5af3)

**Comment by askmeaboutlo0m** [comment]
Screenshot is invalid because the fill tool has since gained additional buttons next to this drop-down and #1189 would add additional modes to it, so we'd just be going back and forth.

I can't find any other instances of this where it would be possible or sensible to replace it. There's some drop-downs that have fewer options, but they're in rarely used places where having longer text available is worth more than saving a click.

Is there any drop-downs of this sort that could be replaced?
