### ISSUE TITLE
Selections: Merging Selection Modes

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1284]
Selection modes can be merged to be an effective general or default option like so:

![image](https://github.com/drawpile/Drawpile/assets/97566823/2ae58d0c-4d6c-4771-bb3a-959f7eaf769d)

**Comment by askmeaboutlo0m** [comment]
This is also a thing in Krita, where the cursor indicates what it's going to transform. They unify moving, scaling, shearing and rotating into a single mode, but distortion is still a separate one.

**Comment by askmeaboutlo0m** [comment]
The separate rotate/skew mode is gone now. You rotate by dragging outside the selection and skew by dragging the edges.

Scale and distort are still separate modes because I didn't like any of the alternatives. Putting the handles outside like in your example is odd because they really refer to a point pretty far away. Putting a handle inside a handle like GIMP's unified transform tool makes it hard to hit the correct one. Both variants are also just not nice to look at, there's so much stuff there.

Having them as separate modes like this ends up being plenty fast to use already anyway, since you can just toggle between them by clicking into the transform. So I'm happy with the modes being partially combined like this, it looks and feels good to me.
