### ISSUE TITLE
Personal server - Can connect on web through desktop browser, but get Connection Failed when using mobile browser..

### ISSUE THREAD

**Issue by Invertex** [drawpile/Drawpile#1309]
I have a 2.2 server hosted on a Linux web server instance, using the Docker method. I can connect to it fine using the Desktop client and web browser on Desktop as well.
But when I try to do it on web browser on phone, it says Connection Failed. And the red error says "Disconnected. The remote host closed the connection.".

Is there a certain server setting related to this perhaps?

Or does not having TLS enabled make it not possible to use phone browser?
(I also don't have an SSL cert for https on this server, it's just an IP address)

Thanks!

**Comment by Wade821** [comment]
Really need to use self signed certs or let's encrypt at minimum. Multi threading in browsers apparently only works with SSL from what the developer told me. It's not an ideal situation.

I've got a script for setting up a server with hostname, either let's encrypt or free hostnames (freedns, duckdns, no ip).

**Comment by Invertex** [comment]
Oh that's a weird restriction, dang.

The server I'm hosting it on is an Oracle Linux server, which is only an IP... I have a domain on Namecheap that I can alter the DNS on to make the sub domain point to the IP. But figuring out how to get that LetsEncrypt verified has been a headache I haven't solved, as backend web stuff is not my wheelhouse. I've got acme.sh setup on it with LetsEncrypt already for verifying SSL on that side of things, just not sure what would be involved in this specific scenario. If you have any tips on that I'd love to hear...

Would be interested in seeing that script if I can get it workin tho! Thank you.

**Comment by Wade821** [comment]
I'm busy today and about to be unavailable for a few hours, but here's the commands to get started. Only supports Fedora, Ubuntu, Debian, and Raspbian. I know it's in the testing folder but it's recently been used to set up a few different servers. You're granted authority to choose most options in the script. Just bear in mind that since you'll have a paid hostname option, you'll want to skip the option for freedns/duckdns/no ip after compiling the server. 

wget -q --show-progress https://raw.githubusercontent.com/Wade821/PiDrawpile/master/testing/drawpile-installer-official-build-from-sources-with-listserver-and-webadmin2

sudo chmod 770 ./drawpile-installer-official-build-from-sources-with-listserver-and-webadmin2

./drawpile-installer-official-build-from-sources-with-listserver-and-webadmin2

**Comment by askmeaboutlo0m** [comment]
Yes, the restriction is a general browser thing. HTTPS websites can't access unsecured resources. And you can't run the client on a plain HTTP website because that will disable multithreading support for, uh, [reasons that have nothing to do with the site being HTTPS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements).

The [all-in-one Docker setup script](https://github.com/drawpile/dpserver) can also set up Let's Encrypt for you. It asks you for a domain name and an email address and then provisions it automatically. If you didn't do that the first time around, you can blow away your containers with `docker-compose rm --stop`, then delete the whole directory and start the setup again.

**Comment by Invertex** [comment]
I'd like to avoid blowing away the containers if possible, since they are several persistent sessions that me and my friends have evolving canvases on.... I might just have to pick apart those scripts and find the relevant part then. Thanks for the advice everyone!

**Comment by Wade821** [comment]
If you need help, consider joining the discord server or use the IRC chat. Both are in app on the welcome page when starting drawpile.

**Comment by Invertex** [comment]
Thanks! I managed to fix it though, in the end I just needed to run `./configure.sh` and set it to use my domain name instead, enable the certbot setting and everything ended up working from there, no resets needed! Didn't think it would work out that simple haha
