### ISSUE TITLE
Buttons too small / unreadable

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1324]
Here's how Drawpile looks on a 4k screen. The quick transform buttons are practically unreadable.
![image](https://github.com/user-attachments/assets/b76da279-bcfc-4519-a73a-4f8ec6a05602)

This especially becomes an issue with certain phones or tablets that have high resolution but compact screen size, which make fingers unsuitable for usage.

Proposed change would be to either:
1- Scale button sizes and create multiple presets according to screen resolution / size.
2- Make all buttons larger by 60%~100% per default 
3- Stretch all buttons to make use of the available horizontal space (recommended)

**Comment by MorrowShore** [comment]
Here's a mockup of a sleek implementation of this. (buttons are horizontally stretched to occupy the available space)
![image](https://github.com/user-attachments/assets/9c058eea-001d-44e9-bb87-f8d317648f8e)

Here's the mockup of a crude implementation, where buttons are enlarged by 50% in both axis, rather than just one.
![image](https://github.com/user-attachments/assets/8b864adb-f1df-4e6c-8a60-0e1a3c7cc6ea)

**Comment by askmeaboutlo0m** [comment]
The header and footer buttons in the brush, selection, transform and layer dockers now spread out more. They still leave some room stretch outside of them, since filling out the entire width makes it look overly cramped and would actually increase the minimum required size by a little bit for the fixed spacing required, so I think this is a sensible solution. It means that on large resolutions with wider docks, the buttons will be wider and on smaller resolutions they will remain at a small size like before.
