### ISSUE TITLE
Hex Field in Sliders Dock

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1344]
A hex field in the slider dock would be great to have.

![image](https://github.com/user-attachments/assets/6b4c9a69-e9a6-4050-b0dd-49beb59537e8)
---
This is an idea to prevent misinputs from ruining the color:
For the first click / focus, you should be able to either copy, or paste a hex value in, but not backspace / edit.
For the second click, you should be able to edit it. 

---
And since there's going to be an additional row, we could accommodate a color mode button, which when pressed, changes the G slider to Y, for RYB mode. This way we cover both the pigment RGB, and the wavelength RYB modes. 
![image](https://github.com/user-attachments/assets/4a8f83a5-1466-4046-82ed-b10d9e959433)

**Comment by askmeaboutlo0m** [comment]
The additional row is an issue, since it will increase the minimum size of the dock. Which is not something we can reasonably do, the sliders are already the largest of all the color docks.

However, the way to solve that may be already mentioned here: the toggle button between color spaces. Instead of 6 sliders, we only show 3 and let you toggle between RGB and HSV/HSL/HSY. That would make the dock *smaller* than before and is how Krita's "specific color selector" docker works, for example.

Downside being that you need an extra click to twiddle a different set of sliders, but presumably wanting to mess with both models simultaneously isn't particularly useful to begin with? At least I've never had that desire.

**Comment by askmeaboutlo0m** [comment]
This is implemented now, with three sliders and a toggle switch, which gives room for the hex edit and makes the dock smaller overall. If this breaks someone's workflow, we can think about putting a setting in that shows all sliders again.

![Color sliders with hex field and toggle button](https://github.com/user-attachments/assets/58c7dc9d-0b53-4f48-b024-0661ac6d64ac)

Adding RYB is an unrelated matter and I've never heard of anyone wanting to use it, so I'd wait until it's actually requested before even thinking about it.
