### ISSUE TITLE
Deselection using Backspace, Delete, and ESC

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1357]
Hello. 
This is a rather simple feature. It involves adding the keybind of ESC, Delete, and Backspace to deselect your selections.
From transform tool, it would return to selection (currently only ESC does this).
Compatibility concerns would involve preventing their infliction when combinations that involve mentioned keys are pressed.

**Comment by askmeaboutlo0m** [comment]
Escape means cancel the current tool operation, it doesn't mean to deselect. I don't want my selection to disappear because I pressed cancel when I happened to not have something to cancel, that's spooky action at a distance.

Delete is already bound to deleting the contents of the selection. Deselecting is a separate act from deleting the contents of a selection, if you want to get rid of the selection.

Backspace could be bound to deselect by default, but that's a matter of #1206.
