### ISSUE TITLE
Overwriting Drawpile with portable ZIP causes Installer to not work

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#1358]
One of the Continuous Windows Installer's may have accidentally stopped midway at first, but wouldn't install fully in trying to use Repair the next time. Using the ZIP causes it to update, but once I try to install newer versions of the Continuous Installer, it only installs around 65mb of the update instead of 100+mb as it usually does.

I'm not certain if it's a bug or a normal occurrence that happens when updating with a ZIP.

**Comment by askmeaboutlo0m** [comment]
Hmm, what do you mean "using the ZIP"? The ZIP is not supposed to be put into program files, that will mess up the installation I think.

**Comment by vipperz** [comment]
Oh, I meant copying all the files from the ZIP into the Drawpile programs files. Seemed like the only option to do since using Repair from the installer wasn't working at all.

**Comment by askmeaboutlo0m** [comment]
Hmm, it's not something I can reproduce. But there was a problem with an earlier version of the installer in the continuous release, because the toolage broke and started generating invalid installers, so you may be affected by that.

Try going into the Add/Remove Software control panel and you may see multiple instances of Drawpile there. Uninstalling all of them and then installing it fresh should hopefully fix the problems? It won't delete any of your configuration.

**Comment by vipperz** [comment]
There was only one instance of Drawpile, but I deleted it and used the Installer again. For some reason it was showing the previous first Beta.3 version at first, so I used the installer again to Repair and that seemed to have fixed it.

Not sure if I would need to use Repair again for the next update, but hopefully not.

**Comment by MorrowShore** [comment]
Solved. 
Potentially related to #1201.
New installers have been fixed and don't seem to have this issue.
