### ISSUE TITLE
Allow disabling socket proxy

### ISSUE THREAD

**Issue by FishEggsThe** [drawpile/Drawpile#1360]
As the title suggests, I'm unable to host sessions or join sessions, whenever I try I just get the error message 'Could not connect to server Proxy denied connection'

**Comment by askmeaboutlo0m** [comment]
That sounds like you or your network are using a proxy that does not allow Drawpile through. Are you using some kind of VPN application or are in a non-residential network, like that of a business, hotel, university or similar?

And generally, what operating system are you using and which server are you trying to connect to?

**Comment by FishEggsThe** [comment]
I'm not on a vpn and I'm using my home internet, my operating system is Windows

**Comment by askmeaboutlo0m** [comment]
Okay, odd, then some further troubleshooting to narrow down what's wrong:

*  Does restarting your computer change anything? Sometimes the network card gets wedged in a weird way and restarting just fixes it.
* Which server are you trying to connect to? Do others behave the same way? You can find some public servers to try at <https://drawpile.net/communities/>. To rule out something being wrong on the server-side that's blocking you somehow.
* Does the web version at <https://web.drawpile.net/> let you connect to anything? The browser goes through different protocols, so if it's your ISP blocking something, this may go through.
* Do you have another system you can check? Like, another computer, an Android phone or tablet or a Linux to boot into. This would rule out network issues and instead point to something being wrong with that particular computer.
* Can you connect to yourself? You can try this by opening Drawpile twice and then in one window host a session "on this computer" and then connect to `localhost` in the other window. If this doesn't work, it's almost certainly something wrong with the way the network is set up on that computer.

**Comment by FishEggsThe** [comment]
1. As far as I know it doesn't, had this same problem months ago so.

2. I attempted to join a server from the link and the same error occurred.

3. I tried it and was actually able to get into a lobby.

4. I have a Mac laptop with Drawpile, but I can't access it since the developers can't be verified. I may try to solve that later.

5. Can't do that since I can't host in the first place

**Comment by askmeaboutlo0m** [comment]
Okay, then it's definitely something with the Windows setup that's off. That's making me somewhat hopeful that it's something that can be worked around in Drawpile.

I've made a build that tells the network socket to not use any proxies, rather than use the system default. Can you check if that works? You can grab the build here, it's under the "Artifacts" and the link "Drawpile-Windows-x86_64-Qt5.15.14": <https://github.com/drawpile/Drawpile/actions/runs/10394454283>

The build is double-ZIPped because that's how GitHub Actions rolls for some reason.

**Comment by FishEggsThe** [comment]
I have tried out the build and the error does not occur, I can host and I can join others.

**Comment by askmeaboutlo0m** [comment]
Alright, cool! You can keep using that build for now, it should be stable.

I'll have to think a bit on how to solve this issue in the general case. Drawpile probably shouldn't disable the proxy unconditionally like that build does, but should offer a setting. And I guess ideally catch this error and offer you the option of disabling the proxy right there. I'll update the issue title accordingly.

**Comment by FishEggsThe** [comment]
Alrighty, thank you so much for your help!

**Comment by askmeaboutlo0m** [comment]
Okay, I've added some stuff into the continuous release, if you could check that out to see if and how it works for your case: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

For one, you can take a look at what proxy configuration Drawpile sees via Tools → Developer Tools → System Information. Scroll all the way down and it should show you some information about it - for me it's "no proxy" evidently, but for you it should show something. Maybe that helps figure out where the proxy is even coming from.

![System info dialog with proxy information](https://github.com/user-attachments/assets/78c52729-69d7-4a4a-a6d7-c1a214d1b6b6)

Then Drawpile now automatically tries to detect if the proxy is actually usable to make a connection. If not, it will automatically disable it. So ideally, that should already fix matters for you.

If not, you can manually disable the proxy under Edit → Preferences, in the Network tab under Network proxy. That's also mentioned in the error message if a connection fails because of something being wrong in the proxy.

![Network proxy preferences](https://github.com/user-attachments/assets/ccfce757-eb53-48fa-8694-0d17eb3b918a)

**Comment by FishEggsThe** [comment]
I downloaded both the portable version and installer and both versions worked. Was able to host a session with a proxy detected.
Here's my System Info and Network Proxy configuration which I have not touched.

![image](https://github.com/user-attachments/assets/3482d012-54ce-4982-944d-72d64363c953)
![image](https://github.com/user-attachments/assets/e74d8ec6-07cd-48a9-913d-f49913cae437)

**Comment by askmeaboutlo0m** [comment]
Alright, thanks! 10.10.10.1 is a proxy on your machine anyway, you may have something installed in that regard. But yeah, since it's a HTTP proxy, Drawpile detects and disables it for non-HTTP connections now.

Thanks for helping test it! You can keep using the continuous release then until the next version comes out.

**Comment by FishEggsThe** [comment]
Alright, thank you so much for your help!
