### ISSUE TITLE
Canvas Shortcut for HSV

### ISSUE THREAD

**Issue by MorrowShore** [drawpile/Drawpile#1407]
There could be a Keyboard shortcut for adjusting the hue/saturation/value of color. 

MyPaint has this, although the implementation leaves much to be desired.

(Submitted by: Dann DeCairns)

https://github.com/user-attachments/assets/1efdd350-7238-4449-b197-ff8b665cdb4e

**Comment by askmeaboutlo0m** [comment]
I think it would make to implement this as a canvas shortcut (as opposed to an action shortcut) because we already have an analogous thing for this in the form of changing the brush size, where you hold down a key and move the cursor to adjust. That gives more control than a raw key press you have to time correctly. It also makes sense for showing an on-canvas preview of the color being changed.

The shortcut should obviously adhere to your selected color space, so if you're e.g. using HCL, it should adjust chroma instead of saturation and luminosity instead of value.
