### ISSUE TITLE
Feature: real stabilizer for classic brushes

### ISSUE THREAD

**Issue by blurymind** [drawpile/Drawpile#179]
What it is:
Its a value that slows down your stroke. This makes it much easier to draw precise, smooth strokes.

Some people call it "lazy mouse" - zbrush.
In blender it is called "smooth stroke"
In krita it is called a "stabilizer" - they even have a number of variants of this same feature.
https://www.youtube.com/watch?v=YpXT_Mx_u6k

In inkscape, it is the "Mass" value of the calligraphy pen tool
https://inkscape.org/en/doc/calligraphy/tutorial-calligraphy.html
"In physics, mass is what causes inertia; the higher the mass of the Inkscape calligraphy tool, the more it lags behind your mouse pointer and the more it smoothes out sharp turns and quick jerks in your stroke. By default this value is quite small (2) so that the tool is fast and responsive, but you can increase mass to get slower and smoother pen."

and so on.
I literally cant ink without this feature. :)

**Comment by callaa** [comment]
Right now Drawpile has a simple sliding average smoother, which I think is equivalent to Krita's "Basic Smoothing". (Or at least seems to be, I haven't checked the source code yet.)
Krita's "Weighted Smoothing" seems to be the feature you describe. I'll take a look at how it works and see if a similar feature will be easy to implement.

**Comment by blurymind** [comment]
Thank you! Looking forward to it :)

It would be very convenient if it can be assigned on per individual brush basis. So my inking pen for example would be set to "weighted smoothing" of 1 for example

**Comment by LionsPhil** [comment]
I've done some digging through the (massive) Krita codebase and from I can tell their smoothing is mostly implemented in [kis_tool_freehand_helper.cpp](https://projects.kde.org/projects/calligra/repository/revisions/master/entry/krita/ui/tool/kis_tool_freehand_helper.cpp) (with parameters set [with the brush tool](https://projects.kde.org/projects/calligra/repository/revisions/master/entry/krita/plugins/tools/defaulttools/kis_tool_brush.cc)).

It looks like their "stabilizer" one is actually time-based, not just distance/move-event--based. I think the same is true of Sai's stabilizer, at least in its normal (non-S) mode---if you rest the stylus mid-stroke, the ink catches up to you. From the looks of `getStabilizedPaintInfo` it's a plain uniform average after that, with some tricks to get the start and end of the line into place (`stabilizerStart` and `stabilizerEnd`...in practice the weighting is non-uniform at the start since they pad out the buffer with the initial point; it will be non-uniform differently to my pull request, though).

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Partially implemented in the form of MyPaint brushes, they have a proper stabilizer. Classic brushes still lack it though, so keeping this open.
