### ISSUE TITLE
Cannot resize window with all docks visible

### ISSUE THREAD

**Issue by ghost** [drawpile/Drawpile#193]
Drawpile, by default, starts up with most of the dockable windows docked and visible. This makes the window taller than the space I have available.

![drawpile](https://cloud.githubusercontent.com/assets/10896954/7436655/e1f346e0-f04f-11e4-889a-a351a5f367c3.jpeg)

When maximized, the window still doesn't fit on the screen.

![drawpile1](https://cloud.githubusercontent.com/assets/10896954/7436656/e1f36422-f04f-11e4-95b0-ccca85ea5089.jpeg)

After detaching or hiding some of the docks, the window became very flexible. I think that Drawpile should avoid this issue either by being able to squeeze the docks, making the sidebar scrollable, making it possible to 'roll up' the docks (like in Inkscape), or open with fewer docks by default.

I am running Parabola GNU/Linux (read Arch Linux) with KDE and Plasma 5.

**Comment by callaa** [comment]
This is indeed a problem. The brush settings dock and the color dock are the biggest offenders, all the rest can be squeezed pretty short.

A scrollable dock section (like mypaint) would be one solution, but I'm not sure if Qt supports directly. A dock that can be rolled up would not entirely solve the problem, since they would force the window bigger when opened.

On my desktop (Plasma 5), the window is about 900 pixels tall when squeezed as short as it gets. This is a bit more than I'd like. Ideally, the default layout should fit in a 1024x768 desktop, which I think is pretty much the smallest resolution in wide use these days.

The brush dock is about as compact as I can make it, but it might be possible to make the color dock a little smaller (perhaps by separating the RGB and HSV sliders to their own tabs or removing the spinboxes. For exact color selection the popup dialog could still be used) which might be enough to make the whole main window fit into a 768px tall desktop.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

The default layout has been adjusted to fit better on small screens and the docks can be squeezed tighter. This will be coming in Drawpile 2.2.

![image](https://user-images.githubusercontent.com/13625824/227511733-6b547495-6dfd-4b2e-92ec-20e12fe5fde9.png)
