### ISSUE TITLE
Broken brushes and a few other bugs

### ISSUE THREAD

**Issue by AliceFox** [drawpile/Drawpile#194]
0.9.9 on Windows.

Undo: After I had used Undo a few times it started to cause multiple steps to be removed with one click.

Brushes (including watercolor and pen): Right after that brush settings were locked. No matter what brush I changed to or what color I picked, when I drew on the canvas it was the same brush I had been using previously despite showing me something else in the docked window.

When I restarted the application to fix this I could no longer draw at all. The brush stroke preview shows up empty on some brushes. Even on the ones where it appears, none of them will make a stroke on the canvas.

Third bug: I can't set Alt as a shortcut.

**Comment by callaa** [comment]
I'm unable to reproduce the bug. Does this happen in online or offline mode? If the problem still persists, you can try deleting drawpile's registry entries to clear out the possibly corrupted settings. (This currently has to be done with the regedit utility, but I'll probably add a button to do this in the next version.)

Alt key cannot be used as a shortcut by itself. This is a framework limitation that would be quite difficult to work around.

**Comment by AliceFox** [comment]
Offline mode. Deleting reg entries did fix it.

Understood on Alt, no worries. Although that leads me to another thing I'd consider a bug: the shortcuts aren't unique. I bet messing with shortcuts prior is what caused my other bugs. I could have had one shortcut doing two things without even knowing.

**Comment by callaa** [comment]
I added a button for resetting all settings.
On my computer, the program does show an alert box when using a shortcut that has been multiply assigned. Although, this might be a feature of the Linux platform plugin, so I'll have to try it on Windows too.

**Comment by Wade821** [comment]
I'm going to assume given the age of this issue that it has long since been resolved. If not, reopen or join the Discord for help. 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.
