### ISSUE TITLE
Brush dock redesign brainstorming

### ISSUE THREAD

**Issue by callaa** [drawpile/Drawpile#201]
This is a discussion issue for improving the brush settings dock in Drawpile 2.0.
Currently, the dock looks like this:

![brushdock](https://cloud.githubusercontent.com/assets/464576/8029787/8367f87c-0dc9-11e5-9d82-8297adb24612.png)

There are five tool slots for keeping presets, blending mode dropdown, toggles for (in)direct drawing mode, brush options and pressure sensitivity checkboxes.

Some thoughts:
- Does anyone really use the tool slots? Would some other method of storing presets be better?
- How often do you need to adjust opacity, hardness and spacing?
- Double sliders for adjusting the pressure range rather than checkboxes?
- Would a list of saved brushes (like most other programs have) be a better way to switch between presets?
- If we have a brush selection box (like in Mypaint), the separation to pen/brush/watercolor might not be needed anymore
- Per tool smoothing and pressure curve settings?

**Comment by NHungate** [comment]
The tool slots are a nice concept, but would find more use if they were slots bound to a tool rather than tools bound to a slot.

Here are my thoughts coming from various other art programs:

1. Binding colors to each tool preset makes it difficult to switch between tools and if only one thing could be changed, I would vote for this. It's more intuitive to separate the tool from the color for digital mediums.
2. Binding tool types to a slot limits your kit to 5 items at a time so it takes time to modify settings. I've found myself having 3-4 key tools and the 5th slot is left as a flex slot so that I spend less time adjusting anything beyond the tool size. Brush presets would be a more useful option and could be combined with the tool slots if custom brushes aren't able to be implemented.
3. Pen pressure would be better suited to being bound per tool slot as many modern tablet drivers can provide global pressure adjustment. This would make it easier to have unique presets such as a brush pen, heavy oil brush or a faint sketch pencil.
4. A pressure curve per setting (size, opacity, hardness, color) would be a nice-to-have, but not essential. This gives more control for those interested

**Comment by callaa** [comment]
Good suggestions, thank you!

**Comment by blurymind** [comment]
I like bounding a tool to a slot myself. That way I can have brushes in multiple sizes,colors and modes.  If you remove that part, then you would remove the ability of the user to easily set brush presets. 

I say keep it, or move the "Slots" design as another tray, instead of replacing it. A lot of other sotware like artrage and paintstorm studio allows for the ability for the artist to create their own toolbox. It lets them personalize the software.
https://www.youtube.com/watch?v=p1OPwY4gWbY
https://youtu.be/oXUReniLyqw
It would be nice if we can increase the number to something higher - like 8-10 slots.

**Comment by blurymind** [comment]
- One thing you can do is remove the "Eraser" tool altogether and add it as an "Erase"  blending mode to all the other tools that generate pixels. So you can have the eraser act as a straight line or a circle and so on.

 -  Right now the slot icon is communicating the color that is set to the tool. That is absolutely fantastic design. You can take it even further if in the tool slot's icon you communicate the tool's blending mode.

 - Pen, brush and watercolor tools can be merged in one brush tool. The pen tool functionality can be added to the brush tool with a checkbox for "Anti-aliasing". If you want the brush tool to act as a pen tool, just uncheck the anti-aliasing checkbox. Merging the watercolor brush with the brush tool would be a bit more complicated. Apart of adding a smudging slider to the normal brush tool, you would also have to tell it to disable incremental and indirect drawing when smudging>0.

**Comment by Kavukamari** [comment]
I think my vote would go for a toolbox kinda similar to sai where you can have a custom list of tool presets rather than slots where you sorta keep temporary tools, cause it is a bit of a hassle to change settings at the moment. also I end up always forgetting to change my color back when i switch tools too, so I'd also support separating color from tool settings as mentioned earlier too

**Comment by callaa** [comment]
Continued in issue #437
