### ISSUE TITLE
transform tool - stamp with "behind" + other blending modes, add to and remove from selection, etc

### ISSUE THREAD

**Issue by blurymind** [drawpile/Drawpile#211]
Some times it is advantageous to stamp a drawing with a "behind" blending mode. Additionally it is currently not possible to add to selection (shift) and remove from selection (ctrl). Once you make an initial selection, you are immediatelly switched to the transform selection mode.

Some suggestions for the select/transform tool (new features):
- Blending modes for the apply and stamp actions
- Selection modes - add to selection mode,  remove from selection mode, transform selection mode
- icons to select selection mode (add to selection, remove from selection, transform selection)

For better feature discoverability (new buttons/sliders):
- checkbox in the  tool options for uniform scale
- rotate slider
- button in the tool options to execute the stamp command ( "stamp")
- button in the tool options to apply the transformation and exit ("apply ")

quick mockup:
![transformtooloptions](https://cloud.githubusercontent.com/assets/6495061/8413947/1324f418-1e9d-11e5-9f0f-d9f031feb25f.png)

**Comment by askmeaboutlo0m** [comment]
This is effectively implemented now. Selections and transforms are now separate, allowing manipulating selections after making them. Blend modes and opacity can be picked in the transform tool, which apply to stamping, pasting and transforming. An apply and a cancel button are also there. Rotation is now available by dragging outside of a transform, rather than having to discover the magic click on it, so I don't think a slider is needed. Uniform scaling and stamping aren't sufficiently important to have a permanently visible spot in the UI I think.

It's available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for suggesting!
