### ISSUE TITLE
New Feature: Selective Zoom

### ISSUE THREAD

**Issue by FristART** [drawpile/Drawpile#226]
I'm not sure if I'm just missing it, but beyond the zoom tool at the bottom, I can't find a more user friendly one. Basically, what I request is an improvement upon the zoom tool.

I'd like to be able to pick a spot on my image and drag a square of exactly where I want to zoom in on, as opposed to having to reach all the way to the bottom toolbar that freqently gets blocked by my hideable windows taskbar, zooming and then manually dragging to a spot. If possible.

I'd also request that it allow me to zoom out simply by tapping.

What I describes is basically my personal setup of the zoom tool with Paint Tool SAI. It's constantly set to zoom out, but zooms in on spots I drag-select.

Thanks for your time!

--Frist

**Comment by callaa** [comment]
There are a few ways you can zoom, other than the slider:

* Ctrl++ and Ctrl+- (configurable via the settings dialog)
* Hold Ctrl + mouse middle button and drag up & down
* Ctrl + mouse wheel up & down
* Pinch gesture on touch screen or macbook trackpad

I'm marking this issue as closed for now, but if these methods do not fit your work flow, please comment and I'll reopen it.

**Comment by FristART** [comment]
Yeah, not quite doing it for me, I don't have a middle mouse button/wheel on my laptop :x, and the keys are a bit out of reach working on a cintiq.

**Comment by callaa** [comment]
Does holding one of the buttons on the stylus and dragging up&down work? On my old Bamboo, the upper rocker button works the same as the middle button on a mouse.

**Comment by Wade821** [comment]
Drawpile released a zoom tool with version 2.1.0. Closing this issue. If this issue is still relevant, please comment so it can be reopened.

https://drawpile.net/news/release-2.1.0/

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.
