### ISSUE TITLE
Splitting recordings

### ISSUE THREAD

**Issue by akunim** [drawpile/Drawpile#236]
I've been having a great time running a dedicated drawpile server so far -- getting to meet people and draw together is always an interesting experience! 

One concern has been the occasional griefing. The proactive solution is kinda cumbersome at the moment -- have 'public' layers on top, with 'private' layers below that have to be granted permission individually. 

I much prefer the 'reactive' solution, where I just grab the last untouched frame from the recording and paste it back into the current session. The problem with this is that after a certain size, recordings just become unusable. It'd take either 30 minutes of fast-forwarding to get to the end, or around six hours to generate an index. 

It'd be cool if there was a setting to have the server automatically split recordings after a certain size, but in the mean time, is there an easy way to split an existing recording? Can you convert a text-ified recording back into dprec format? Here's my server's recording directory if you want some gigantic test files to mess around with (I'm sure drawpile.net has plenty of its own): [http://draw.caturday.party](http://draw.caturday.party/)

**Comment by callaa** [comment]
A recording must start from a known state, so splitting one is not so simple. The index generator does it by running the entire session and occasionally saving a snapshot. A dedicated recording splitter would not run any faster. (Well, actually it could run a bit faster since it wouldn't need to snapshot as often.)

Index generation is much faster in version 1.0.1, since it snapshots less often. (Although, even then it's probably too slow if the session is 50 megabytes)

However, this feature could be implemented in the server fairly simply. Right now, the server makes a single recording per session, but if instead it would start a new recording every time it snapshots (since the snapshot's purpose is to be a fresh starting point), using a reasonable session size limit would mean the server generates split recordings automatically without any extra overhead.

On a side note, in the protocol update I'm working on for version 2.0, session snapshotting (which is controlled by the server) will be replaced by explicit session resetting. This should make it possible to build in anti-griefing tools to do this without needing to use a recording.

**Comment by callaa** [comment]
Server generated split recordings are now implemented. They are with the `--split-recording` command line option.

Do you use the Windows or Linux version of the server? If you're using the Windows version, I can make a new build for testing.

**Comment by akunim** [comment]
Ah, cool! 
I run it on Linux, so I'll just pull the changes and try it out right away!
