### ISSUE TITLE
Painting with transparency over other transparencies

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#247]
http://a.pomf.cat/xoaggq.dprec
Strange solarizing effect when painting with very transparent brush over other transparencies.
One way to avoid this is draw over in a layer above.

**Comment by callaa** [comment]
I think what's happening here is rounding errors accumulating. Drawpile uses 8 bit color channels, so when the colors are very similar, there just isn't enough precision to blend them correctly. I've been thinking about switching to 16 bit color channels (like Mypaint), but that's for version 2.0 or later.

**Comment by Wade821** [comment]
Mostly fixed with Drawpile 2.0 as far as I'm aware, so I'm closing this issue. If not, comment so it can be reopened.
https://drawpile.net/news/release-2.0.0/

_**As a side note**_, if you do have Discord, you can post suggestions there by joining it and even discussing the viability of such suggestions. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join, reference this suggestion and start a conversation! So we can maybe review in more detail or close it out.
