### ISSUE TITLE
Lag Issue

### ISSUE THREAD

**Issue by Miumix** [drawpile/Drawpile#249]
First of all, Thank you for making such a wonderful software.
I've always loved paintchat. Drawpile could be a good replacement for shi-chan since Oracle made java to refuse running it. 
However when I tried drawpile out with a friend of mine, It starts lagging as we draw at the same time. I was wondering if someone else is getting this issue and If so, there's a way to fix it?

Thanks for a prompt reply

**Comment by callaa** [comment]
If the program thinks brush strokes (or other actions) from different users overlap, it wil try to reorder them in the canonical order. This can cause some heavy lag, but it shouldn't happen normally. Does this happen every time, or is there some specific sequence of actions that triggers the bug? This might be related to issue #224

One thing to try is working on different layers. If the bug is in the part of the code that detects whether two strokes overlap, working on separate layers might bypass it.

**Comment by Miumix** [comment]
The lag only happens every time during the brush strokes. 
Anyway, I'll try your suggestion about drawing on different layers and I'll let you know how it was.
Thanks * v * /

**Comment by callaa** [comment]
I just pushed a commit (e310fa7) that may fix this problem. Rather than try to replay the local changes, the program will now just throw away the local fork when a conflict is detected, thus avoiding the CPU hogging replay loop. This change will be included in the next version.

**Comment by Miumix** [comment]
Nice!
I can't wait for the next update to test it out~ Thanks for letting me know

**Comment by callaa** [comment]
Forgot to reply: the new version is now out. If the bug still exists, please comment and I'll reopen the issue.

**Comment by callaa** [comment]
One thing I just thought of that could be worth a try: do you have the Navigator dock open when the lag happens? If so, try closing it to see if it has any effect. Having the navigator open can have a great effect on performance since it forces the whole canvas to refresh on every change.

**Comment by Miumix** [comment]
Nope. I never used it before.

**Comment by Miumix** [comment]
Fixed after version 2.0.0 release.
Thanks a lot * v * /
