### ISSUE TITLE
Feature Request: Persistent AutoSession

### ISSUE THREAD

**Issue by KurinPawpad** [drawpile/Drawpile#267]
So I had an idea while trying to figure out how to get the dedicated server to work.  It would be very nice to be able to just join a server and, if there is no current session, just create one, rather than having to host one.  Maybe a configuration option on the server?  If there are zero sessions, and a user attempts to join the server, and the server is set to single-session, persistent, drop them in a new default session (perhaps configurable defaults, like dimensions, # of layers, layer names, etc) so you can quickly start it up without having to organize beforehand.

**Comment by callaa** [comment]
That's a good idea. Probably something for the 2.0 branch, though.

A user can join a session in three ways: by selecting it from a list presented by the server, by trying to join a preselected ID (e.g. via a hyperlink) or (in the case of single session servers) automatically joining the only available session.

An automatic session could be made available in two ways: either as a prelisted session (like a hibernated session) or one that is created on-demand (i.e. when a user connects to a single-session server or tries to join a specific session that doesn't exist yet.) Both approaches could be supported.

The actual initialization of the session could again be implemented in two ways: by loading it from a file (essentially a hibernated session that isn't consumed when loaded) or by executing a script that generates the session. The latter approach would be more versatile, since it would make it possible to customize the newly generated session based on the ID, the initial user or some external information.

**Comment by KurinPawpad** [comment]
That sounds great!  Definitely looking forward to that in 2.x!
