### ISSUE TITLE
Make OnionSkin layers parameters available outside preferences panel

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#269]
When working with animations, it'd be nicer and faster to have the onioskin number of layers shown available easily as a shortcut or in their own toolbar. Optionally colorize and background layer toogles would be useful as well.
###### Example:

```
CTRL+SHIFT+Z+Left Arrow Increase onion skin layers show before.
CTRL+SHIFT+Z+Right Arrow Decrease onion skin layers shown before.
CTRL+SHIFT+X+Left Arrow Decrease onion skin layers show after.
CTRL+SHIFT+X+Right Arrow Increase onion skin layers shown after.
CTRL+SHIFT+C toogle colorize
CTRL+SHIFT+B toogle background layer
```

**Comment by blurymind** [comment]
I suggest to add a new "Animation" dock that contains controls for onion skinning:
- To enable Onion skin or solo mode, instead of normal (drop list)

When onion skin or solo mode is selected, make the following options available for control (they are greyed out on "normal" layer view mode):
- to enable onion skinning (checkbox)
- to set range/color of onion skinning

-a play button to play animation (automatically opens flipbook and plays the animation)

This way Drawpile's animation features will be less hidden from the users and will be more organized in one place.
