### ISSUE TITLE
Question/Feature Request: Console input for broadcast chat

### ISSUE THREAD

**Issue by KurinPawpad** [drawpile/Drawpile#274]
Allowing console input to send chat to all/certain sessions (for warning when the server's about to be reset, notices, etc)

Is this possible/already enabled somewhere?  I can't find anything explaining that, yet.

**Comment by callaa** [comment]
There is no chat command for this yet, but serverwide messages can be sent via the web admin interface.

**Comment by KurinPawpad** [comment]
web interface should just be --web-admin-port 9999 via command line, or web-admin-port=9999 via config, correct? if so, the 1.x branch doesn't seem to have it.

**Comment by callaa** [comment]
Yes. If you want the admin UI as well (rather than just the plain API), you also need to set the path of the web app files with `--web-admin-app`.

The admin UI was included in the server before version 1.0 even, so it should be in the stable branch. It's an optional component, though, so you need to have libmicrohttpd development package installed when building. The official Windows build doesn't include it at all at the moment.

**Comment by Wade821** [comment]
Closing this issue since it's already available and new features are being added to make server changes through a web browser as well.
