### ISSUE TITLE
Animation Timeline - to manage keyframes and timing

### ISSUE THREAD

**Issue by blurymind** [drawpile/Drawpile#275]
I propose a new tool for drawpile in the form of a new Dock/window. The animation timeline.
Here is how it works:
- The timeline window lets the user create a new data type: The animation layer. Inside the Animation layer, the user can create animation frames. Each frame can be moved by dragging on the timeline, allowing the user to adjust duration between frames. The user can also insert animation frames between animation frames. The user can assign a "drawing" to each "animation frame".

Now here is the beauty of this system. It uses drawpile's standard layers for "Drawings" .
- A "drawing"(animation timeline) is a "layer" (layers dock). It's just a variable that you can assign a layer to, in order to use as a frame. so in essense you use a single layer as a frame.
- An "Animation layer" (animation timeline) is a "layer group" (layers dock)
  https://github.com/callaa/Drawpile/issues/261
  ![layerfoldersanimation](https://cloud.githubusercontent.com/assets/6495061/9600478/ee52cf50-50a3-11e5-84ba-f66b59e870c4.JPG)

Information about timing is stored and managed in the timeline. Actual drawings are stored as layers inside groups.

Inspiration:
This is Clip Paint Studio EX - a japanese alternative to photoshop that is used by mangaka artists. They recently added animation features ported over from their other product - RETAS. It's in closed beta at the moment, but they gave me access to evaluate their software.

Basically they added a timeline, which stores all of the frames in layer folders. Each layer folder corresponds to the animation layer in the timeline editor. Each animation keyframe can be assigned to use any of the layers you have in that layer folder. You can see it here:

![timelinestoringframesinlayerfolders](https://cloud.githubusercontent.com/assets/6495061/9604988/8526e492-50c3-11e5-9416-473974aff7b5.png)

I have a "lines" layer folder where my lineart frames are stored. I also have a "color" layer folder where my color for the lines is stored.

The timeline contains meta information as to where frames are in the timeline and for how long it is held. That is really enough to create a complete animation system with layers.

Right now we can not control animation timing very well. In order to keep a drawing/pose for longer than one frame, we have to duplicate it many many times- wasting valuable resources

**Comment by blurymind** [comment]
here is a video that illustrates it better:
https://pbs.twimg.com/tweet_video/CSueTkSUcAAmTbx.mp4
 :)

It is incredibly useful

**Comment by Merleawe** [comment]
I was going to put up a topic about Folders as well; for animation and otherwise, but this post covers some of it already.

A timeline would be helpful; but folders would be GREATLY. GREATLY. Appreciated. I can't animate during a group drawpile without overwhelming the group members with frames. And not only would it be helpful to have folders for animation frames; but also for the other drawpile room members to put their own layers.

Both a timeline and folders are a much needed feature. And very appreciated ones.

**Comment by blurymind** [comment]
Krita devs now have added animation and multiple frames can be stored on a single layer.
It is however somewhat behind drawpile - as we have ability to erase by color and colorize with a single command and they dont :P

**Comment by TeheeFB** [comment]
This feature will be great, since drawpile simple animation support is already good enough for simple animations it'll be great to have timing support as well with a timeline to being able to manage timing more easily, folders would work basically as a layer and the layers inside the folder would work as cells or frames, with that animation on drawpile will be really pretty much complete. I know this feature was submitted in 2015 but honestly i think with the support for animation it has now it'll be an quick way to just finish the animation support for drawpile.

**Comment by blurymind** [comment]
This looks awesome :)
I think following kritas well established design is a good idea. Its
already liked by the community and is battle tested for sure. Drawpile's
multiuser session combined with this will result in a truly interesting
collaboration experience. I can already see this being used for putting
together an animatic when typically a team of people collaborates and
discusses the arrangement of shots, etc. It could help with teaching
animation to students remotely.

Other exciting things like having people work together on things like
animation shorts and even sprites for games comes into mind. This would
enable much more polish and non destructive workflow than the current one,
a timeline will make it so much better for adjusting timing too.

I am very excited about drawpiles collaborative power growing like this 😁

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been implemented and will be coming with Drawpile 2.2, in the format Calle described.
