### ISSUE TITLE
Zoom towards mouse location

### ISSUE THREAD

**Issue by ryanmcnz** [drawpile/Drawpile#279]
Currently, zooming in and out centers around the area being viewed.
It would be pretty neat if we could center zoom in/out towards the mouse location on the screen, via some key combination held down.

This would be quite useful when working on a huge canvas size.

**Comment by Wade821** [comment]
Drawpile released a zoom tool with version 2.1.0 that allows you to zoom in via left mouse click or out via right click, as well as specific area by clicking and dragging a selection area. Closing this issue. If this issue is still relevant, please comment so it can be reopened.

https://drawpile.net/news/release-2.1.0/

_**As a side note**_, if you do have Discord, you can post suggestions there by joining it and even discussing the viability of such suggestions. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join, reference this suggestion and start a conversation! So we can maybe review in more detail or close it out.
