### ISSUE TITLE
Tablet End pressure

### ISSUE THREAD

**Issue by piearty** [drawpile/Drawpile#296]
This is kind of hard to explain. Basically when I draw with the tablet, at the end of the line there will be a big fat dot the size of the actual brush outline. I turned on bug workaround and tried different settings but it remains.
![capture](https://cloud.githubusercontent.com/assets/17207322/13020288/879d1218-d1a2-11e5-8ef9-fbba7aed66f3.PNG)

**Comment by callaa** [comment]
I remember an older bug that caused full pressure dabs to appear at the end of each stroke, but in that case it was just a single dab, while this looks like a fairly smooth ramp to full pressure. What does your pressure curve look like? It almost looks like its inverted.

**Comment by piearty** [comment]
It does it regardless of what the pressure curve is like. I've messed with the pressure curve a lot (and it's on stylus), keeping it linear, making it concave, complex, even a wave, but though it affects the strokes before the end, the dot still remains.

**Comment by piearty** [comment]
![drawpile](https://cloud.githubusercontent.com/assets/17207322/13969358/b82dc33a-f058-11e5-8a53-cfc90a2c45ae.PNG)
i reinstalled it and even with a new tablet it does the thing

**Comment by shadowcopalypse** [comment]
older copies of the program maybe ?

**Comment by Pugnippets** [comment]
Anything happening with this? I have the same thing and I can't place it.

http://i.imgur.com/eHQqvRW.png

It's quite common with these light, fast lines because the pen is skimming along the surface, so it seems to be activating a double click, despite having every double click function as disabled as it can be.

**Comment by MaximumDongers** [comment]
Is this going to be solved anytime? I just started having this issue with the new update, it was not like this with 1.0.6 and now it's doing it. It's not my tablet either as I'm not having this issue in any of my other drawing programs, I messed with all the pen settings and it still does not help, I do not know what to do.

**Comment by callaa** [comment]
It will get solved as soon as I know how, or when someone else volunteers their time to fix it.

**Comment by badmasteryoujerk** [comment]
Ive been having the same issue for the longest time and I thought it was my tablet (I even bought a new one to try and fix it)

Turns out, what you have to do is go to Edit, Preferences and deselect "Enable Bug Workarounds"
![adhadhdfgdag](https://user-images.githubusercontent.com/34011773/33244671-26fca276-d2c1-11e7-8d18-6a8728cca38d.JPG)

This is my pen before and after deselection
![image](https://user-images.githubusercontent.com/34011773/33244685-626a06a0-d2c1-11e7-89d3-855ba6e3983d.png)
before
![image](https://user-images.githubusercontent.com/34011773/33244694-9a80cf4c-d2c1-11e7-8fbd-53f50f0d483b.png)
after

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
