### ISSUE TITLE
Linux Distro Incompatible 

### ISSUE THREAD

**Issue by shadowcopalypse** [drawpile/Drawpile#299]
Current Linux release is 0.9.8

When attempting to join  a server it doesn't permit due to difference in edition. 

Backwards compatibility bug?

**Comment by callaa** [comment]
Most people are probably using version 1.0.2, which is incompatible with version 0.9.8. All 1.x series versions are compatible with each other but most pre 1.0 versions are only compatible with the exact same version.

Out of curiosity, which distro are you using?

**Comment by shadowcopalypse** [comment]
Linux Mint 17.2 Cinnamon 'Rafaela'

**Comment by shadowcopalypse** [comment]
to re-iterate , am having issues getting 1.0.2 for linux
have had no success building from srouce 
getDeb link is broken, am running wine copy windows edition.

is there a link I'm not seeing? 
17.3 cinnamon

**Comment by callaa** [comment]
What sort of error are you seeing when trying to build from source? I noticed the current version breaks on Ubuntu 14 LTS, which Mint 17.2 is based on. I'll try to fix that for the next release (soon, I hope).

**Comment by shadowcopalypse** [comment]
KF5 Archive mostly 

cmake .. -DCMAKE_PREFIX_PATH=~/Qt/5.6/gcc_64                
-- No build type selected, default to Release
-- Use -DCMAKE_BUILD_TYPE=debug to enable debugging
-- Build type: Release
CMake Warning at src/shared/CMakeLists.txt:2 (find_package):
  Could not find a package configuration file provided by "KF5Archive" with
  any of the following names:

    **KF5ArchiveConfig.cmake
    kf5archive-config.cmake**

CMake Warning at src/client/CMakeLists.txt:202 (message):
 ** QtColorWidgets not found: using bundled copy!**

CMake Warning at src/server/CMakeLists.txt:43 (message):
  **Libmicrohttpd not found: web-admin not enabled**

**Comment by Wahffle** [comment]
The issue has been fixed on the most recent stable version: https://github.com/callaa/Drawpile/tree/stable-1.x

Also, you don't need to specify "-DCMAKE_PREFIX_PATH=~/Qt/5.6/gcc_64" unless you weren't able to install Qt as a system library (just install the depencies bellow) 

Click on "Download ZIP" at the top right side and extract the content to your home folder.

Check if you have all the depencies for ubuntu 14.04 installed (https://github.com/callaa/Drawpile/wiki/Building-from-sources):
**sudo apt-get install qtbase5-dev qtmultimedia5-dev libqt5svg5-dev libminiupnpc-dev libgif-dev cmake**

You don't have to install Karchieve or other depencies since most of them come with a bundled version.

**cd "/path/to/drawpile"  ex: cd /home/"username"/Drawpile-stable-1.x/
mkdir build && cd build
cmake ..
sudo make**

And you're done, now just go to the bin folder inside the build folder and you'll be able to run drawpile from there.
