### ISSUE TITLE
Turn on sound notifications? 

### ISSUE THREAD

**Issue by blvk** [drawpile/Drawpile#311]
I noticed that the package for 1.0.2 has sounds and themes but I can't figure out for the life of me how to turn the sounds on or change the theme? I'm no dev and I tried to read help files but not a clue how to get it to work... please help! 

Edit: I just found a bug within the program...I don't know how it happened but during a collab session, one of the layers went a little crazy and wouldn't let the user erase or draw on it. The erased object would pop back up where it was and a drawn line would disappear. I tried to delete the layer and it came back as well.

**Comment by callaa** [comment]
The sounds should be active by default. They can be enabled/disabled from the preferences dialog. (It's also possible that the current windows package is missing some DLL needed for playback.)

The icon theme is a set of SVG files in the theme folders that follow the [freedesktop icon naming specification](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html). You can change the icons by replacing the files with your own. There are two variants for dark and light color themes. The variant is selected automatically based on the color of the window background.

I've received reports about similar bugs, and they all probably share the same root cause. I haven't figured out the cause yet, though.

**Comment by blvk** [comment]
> The sounds should be active by default. They can be enabled/disabled from the preferences dialog. (It's also possible that the current windows package is missing some DLL needed for playback.)

It must be the latter because all the notification options are ticked and the volume is at 100%....I even went and tried an archived version of the program and still nothing. Is there a way to confirm that this is the issue or easily solve it on my end?

**Comment by ClockworkWolf** [comment]
I'm not sure if this is part of the same issue, but myself and another user are experiencing the same audio issue. He's on Windows 7 and I just switched from Debian to Antergos. Neither of us receive audio notifications and Drawpile is not listed in our mixers. I'm also running it through the appimage (both 1.05 and 1.06). Is there any known fix for these?
