### ISSUE TITLE
Issues with launching

### ISSUE THREAD

**Issue by Mightyswave** [drawpile/Drawpile#312]
Hello, I recently downloaded Drawpile, and had a lot of fun with it.  However, since then it hangs up on launch.  I go into the task manager and see that it's hogging roughly 22% of my CPU and does nothing even after half an hour of waiting.  I've uninstalled and reinstalled twice thus far, and the same issue still comes up.  It's strange because the very first time I launched it, it worked flawlessly.  It's only on subsequent launches that it's been giving me trouble.

**Comment by callaa** [comment]
Most likely corrupted data has been saved in the registry, since that is the only thing that persists between reinstalls that I can think of. Can you export Drawpile's registry entries (should be in `HKEY_CURRENT_USER\Software\Drawpile`), then delete the entries? If this fixes the problem, you can send me the reg file and I'll try to see if I can find whatever is causing the problem.
