### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by shadowcopalypse** [drawpile/Drawpile#338]
# Disable Fill tool for online servers. Someone always goes splat!

Pop out chatroom 

.appimage for linux

Join server without having to go through whole index. That can take forever

Tab to disable interface

Internal video editor for Rotoscoping. 

Some type of onion skinning. Changing opacity on layers by hand gets messy.  

Vector tools

Allow people to group vote someone out of a server. 
Also need notice of who cuts layers out and who pastes on them

Set interval for clearing of canvas. Or a group vote as well.

**Comment by probonopd** [comment]
Can you get it to build on CentOS 6? [Here](http://files.svenbrauch.de/kdevelop-linux/kdevelop-recipe-centos6.sh) is a build script that builds a complex KF5-based application on CentOS 6 and packages it as an AppImage. Using an old distribution like CentOS 6 has the advantage that the resulting binaries will run not only on recent but also on older target systems.

**Comment by callaa** [comment]
> Disable fill tool

Probably for version 2.0, since this requires protocol changes. A general ability allow only specific tools might be a nice feature.

> Pop out chatroom

Do you mean a detachable window, like the docks?

> Join server without having to go through whole index.

This is sadly not possible with the current architecture. The login time can be shortened a little by setting a session size limit or manually forcing a snapshot.

> Tab to disable interface

Do you mean like in GIMP, where hitting tab hides all the tools and other windows, leaving just the canvas?

> Internal video editor for Rotoscoping.

Probably out of scope for this project.

> Some type of onion skinning.

Already exists. Check out the Mode submenu in the layer settings popup menu.

> Vector tools

Perhaps for version 3.0

> Allow people to group vote someone out of a server. 

This needs further planning, and warrants an issue of its own.

> Also need notice of who cuts layers out and who pastes on them

This sounds very useful, I'll add it to the TODO list.

> Set interval for clearing of canvas. Or a group vote as well.

In the server settings. an interval can be set for snapshotting the canvas (i.e. drawing history is cleared and replaced by a snapshot of the current image.) Snapshotting can also be triggered manually using the `/force_snapshot` operator command. In the current 2.0 development version, snapshotting has been replaced by explicit resetting, which is much more versatile, as it allows the session to be restored to a blank initial state (for example.)

**Comment by callaa** [comment]
Regarding Appimage, I'd certainly like to provide prebuilt appimages, at least until Flatpak KDE frameworks become ready to use. I like how appimages are so easy to use (for the end-user), but the build process looks really complicated.

**Comment by blurymind** [comment]
The fill tool limitation could be imposed on specific layers - that way you
can also force people in the chat room to treat a layer as a linework layer
that is not to be used for fills.

**Comment by probonopd** [comment]
@callaa work is underway to make the AppImage build process easier, but essentially how you build your app is your business; AppImage is simply a format that holds your binaries (an ISO, essentially).
Let me know which aspects you find most complicated and I'm happy to help.

You can put anything into an AppImage. But for it to be compatible with as many target systems as possible, I recommend to build on a not-too-recent ("enterprise stable") distribution such as CentOS 6.

**Comment by callaa** [comment]
I managed to get the AppImage build script working. I made two scripts based on the ones at the recipe repository: one that prepares a docker container with all the build tools and dependencies, and one that actually builds Drawpile (the client, will add a build script for the server later) and spits out the finished appimage. It seems to work on Ubuntu 14.04, Fedora 23 and Archlinux. It starts up on Ubuntu 12.04 too, but the window decorations are missing for some reason. Also, it doesn't follow the system widget theme, but that's probably a normal side effect of using the bundled Qt version.
I will provide an appimage for the next release.

**Comment by probonopd** [comment]
@callaa can you share the script you use for building the AppImage? Thanks

**Comment by callaa** [comment]
@probonopd the scripts are in the [appimage directory](https://github.com/callaa/Drawpile/tree/stable-1.x/appimage).

**Comment by shadowcopalypse** [comment]
@callaa by popout chatroom I meant exactly like how when people log on or off
A box at top right screen that shows what's written and then dissapears after a few seconds

The tab thing is not that good an idea. It happens in full screen already anyway.

**Comment by probonopd** [comment]
Thanks @callaa for the AppImage!

**Comment by Rockmanan** [comment]
Just started using Drawpile & love it! Been trying to spread the word to all my friends. 
However, I just had a long drawing session ruined by vandalism, and could find no way to revert the changes or report/block the offending user. While trying to find a Moderator to report the issue to, I found the same user jumping to other boards to ruin multiple public sessions.

If there are existing tools for users to deal with vandalization, I suggest making those features' existence & how to use them more visible if already available on the Drawpile website. if it is not, I ask the information be added somewhere clear & easy to find (possibly within the  Help or Troubleshooting section)

 If there are no tools for users, I suggest including a way to report/block a user's IP (or something else that is more permanent than username), and a way to undo a vandal's changes (at least as a board moderator). 

Thank you!

**Comment by blurymind** [comment]
It's worth noting that drawpile has a command to erase by specific color! This feature was added for animation/cleanup sketch purposes, but it can also help with clearing the canvas from bucket tool spills.

1.Pick the color you want erases with the color picker
2. Lasso select the area where it is spilled (or do select all for the entire canvas)
3. Erase by color

**Comment by Rockmanan** [comment]
Unfortunately, our vandal went to the effort to not only fill the canvas, but also used the brush tool to completely cover our work, so erasing their color couldn't salvage our drawings. 
Thank you for the information though! That feature definitely sounds useful in other situations!

**Comment by callaa** [comment]
I just uploaded a help page on Drawpile's session moderation features: https://drawpile.net/help/mod-tips/

So sorry to hear about what happened to your session. Hopefully I can get the 2.0 final version ready soon, since it has a new reset/rollback feature that can be used to recover the session in most cases.

**Comment by blurymind** [comment]
Would be useful if the moderator could execute a global undo that undoes
steps of all the users in the session

**Comment by shadowcopalypse** [comment]
A few more suggestions conjured up. 

Default canvas colour -- make changeable or set to mid-tone 

Pixel art at different sizes. Like bigger boxes that always snap. A brush ideally.
^ That one could be popular with trolls though. 

Instead of names of others being visible when drawing, allow custom avatars.

Textbox rotation enable (alt + rmB) 
Proportional scaling

Pictionary Bot like on iSketch.net

**Comment by Wade821** [comment]
We really should have separate issues for separate suggests @shadowcopalypse ... bundling them together makes it hard to keep track of all the ideas being posted and making sure nothing is missed in the commentary. As such, I'm going to close this issue. 

**Pop out chatroom** --> https://drawpile.net/news/release-2.1.11/

**.appimage for linux** --> #697

**Join server without having to go through whole index. That can take forever** --> https://drawpile.net/news/release-2.1.9/
Full implementation of the Thick Server will help alleviate that once it goes mainstream. But you can't get rid of having that index load when you first join a session because you'd change a very fundamental part of the way Drawpile works. 

**Tab to disable interface** --> https://drawpile.net/news/release-2.1.5/

**Internal video editor for Rotoscoping.** As Callaa said, it is out of scope for this project. That's a huge addition to Drawpile and so I don't think that will go anywhere.

**Some type of onion skinning. Changing opacity on layers by hand gets messy.** --> https://drawpile.net/news/release-0.9.10/ already exists

**Vector tools** As Callaa said, perhaps for version 3.0. Should have its own issue.

**Allow people to group vote someone out of a server.** As Callaa said, this needs further planning, and warrants an issue of its own.

**Also need notice of who cuts layers out and who pastes on them** TODO List for Callaa... ? 

**Set interval for clearing of canvas. Or a group vote as well.** Callaa already answered this as well. 

> In the server settings. an interval can be set for snapshotting the canvas (i.e. drawing history is cleared and replaced by a snapshot of the current image.) Snapshotting can also be triggered manually using the /force_snapshot operator command. In the current 2.0 development version, snapshotting has been replaced by explicit resetting, which is much more versatile, as it allows the session to be restored to a blank initial state (for example.)

**Pixel art at different sizes. Like bigger boxes that always snap. A brush ideally.  (That one could be popular with trolls though.)** Should be a separate issue, also I'd need some elaboration on exactly what you mean by this... examples in other art programs, drawing mock ups, something!

**Instead of names of others being visible when drawing, allow custom avatars.** 
https://drawpile.net/news/release-2.1.0/

**Textbox rotation enable (alt + rmB)** Should be a separate issue.

**Pictionary Bot like on iSketch.net** Should be a separate issue.
