### ISSUE TITLE
Accidental Layer Deletions

### ISSUE THREAD

**Issue by doornob** [drawpile/Drawpile#369]
Is there anyway that certain keyboard commands can be disabled? There's a problem in the roleplay rooms where someone will hit CTRL+X and wipe an entire layer clear and we don't always know who's doing it accident or not.

**Comment by shadowcopalypse** [comment]
The simple solution to this would probably be to not put the cut hotkey right next to the undo hotkey. 

Put it far away somewhere...like Alaska.

**Comment by callaa** [comment]
Sorry for the late response!
You can use the "lock cut, paste & fill" command to block dangerous operations. Although I understand this is too heavy handed in some cases.
One simple solution I just thought of would be to limit the Cut operation to selected areas. (How often one needs to cut the entire layer anyway?) This way, accidentally hitting ctrl+x is usually harmless, since you need to have an active selection for it to do anything.

In the current stable branch (and soon 1.0.6 version) the user cursor is shown of all cut, fill and paste operations (the cursor is placed in the center of the filled area.)
