### ISSUE TITLE
CPU spike and lag?

### ISSUE THREAD

**Issue by TriangleArt** [drawpile/Drawpile#390]
Hello there!
Computer specs:

iMac (Retina 5K, 27-inch, Late 2015)
Processor 4 GHz Intel Core i7
Memory 32 GB 1867 MHz DDR3
Graphics AMD Radeon R9 M395X 4096 MB

I've been using Drawpile for quite some time now and I noticed lately that every time when I try to draw with friends on a 2000x2000 canvas with three or four other people, every time they are drawing my line quality instantly lags and I'm unable to draw until they stop.

I checked my CPU usage and when I'm drawing normally it's at 32% but when others draw and I'm not even drawing it instantly shoots up to 100+%. 

This is a pretty high end running computer I have no idea why it lags THIS badly unless it's a program thing. It just sort of happened randomly one day.

Any help?

Thanks!

-J

**Comment by callaa** [comment]
My first guess would have been that the program is incorrectly detecting inconsistencies between the local input and the network input and is constantly rolling back the canvas to fix it. However, this should only happen while you're drawing at the same time as other users.

Does the CPU spike continuously while others are drawing, or does it only happen while/after you've drawn something?

Here's some things you can try that might help diagnose the problem:

* When the problem starts, try starting a session recording. When you play back the recording, does the CPU spikes happen also?
* If possible, try if the bug occurs in the 2.0 beta as well.

**Comment by TriangleArt** [comment]
HI there!

You are correct in saying that when other people are drawing that my lag grows exponentially, it's also when the canvas exceeds a certain size 2000x2000 is when it gets worse off.

We did some tests and upgraded to 2.0 but there didn't seem to be a change in the lag.

I tried to recording and playing it back and it does the same spike in CPU usage to about 133% It's just jarring that all of sudden the program doesn't seem to work. Would you possibly have any other solutions?

Thanks!

-J

**Comment by callaa** [comment]
If the recording reproduces the problem, can you send me a copy? I might be able to figure out what's causing it.

**Comment by TriangleArt** [comment]
Sure thing! I hope this works I'm not sure if you had to export it or anything:

http://sta.sh/019qvlqixot

Thanks!

-J

**Comment by callaa** [comment]
Thanks. I tried the recording on my Linux desktop and Macbook Pro (2013 model, 8GB RAM with Intel GPU) and was not able to reproduce the problem. On the macbook, the CPU did spike to over 100% when there were multiple simultaneous drawing operations going on, but the program remained responsive during the whole time. I also analysed the recording file itself and didn't find any commands that  could cause excessive CPU use (e.g. heavy undo operations.)

One thing that I just though of is that the beta version writes a log file. On Macs, it can be found in ~/Library/Application Support/drawpile/drawpile/

Check if there are any messages in yesterday's log file that might indicate problems. If you see lots of lines about inconsistencies and rollbacks, that would mean the problem is in the retcon module. I'm not sure if those messages are printed in non-debug builds, but I can upload a debug version if needed.

**Comment by Wade821** [comment]
Are you still having a problem with this @TriangleArt? If so, can you get the recording log @callaa asked for?

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Comment by notfood** [comment]
The new adaptive autoreset threshold should fix your issue though. Stale issue, closing.
