### ISSUE TITLE
Session constantly being announced

### ISSUE THREAD

**Issue by Lyncesca** [drawpile/Drawpile#391]
http://puu.sh/tw0wN/03b30a302b.png

but the thing is this is a private session, it shouldn't be being announced in the first place.

addendum: i'm hosting a dedicated server off my machine. the cmd box says messagequeue timeout whenever the message appears in chat

**Comment by Lyncesca** [comment]
addendum: i'm hosting a dedicated server off my machine. the cmd box says messagequeue timeout whenever the message appears in chat

**Comment by callaa** [comment]
Are there multiple sessions hosted on your server? If so, I think I found the problem. The bit of code that prints the "session announced" message is found in `src/shared/server/sessionserver.cpp`. It prints that message to *every* active session instead of just the one it was intended for. (I have no idea what I was thinking when I added that.)

So, the private session is not actually being announced (you can check if it appears on drawpile.net's listing,) but some other sessions on the same server are. In version 2.0, I've rewritten the session announcement code and already fixed this bug as a byproduct of that. (Although I seem to have forgotten the announcement notification message altogether.)

I'll fix this in the 1.x branch as well if I make another release before 2.0.0. If you're using a self-built server, you can just remove lines 54-56 from sessionserver.cpp to silence the message.
