### ISSUE TITLE
Cannot connect to servers because their full

### ISSUE THREAD

**Issue by LadyLilligant** [drawpile/Drawpile#399]
i cant create a serve becuase their all full?

**Comment by callaa** [comment]
Are you trying to host on the public server? What sort of error message do you see?

**Comment by LadyLilligant** [comment]
Yesterday I was trying onba public server, it said could not connect
servers then I tried a privite one and it worked but today I try the
private one and it doesn't work

**Comment by callaa** [comment]
If the public server says "server is full", that usually indeed means the server is full. At the moment, it is configured to allow only 15 simultaneous sessions. I've tried increasing the limit in the past, but the server started running out of memory. Things will get better once I switch over to 2.0, since the new one should be more memory efficient.

There are many private servers and many reasons they might not work, so I can't say what was the problem based on that description alone.
