### ISSUE TITLE
Freeform Selection Tool (Drawpile 2.0 RC)

### ISSUE THREAD

**Issue by mysterypaint** [drawpile/Drawpile#410]
Selecting a region and moving it around will reset if the artist tries to select a new region or switch tools. This bug doesn't seem to happen with the rectangular selection tool.

**Comment by callaa** [comment]
Yes, the behaviour does seem to be inconsistent. The least surprising thing to do would be to always treat the loss of current selection as a commit action. (Except when the selection is explicitly cancelled with ctrl+z)

**Comment by callaa** [comment]
Ok, these are now fixed. Lasso select tool bug was introduced in the previous release when added the new MoveRegion command. When I fixed a rounding error for rectangular selections, I didn't remember to test it with the lasso tool as well.

Switching to another tool now commits floating selection instead of cancelling it.
