### ISSUE TITLE
Hide Layer Sounds do not play

### ISSUE THREAD

**Issue by HolocaustoDevil** [drawpile/Drawpile#411]
Well i just noticed there are some nice feedback sounds when you click the hide checkbox in the layer menu n.n

But if you toggle some 4 times for example the sounds (to hide and show) don't reproduce all the time.

**Comment by callaa** [comment]
The notification sounds have a rate limit so that a sound will play only once every 1.5 seconds. The purpose of the limit is to prevent a cacophony of notifications when joining. However, now that there is a login progress dialog shown during the catchup phase, the notification sounds could simply be disabled during this period.

**Comment by notfood** [comment]
There is no hide layer sounds anymore...
