### ISSUE TITLE
Lasso Freeform Issue & Color Swap

### ISSUE THREAD

**Issue by blvk** [drawpile/Drawpile#415]
When making a selection with the lasso and making a selection transformation- i.e. resizing or rotating it- clicking out of the marquee boundary just makes the selection pop back to its original state....yet the rectangle selection tool will make transformation changes without this issue? Is this a bug or am I missing something? Also noticed that "X" to switch between two colors doesn't work anymore which is a feature I used all the time...

**Comment by callaa** [comment]
Yup, the lasso selection snapping back is a bug. I've fixed it already in the master branch, so it will be fixed in the 2.0.0 release.

The X color swap is a separate issue. Version 2.0 no longer has a concept of a background color (it has been a vestigial feature in 1.x series ever since layers were added,) but the quick color swap feature can be reimplemented in some other form in the near future. (I'm planning on adding many of the missing features in 2.0.1)

**Comment by blvk** [comment]
That would be awesome! Great job on the new release!
