### ISSUE TITLE
record and play algorithm

### ISSUE THREAD

**Issue by kamranrad1993** [drawpile/Drawpile#417]
hi

can someone explain to me how record and play work and how it seek in time? 
I want to know its algorithm.

sorry for my English. 
thanks

**Comment by callaa** [comment]
Check out the [How Drawpile works](https://github.com/drawpile/Drawpile/wiki/How-Drawpile-works) page for an overview of how Drawpile works in general.

Recording just saves the received messages to a file. During playback, the messages are read from the file, instead of from the network.

Jumping to specific times works with the help of an index file. The index contains snapshots of the canvas at regular intervals. When jumping to a specific position, the snapshot closest to the position is loaded from the index, then the remaining messages are executed.

You will find the relevant code [here](https://github.com/drawpile/Drawpile/tree/master/src/client/recording).

Does this answer your question?

**Comment by kamranrad1993** [comment]
thanks so much

yes, your answer is so helpful.

can you tell me about saved data in snapshots?
and is canvas draw from began when seeking to a time?

**Comment by callaa** [comment]
The index file is a zip file that contains the following:

 * Array of stop offsets (positions in the recording file where new strokes begin)
 * Canvas snapshots
 * Canvas thumbnails (used in the filmstrip widget)

The snapshot are [StateSavepoints](https://github.com/drawpile/Drawpile/blob/master/src/client/canvas/statetracker.h). They contain:

 * State of each user context (active brush settings, etc.)
 * Layers (pixel data and attributes)
 * Annotations

In short, a snapshot of the entire canvas state. (Currently, undo history is not saved, so undos will not work properly after jumping in the recording.) I'm using QDataStream to save the snapshots, since it's convenient. The actual format is not documented anywhere, since it's just a cache that can always be regenerated and thus doesn't need any backward/forward compatibility.

The snapshots make it possible to not redraw the canvas from the beginning when seeking. When seeking to time *t*, the snapshot *S* closest to *t*, such that *t<sub>S</sub><t* is loaded from the index. Then all messages in range *(t<sub>S</sub>, t]* are executed. (The position the message at *t<sub>S</sub>* is found in the offset index file, since all snapshots are made at stop offsets.)

Without the snapshots, seeking backwards would mean the canvas would have to be reset to a blank state, then all messages in range *[0,t]* executed. This would be extremely slow for long recordings. With snapshots, there is a fixed upper limit on how much CPU time a seek will take. (It's a balance between short seek times and disk space: if snapshots are made too often, the index file becomes huge.)

**Comment by kamranrad1993** [comment]
thanks so much
there is no better answer!
