### ISSUE TITLE
Disable history loading/playback

### ISSUE THREAD

**Issue by jameslis** [drawpile/Drawpile#419]
I'm not sure if this is changed in 2.0 but is there a way to disable playback and grab only the current state of the canvas when a user connects? 

We host long running sessions where we aim to fill a large canvas so lots of messages are generated over time. Every time a new user connects it will play them all back taking the canvas longer to load. We don't need to see previous versions of the board unless there is an issue with a troll; which is not likely since all users are trusted and there are no public/open sessions.

The only workaround we have is to save and reload the session (wipes the messages, keeps the canvas) but is there a config option or something I can change to control this behavior? Note we are still on stable-1.x but if version 2 offers a fix we may just migrate sooner than later.

**Comment by callaa** [comment]
The way Drawpile works, it's impossible to get just the current state. The 1.x versions support session snapshotting, which periodically replaces the history with a snapshot of the current state. This is triggered automatically when the max history size is reached, or manually with the `/force_snapshot` chat command.

In version 2.0, snapshotting has been replaced by session resetting. The difference between the two is that snapshot happens invisibly and replaces just the serverside history, while resetting resets the session for everyone. (The snapshot feature causes a few difficult to fix bugs, as well as some architectural limitations, which is why I changed it in 2.0)

So, if you're currently manually resetting the session, I think you will like 2.0, since it offers an easy to use tool to do that automatically. As a bonus, it can be used as a super-powered undo to revert the session to an earlier state in case of vandalism.

**Comment by jameslis** [comment]
I remember testing this out briefly in RC1, the archiving system worked well and I did notice snappier loading for larger canvas. We haven't tried the reset function yet but it is a useful feature so we don't need to reload the canvas when it gets full.

However in 2.0 release we also experienced bug #422 so I'm glad to see it resolved. Will try out the next version. Thank you.
