### ISSUE TITLE
Pasted image bigger than sessionSizeLimit crash

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#430]
Server enters into infinite loop trying to flatten history after any user pastes an image that is bigger than the sessionSizeLimit variable, eventually it runs out of memory and crashes.

I noticed the issue when the server would crash after setting the sessionSizeLimit to 5mb.

Always reproducible.

Forbiding pasting images above sessionSizeLimit would be desirable though there needs to be some buffer so it doesn't go into the loop of flattening the history after pasting the image a little below the sessionSizeLimit then drawing a few more lines.

Idealy we could use a max paste size variable.

**Comment by callaa** [comment]
Normally, the client will take the server's available space in account when sending the reset: if it's not enough, the client will not autoreset and the user has to manually revert it to an earlier state.

However, when someone is uploading a huge image, the upload may not be finished when the operator starts the reset. The remaining parts of the image will then be added to the history after the reset, sending it over the limit again. So, the loop is not infinite but can still clearly be big enough to effectively be a DOS attack. I couldn't get the server to crash, though.

There are two problems:

 * That the server can be DOSed by uploading large images. Currently, this is exacerbated by the fact that while in reset mode, all new messages go to a holding buffer and are then added to the session when the reset completes. I think this is what leads to the infinite loop like behavior. I should change this so that if the session history is full, incoming messages are just dropped instead of queued. (IIRC, in Drawpile 1.0, the initial snapshot didn't count towards the history size, so someone could upload a huge image, which would result in... something. A broken session probably.)

* That it's possible to accidentally upload an image larger than will fit in session history. As you suggest, a maximum size limit for pasted images is a good approach here.
