### ISSUE TITLE
some feature improvement suggestions

### ISSUE THREAD

**Issue by calmnivore** [drawpile/Drawpile#431]
Streamline deletion/adding/merging of layers. ability to perma banish the "are you sure" popup. Delete, new layer, and merge need to be separate buttons, merge option as part of deletion popup is very clunky. see image:  http://puu.sh/uTRPh/4af793666f.jpg

Improve the erasing algorithm. would prefer uniform alpha channel opacity lowering rather than the gradual from the outside in effect that it has. This would allow the user to sketch, then erase his lines on low opacity, effectively making his lines "dimmer". As it is, it requires careful work to achieve this effect whereas in Photoshop or other similar programs it's the work of a single stroke. The benefit of this is that the user doesn't have to fuss with layers while sketching in a server with others. 
http://puu.sh/uTStu/897381ebda.jpg  http://puu.sh/uTSxj/17751b0b2e.jpg

Selecting needs to have a confirm done button rather than clicking outside the selection or changing tools. Someone else asked for a lasso fill tool but really, the selection tool needs to be a true selection tool, not a snipping tool. Define a selection and wait for the user to input commands like transform, paint inside the selection, or deselect. http://puu.sh/uTS79/2d2d2b3401.jpg

A proper animation tool should use a graph with layers on the y and frames on the x. That's probably a massive task though. 

PS You've done an amazing job with this program in any case

**Comment by callaa** [comment]
> [Layer delete]

Yes, this can be done. I don't remember the original reason why the delete and merge actions are behind the same button, but it was probably to minimize the number of buttons due to limited space. However, since the delete action is now inside a popup menu, there is no longer any reason not to have them as separate items. The deletion confirmation box dates from a time before Drawpile had an undo feature, so that's indeed a bit superfluous these days too, especially if the merge action is separated from it.

> [Erasing algorithm]

I'm not sure what you mean by this. Do you mean using alphadarken blending for the indirect paint mode, like in issue #286? (I still haven't gotten that working properly, and I'm not sure why)

> [Selection tool]

Taking this under consideration for later. I will need to add support for masked painting to the paint engine for this to be done.

> [Animation tool]

I know. This needs support for multi-page (or frame, in this use case) documents. Right now, Drawpile isn't really meant to be a proper animation tool, it just can function as a very basic one.

**Comment by calmnivore** [comment]
> eraser
I really couldn't tell you. The problem you reference might very well be the culprit but I'm only speaking from precious little knowledge about how any of this actually works and I'm only really guessing at what the underlying problem is.
