### ISSUE TITLE
Full pressure at start of stroke 

### ISSUE THREAD

**Issue by ClockworkWolf** [drawpile/Drawpile#434]
A friend is having an issue where when he starts a stroke, it appears to randomly start at 100% pressure. It's a Monoprice tablet but other Wacom tablets do not appear to show the same problem. It just started with the 2.0.1 version but not on the 1.0.6.

Tried restarting both the client and the computer but it still persists.
![lines](https://cloud.githubusercontent.com/assets/17094518/24319185/04c48c04-10da-11e7-9b9a-ce0b9d6323a3.png)

**Comment by doornob** [comment]
I found this solution for krita that might work for them https://forum.kde.org/viewtopic.php?f=139&t=107138

However, I have a theory that I'd like to test out. Since it's popping up in 2.0 do you think it could be an error in the registry?
I have a friend who had upgraded to 2.0 and had this start happening so they downgraded back to 1.6 and now 1.6 is doing this to them mid stroke.

**Comment by callaa** [comment]
I discovered some changes in the 1.x branch I hadn't copied over to the 2.x branch. One of them was a workaround for bad pressure data in the tablet stylus down event, which might help with this problem. The changes are included in the 2.0.2(.1) release I just uploaded.

**Comment by callaa** [comment]
There is now a new version with experimental Windows Ink support, which should solve many tablet related problems people have had, so I'm now closing all open issues with the Tablet tag. See Issue #562 for details.
