### ISSUE TITLE
[DP 2.0.2] Strokes dissapearing and erasers not erasing.

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#438]
Annex #shgjkhskdgjh sent via mail. Probably related to issue #425

In the sent dprec, Layer 4 will not accept new strokes, be it brush or eraser. One of the people drawing also claims it's reoccurring issue.

**Comment by callaa** [comment]
I was unable to reproduce the issue with the recording, however I did find an error in the access control checking: when a layer was deleted, it's access control list was not cleared. If a new layer was then created, it could reuse the ID of the deleted layer and inherit the stale access controls. The ACL filter and the UI would then be out of sync and strokes would disappear after drawing.

A misbehaving layer can be fixed by locking & unlocking it to reset its ACL. Since I couldn't reproduce the problem with the recording, it's possible someone did this already. I'll have to analyze it a bit more closely. Another option is that that particular problem was caused by some other bug.

**Comment by notfood** [comment]
This used to happen in the 1.x series too. If you merge a layer down, then undo it. Sometimes the layer becomes unusable even for OPs/Mods and it can't even be deleted. Only a new session fixes it.

**Comment by callaa** [comment]
Version 2.0.3 is now out, which should fix this problem. If the problem appears again, please open a new issue.
