### ISSUE TITLE
Loss of Canvas

### ISSUE THREAD

**Issue by doornob** [drawpile/Drawpile#440]
![broke](https://cloud.githubusercontent.com/assets/20618081/24542749/804ca252-15c2-11e7-8c82-8dbd158ac892.png)

Had the canvas reset on us tonight and it broke the session for us. We can still use the chat but the canvas disappeared along with the navigator preview and layers. We tried relogging and it would start to load normally and then break again once it loaded.

**Comment by callaa** [comment]
I found the broken session from the server's archive. (I have to say, even though 2.0 introduced a bunch of new bugs due to the big architectural changes, those same changes make it very much easier to debug.)

This is apparently how the bug happens:
1. User X initiates a session reset (either manually or automatically due to low space)
2. Server prepares itself and sends the "go ahead" message
3. User X uploads the reset snapshot. If the reset was automatic, the user may be drawing when it happens. With bad luck, a few of the drawing commands get mixed up with the snapshot, including an UndoPoint message.
4. Reset completes. User X now undos something.
5. Due to the mixup, there is an UndoPoint that precedes the reset. The program then undos the entire reset, leaving the canvas with zero size and no layers. (In some cases, a redo might fix this.)

**Comment by doornob** [comment]
Ah! I'll try the redo solution the next time that it happens to us and get back to you if it work or not. Thank you!

**Comment by callaa** [comment]
Version 2.0.3 which fixes this problem is now released.
