### ISSUE TITLE
Multiple Sessions

### ISSUE THREAD

**Issue by rakunko** [drawpile/Drawpile#444]
Hosting a 2.0.2 server on Ubuntu 14.04 LTS and I cannot find any information about hosting multiple sessions from a single server. I have tried multiple template files - only the first one seems to read? I don't think running drawpile twice will work since its the same port. I cant find any documentation or obvious method.

**Comment by callaa** [comment]
That only the first template is read is clearly a bug. I'll fix that. Otherwise, there shouldn't be anything special you need to do to host multiple sessions. Just host a session from the client and enter your server's address to the *remote* box. By default, the server will allow 25 simultaneous sessions, but you can change that with the `sessionCountLimit` setting.

**Comment by rakunko** [comment]
Thank you!

**Comment by callaa** [comment]
The template problem turned out to be a bug on the client side. The server reports all the sessions as it should, but the client lists them wrong. The bug is now fixed in the development version.
