### ISSUE TITLE
Feature design: Censored layers

### ISSUE THREAD

**Issue by callaa** [drawpile/Drawpile#448]
Drawpile currently supports tagging an entire sessions as "not suitable for minors". However, this binary tagging is too heavy-handed in some cases. In a large group canvas, only small parts of the canvas might actually contain NSFW material. To work around this problem, a "censorship layer" is sometimes used: a hidable layer that is used to block out the NSFW parts. However, this approach has its limitations: it's easy to accidentally draw on the censorship layer itself, and one must remember to update it to cover the areas that should be hidden.

This feature proposal aims to provide a built-in alternative to censorship layers. The feature would be very simple: individual layers could be tagged as NSFM. There would be an additional option in the View menu to censor NSFM layers. When censored, all tiles containing non-transparent pixels would be replaced by completely black tiles.

![censored-layer-mockup](https://cloud.githubusercontent.com/assets/464576/25070374/c8290a4a-22a4-11e7-9ad1-786aa2f0d01b.png)

Alternative censorship styles:

 * Hide entire layer (problem: people can unknowingly draw over other people's art)
 * Replace non-transparent pixels with black pixels instead of the whole tile (problem: may not censor enough in some cases)
 * Scramble layer content (problem: computationally expensive)

Advantages of NSFM tagged layers:

 * No need to maintain a censorship layer manually.
 * UI locked when a censored layer is selected: impossible to accidentally draw on the wrong layer
 * Supports parental controls: possible to lock the application into censored mode.

Implementing this feature requires adding a *flags* attribute to `LayerAttributes` message, or creating a new message type. Either way, this is a protocol change and thus cannot be done until version 2.1.

**Comment by Le2222** [comment]
A different approach to let the overall view more elegant: NSFM tag would turn on/off the pixalate filter on the layer, like this:

![Pixelate filter](https://i.gyazo.com/bc2deaff2939092076c6828900a93614.png)

ps: the filter's tiles size can be changed to let it less recognizable, if needed.

**Comment by callaa** [comment]
That's what I was thinking with the "scramble layer content" option. The downside is that it's a more expensive operation compared to just blanking out the tile, which is effectively free. However, now that I think about it, in this use case the pixelation filter can be optimized for speed at the expense of accuracy, so it should be feasible after all.

**Comment by Le2222** [comment]
An alternative idea to think about: instead of have SFM and NSFM mixed in the canvas, it could be like they do in my beach: its divided, the surfers use the zone A while the fishermen stay on the zone B. WIth the canvas splitted in 2 (50%/50%), the NSFM option would be 'hide the right side of the canvas' instead of 'hide a layer'. So it wouldnt need black or pixel filters, a single color like white could cover all.

**Comment by notfood** [comment]
This seems unnecessary. You can easily add another layer, paint the danger area black, put a danger here image or whatever and just draw under that layer with that one hidden for you and those others that want to see your NSFW.

This new feature just adds more bloat to the toolset/screen/layers without adding any value since any kid can just tick the hide thing away. I foresee nobody using it properly or just forgetting about it most of the time.

I see no point in cramming minors with people who want to draw NSFW, they are two separate groups with different mindset that should be kept separate. Rooms with this feature will only be a moderation headache in the long run.

**Comment by callaa** [comment]
@Le2222 Specifying censored regions is actually more complicated to, even if it's just a divider. (From a programming perspective, it's not much more difficult to allow arbitrary regions instead of just two.) In contrast, whole-layer based censoring as described is trivial to implement.
However, if it's too coarse grained and people would have to use a manual censor layer anyway, then there is little point in this feature.

@notfood You're describing the way it's currently done. People are hosting mixed SFW/NSFW sessions right now and manually maintaining a censor layer. The purpose of this feature would be to simplify that use case. (Although, as I said above, that's assuming whole-layer based tagging is fine-grained enough.)

And yes, I expect any tech-savvy kid to work around any parental controls in 5 minutes, but I still think the ability to rate sessions and layers is nice to have.
