### ISSUE TITLE
Social Features (Profile + Gallery)

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#451]
As a social tool, would be interesting if the users had a profile with basic info like location, timezone, age, website, quote, etc (it could appear on mouse hover or in mIRC style /whois).

Also, the drawpile website could have a gallery where people would be able to share their drawings (or sessions) and comment on the other people's stuff. It could be a single gallery to everyone or each person could have their own gallery inside their profile (or both).

**Comment by callaa** [comment]
Issue #446 covers the user profile feature. Since it requires a protocol change, it has to wait until version 2.1. (Or does it? I'll have to think about this a little more.)

A gallery for the main site is a great idea. It could tie in to the guest user registration feature of issue #447.

**Comment by callaa** [comment]
There is now preliminary support for user accounts on the website (will be opened for public after 2.0.6 release) and version 2.0.6 will support logins those accounts. A user gallery feature is also in the works.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

As said in #446, the website link stuff is a source of grief. I think the gallery was a thing for a bit and then has been removed because it also was a source of trouble, and I'm not inclined to bring it back and deal with that kind of content moderation. Hence closing this.
