### ISSUE TITLE
dprec file format questions

### ISSUE THREAD

**Issue by rakunko** [drawpile/Drawpile#455]
Going to try to keep it short and sweet.
I am looking to build a python script to take a session (.dprec) on a server, load it into a program (drawpile/gimp maybe) take a screenshot/save visible layers as a png and save the file. I am building a discord redbot cog to make it possible to save the session outside of the program and have the server perform all the work. I know this isn't an issue but any help would be appreciated.
dataflow:
discord "/botgetdrawpilepic sessionid" > server "get sessionid, load dprec, export as png, save png" > discord "save is complete, upload png to chat"

**Comment by callaa** [comment]
Take a look at the `dprectool` utility (it's included in the Windows installer package and can be built from source by setting `-DTOOLS=ON` when calling cmake.)
Dprectool converts dprec files to dptxt files and back. Dptxt is a text version of a dprec that's easier to read and write by hand. In the `scripts/` folder is also a `dptxt.py` script for parsing and generating dptxt files. (plus `spiro-demo.py` and `calibration-rects.py` scripts that demonstrate how it's used.)

However, the recording only contains the commands issued to the paint engine, so it requires either Drawpile itself, or an exact reimplementation of its paint engine to turn into an image. One thing I've been meaning on writing is a command line tool that does exactly what you want: take a dprec and output one or more images.

A very basic version of this tool that just reads a dprec then writes an image should be very easy to write. Drawpile client source code is now divided into two parts: `src/client/` which contains the paint engine and all GUI-agnostic code and `src/desktop/` which contains the GUI parts. If you know basic C++, it would probably be easier to write the tool rather than trying to interface with the GUI application.

Take a look at `src/client/recording/indexbuilder.cpp` This class already does pretty much what you need. The relevant section would look something like this:

	void dprec2image(const QString &dprecFileName, const QString &outputFileName) {
		// The data structures to hold the layer stack and drawing state
		paintcore::LayerStack image;
		canvas::LayerListModel layermodel;
		canvas::StateTracker statetracker(&image, &layermodel, 1);

		// Recording file reader
		Reader reader(dprecFileName);
		MessageRecord record;

		// Read and execute drawing commands
		do {
			record = reader.readNext();
			if(record.status == MessageRecord::OK) {
				protocol::MessagePtr msg(record.message);
				if(msg->isCommand())
					statetracker.receiveCommand(msg);
			}
		} while(record.status == MessageRecord::OK);

		// Save canvas as an image file
		image.toFlatImage().save(outputFileName);
	}

(This is actually not entirely right: it assumes the recording is pre-filtered. For correctness, the CanvasModel should be used instead instead of using LayerStack and StateTracker directly, so it will do the message filtering. However, for just generating a screenshot this is probably good enough to get started)

**Comment by rakunko** [comment]
Thank you for the quick response! I will take a crack at it with C++ (its been a few years) if not I might make a janky python gui automation script that just loads the dprec/dptxt file from the server location and goes through the motions.
