### ISSUE TITLE
[2.0.4]Unknown option 'web-admin-port'

### ISSUE THREAD

**Issue by pachuco** [drawpile/Drawpile#464]
I am trying to set web admin port to headless dedicated server, but it's telling me it's an unknown option.

This is how I am launching it:
drawpile-srv --web-admin-port INSERTPORT --local-host INSERTHOST --database myserv\data.db --sessions myserv\sessions

**Comment by callaa** [comment]
I'm assuming this is with the Windows version? In that case the problem is that the Windows version is not built with libmicrohttpd, so the remote admin feature is not enabled. (I didn't expect that anyone would want to run the windows version in headless mode.) I'll see if I can enable it in the next release.

**Comment by pachuco** [comment]
Yes, windows.

**Comment by SpawnSean** [comment]
@callaa , any updates on this?

**Comment by callaa** [comment]
Yeah, I haven't added it to the build script yet. I suppose all that's needed is to install libmicrohttpd in the build image dockerfile. At some point, I'm going to write a new web based admin UI for the server, which will probably replace the current UI, so I'll have to add Windows support then.

**Comment by Wazbat** [comment]
How would be go about doing this? I haven't had a chance to work with docker properly yet, otherwise I'd be happy to submit a PR for this, or even build it for personal use. I can't figure out when in the dockerfile it'd go, assuming I'm looking at the right dockerfile.

I'm also interested in this feature

**Comment by callaa** [comment]
The Dockerfile in question is the one in `pkg/win`. Where it runs the "make download-*" stuff, download-libmicrohttpd should be added, and also on the build line.
I'll try to add it when building the next release. I should also update the other dependencies, since they're so old they're probably not available for download anymore.

Do note that, at the moment, the admin API can only be enabled when running the server in headless mode, so even on windows you'll need to run it in the command prompt.

**Comment by Wazbat** [comment]
I appreciate the prompt reply. I'll try building it locally to see if that works.

I'm eager to see what the web based UI will look like. I'm guessing that'd use this same API? If so, how do you think you'll implement starting/stopping the server? Would that option work for remote servers too?

**Comment by Wade821** [comment]
This is not a support issue.

**Comment by notfood** [comment]
It's a support issue, they built it with missing dependencies.

**Comment by Wade821** [comment]
> Yeah, I haven't added it to the build script yet. I suppose all that's needed is to install libmicrohttpd in the build image dockerfile. At some point, I'm going to write a new web based admin UI for the server, which will probably replace the current UI, so I'll have to add Windows support then.

> The Dockerfile in question is the one in pkg/win. Where it runs the "make download-*" stuff, download-libmicrohttpd should be added, and also on the build line.
I'll try to add it when building the next release. I should also update the other dependencies, since they're so old they're probably not available for download anymore.

I see how old it is, but it's definitely a missing feature. I see how old it is, but @callaa is basically saying he needs to modify the build script so compiling from script will properly build the server so it can run in headless mode.

**Comment by callaa** [comment]
Sorry, I keep forgetting this feature. I'm planning a (yet another) big rewrite of the server, but it looks like that's not going to happen in the immediate future, so I'll look into this right away.

**Comment by callaa** [comment]
Looks like this isn't as straightforward as I thought. For some reason, libmicrohttpd is refusing to build in the dockcross/MXE environment. Running `make libmicrohttpd` will just say say that the package is disabled, but will mark it as installed. This seems to be due to me using the mingw.shared build type, but the package is apparently made for static build only. If I remove the line that disables the shared build, the build still fails because it can't compile the  test program.

**Comment by askmeaboutlo0m** [comment]
This is solved in Drawpile 2.2, we now build with libmicrohttpd on Windows.
