### ISSUE TITLE
Layer alpha to selection

### ISSUE THREAD

**Issue by brummerke** [drawpile/Drawpile#475]
It would be nice to have an option to select the contents of your layer.
Sorry if it exists, i've scoured through the windows and menus but i can't find it anywhere.

In photoshop the shortcut for it is just ctrl+clicking the layer,  and it creates a feathered selection based on the alpha of your layer (not sure if drawpile allows that, but it's not strictly necessary).

It basically loads up your entire alpha into a selection mask, it's a useful feature for painting as well, since if you create a mask based on your solid color, then you can freely paint on it without painting outside your line-art.

Additonally, i'm not sure if it's possible as of yet, but an option for users to auto-create their layers would be nice as well. Meaning new users would have their own private layer without being able to create or access layers of other people.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Layer groups are coming in Drawpile 2.2, they will support alpha preserve. Put a layer into a group, put another one on top, set the mode to Recolor (or anything other than Normal) to make it clip to the layer below.

Auto-creating layers would be something that a bot would be better for, rather than having it baked into Drawpile itself.
