### ISSUE TITLE
Switching Colors with X

### ISSUE THREAD

**Issue by amyanimalover** [drawpile/Drawpile#485]
Hi there, I've been playing around with painting on drawpile and I'm not entirely sure how switching works. I actually wish it were simpler like it is on Photoshop, where you see two main swatches that flip to and from. For some reason, if I were to colour pick a colour, it does not register as a real "color" switch, and reverts to whatever I manually picked on the colour wheel. Anyone know what's up with it?

http://i.imgur.com/KKIyvQX.gif

I'm not sure what's going on, but I have three swatches, and it switches between two different colors...

**Comment by callaa** [comment]
There are two color history sets that the X shortcut switches. At the moment, a color is added to the history only after it has been used, which leads to that unintuitive behavior. This is not really a design decision, it just works like that because it was easy to implement. I should change this so that modifying the selected color updates the history immediately.

**Comment by amyanimalover** [comment]
Alright, I'll be sure to look out for your next mini update! I have a habit of pre-emptively selecting colours I will need in advance (and I switch colours a lot with the area dropper) so this will be most helpful.

**Comment by callaa** [comment]
I've now implemented this change and it will be part of the next release.
