### ISSUE TITLE
Connection issues in remote admin

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#500]
We've kind of delved into this before, but I keep encountering this error, where after awhile, remote admin will not let me log in. Terminal launched with remote admin gives this error:
**"sessionlist" query failed: QJsonDocument({"message":"Connection closed","status":"error"})**
Server side gives the message: 
**Not enough memory for write!
Closing connection (failed to create response header)**

This appears to be a message from libmicrohttpd, looking up the server side message.
Running another server beside the current with the exact same settings (but different port and web-admin-port) works fine. Shutting down and restarting server fixes it.

**Comment by callaa** [comment]
That error message is interesting. It looks like libmicrohttpd is running out of memory (it uses a memory pool for all dynamic allocations.) The default pool is only 32Kb, but that shouldn't be the problem, since when that error starts happening, it happens on all requests, even small ones. (Although it might be a good idea to increase the buffer, since a large session or user list might be more than that.)

The fact that the problem appears after a using the remote admin for a long time suggests it's a memory leak.

**Comment by tincancrab** [comment]
https://gnunet.org/bugs/print_bug_page.php?bug_id=4007

This may be a fix, which I will look into. It's odd you do not see the issue on your server.

**Comment by tincancrab** [comment]
Going to be honest, not sure how to increase the memory for libmicrohttpd. Most places I'm looking at just say they've fixed it in later releases.

**Comment by Wade821** [comment]
Fixed in 2.1.15.
https://drawpile.net/news/release-2.1.15/
