### ISSUE TITLE
Allow zoom in Flipbook

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#505]
Drawpile is a collaboration program, more than often when animating you will find yourself with several people in a large canvas each working on their own separate animation making previewing your animation difficult because the canvas is so large and your animation is so tiny, it's troublesome.

Would be very useful for us that use Drawpile as an animation program to preview just the area that we are working with, either by defining bounds, cropping it on the flipbook or just zooming in. It's important that those settings are kept between each preview, to ease the workflow of animating.

**Comment by callaa** [comment]
This is now implemented.

**Comment by blurymind** [comment]
@callaa Thank you very much 👍

**Comment by notfood** [comment]
It appears that it only crops but doesn't zoom. It's not very helpful right now.

![tiny](https://user-images.githubusercontent.com/5370107/35243547-4c6249de-ff8b-11e7-8bb8-1d72cd1ee7e2.png)

**Comment by callaa** [comment]
Ah, I interpreted "canvas is so large and your animation is so tiny" to mean the animation is just small relative to the canvas. I changed it so that if the canvas (or cropped area) is smaller than the viewport, the image is upscaled by the largest integer factor that fits. I also fixed a downscaling regression.
