### ISSUE TITLE
HUION tablet keeps swapping brush for Eraser

### ISSUE THREAD

**Issue by 4cer** [drawpile/Drawpile#509]
I downloaded DrawPile recently, but ever since I installed it, I had trouble drawing, due to an annoying brush issue. Whenever my stylus enters the detection range of my pen tablet, the program automatically switches my brush preset nr1 through nr5 to brush preset Eraser (/nr6). The tablet model is HUION Inspiroy Q11K, with all latest drivers installed. I have confirmed it to work with all other software including Photoshop or GIMP, so I do believe it to be a DrawPile-related issue.

To be clear, it doesn't make me unable to draw, I can always switch right back to my preferred preset, but I'd rather it wasn't something I have to do regularly. In fact, since I use all the presets, it can be confusing or simply annoying.

EDIT: A friend of mine, who also happens to be using a HUION tablet (model 1060 PLUS) does not experience the switching issue. That said, aforementioned tablet has been on the market for a longer period of time than the one I use.

**Comment by callaa** [comment]
The tablet tip detection sometimes does not work correctly. It seems to be related to the driver version and/or Qt version. I'm going to add an option to disable the tip detection feature so that at least it won't get in the way if it's not working.

**Comment by 4cer** [comment]
Another thing that came to my mind that I consider noteworthy here is that the tablet my friend has, indeed uses a different, legacy version of the driver.

**Comment by kevinir** [comment]
I was having this exact same issue on my new Q11K, except it was occurring in PSCS6. I found the fix in this thread https://forums.adobe.com/thread/1309177. To opt out of the seemingly permanent eraser mode, set a button, whether on the pen or one of the programmable ones, to the "switch brush" option in the Huion Driver. I have no idea what shortcut or keystroke combo it actually is but it does the trick. Hope it helps since this completely halted my workflow and learning time with the tablet.

**Comment by callaa** [comment]
I don't know if there is anything I can do on my end to solve the actual bug, but as a workaround, the latest version now has an option to disable eraser detection.
