### ISSUE TITLE
Surface Pen Needs to hold the side button to draw without moving whole canvas

### ISSUE THREAD

**Issue by ColeAche** [drawpile/Drawpile#526]
A strange issue has popped up. The Surface Pen now requires you to press the side button in order to draw without moving the whole canvas. 
All the Wintab drivers are up to date, and the pen functions normally otherwise, but you now must press in the side button to prevent the pen from dragging the entire canvas. This makes controlling pressure quite a chore, so any update to address this issue would be greatly appreciated.
![drawpile issue 11 11 17](https://user-images.githubusercontent.com/33590698/32696161-4278c282-c736-11e7-9ecd-4f37a357a4e4.gif)

**Comment by NGMZero** [comment]
Hello, I will explain what i know about this problem.

Windows 10 fall creator update (version 1709) changed how the pen function. Before the pen was more like a mouse left click with pressure sensitivity, after the update it will function more like a touch input (tap or tap and drag) with pressure sensitivity. drawpile will think you are trying to touch the canvas with one finger when you use the pen now.  

I had to revert back to the preview version of windows because this also broke some other older drawing programs I use. Until windows provide a fix. 

I did not try this in drawpile as a work arround, but you could try to disable the touch with finger option ( Edit > Preference > Touch with finger ).

**Comment by callaa** [comment]
This is the same problem as in issue #531. (I'm closing this issue to consolidate the reports.)

Disabling "scroll with one finger" is currently the only known workaround. You can still scroll the canvas by using two fingers, though.
