### ISSUE TITLE
Could not connect to server. Connection refused??

### ISSUE THREAD

**Issue by porkchop84** [drawpile/Drawpile#537]
Why is this happening? I can't connect to a certain room but others can. It has been going on for weeks now. Please help.

**Comment by callaa** [comment]
Which server? The one at drawpile.net or others? If others, is the server address an IPv4 (xxx.xxx.xxx.xx) or IPv6 (like ffff:ffff:fff:ffff:ffff) address?

**Comment by Airrocket** [comment]
I'm having the same issue. I'm trying to connect to a session hosted on my desktop with my laptop. Both computers are running the same version of Drawpile. I've tried connecting to an open session through the find menu, with the session code, and I've tried connecting to a private session with the IPv4 address. Could this be because both computers are on the same network?

**Comment by callaa** [comment]
If both are on the same network, try connecting directly using the local IP address. Connection issues like this are almost always due to firewalls. If you can't connect with the local IP, then it's most likely the Windows firewall (or the security suite's firewall) that's blocking the connection. If you can connect locally, but not over the Internet, then the problem is either that the router is not set up to do port forwarding or your ISP is blocking incoming connections.

**Comment by notfood** [comment]
Stale, closing. For connectivity issues feel free to open your own issue.
