### ISSUE TITLE
About Pixel Art

### ISSUE THREAD

**Issue by Fusionnist** [drawpile/Drawpile#545]
The current brush tool does not allow for precise pixel placement and can be very frustrating to use when making pixel art. I'd be very happy to see a feature that would fix that - a simple brush that doesn't 'drag along' would suffice.
Thanks you for considering this :)

**Comment by callaa** [comment]
Do you refer to the brush outline not snapping to pixel boundaries?

**Comment by Darudado** [comment]
https://cdn.discordapp.com/attachments/300375511744512000/404726786216165376/example.gif

This is what we meant. 
It's incredibly hard to be precise with it and this prevents us to implement a permanent server for it in the community. 

But I see that you already added a commit.

**Comment by callaa** [comment]
Yeah, I noticed a regression. The brush outline should snap to the center of the pixel when a hard edged brush is selected. This was probably broken a few versions ago.

The stroke trailing the cursor as seen in the gif is caused by input smoothing. You can fix it by setting the *smoothing* slider to zero in the input dock.
