### ISSUE TITLE
Feature: Advanced user management

### ISSUE THREAD

**Issue by tincancrab** [drawpile/Drawpile#558]
Since I will be investing into the user registration system soon, I'd like to suggest this. I know that there is an option within the base server that makes it so only registered users can join. Is it possible to do this by room, or even better, restrict layers to registered/approved users/ users with a special flag, so that their drawings are protected and allows us to verify the new user is not a person with ill-intentions?

The next thing is user groups. Allowing person within a certain usergroup on the database be allowed functions such as cut and paste, but not exclusively set op-permissions like layer management? I know this is asking quite a bit.

Lastly, is there any possible way to add a 'forbidden names' list? With wildcard characters to prevent sneaky name workarounds? Some people who think they're funny like to enter the room with racist names, most commonly n***er (sorry for censoring, but its a term that is unacceptable in the US). We ban them, but they easily get a new ip address from vpn and do the same thing again.

**Comment by callaa** [comment]
>I  know that there is an option within the base server that makes it so only registered users can join. Is it possible to do this by room, or even better, restrict layers to registered/approved users/ users with a special flag, so that their drawings are protected and allows us to verify the new user is not a person with ill-intentions?

Currently, no such option exists.

I considered adding a session option that only lets authenticated users in, but I was not sure if it would actually provide much added value. However, now that I think about it, I can imagine trolls being focused on a specific popular group on a server, with  smaller groups and random sessions not affected to the same extent. Does this match your experience?

>Allowing person within a certain usergroup on the database be allowed functions such as cut and paste, but not exclusively set op-permissions like layer management?

Currently, these features can be restricted to session operators only:

 * Layer creation/deletion and reordering
 * Image pasting and fills
 * Annotation creation

(Also, there is an option to lock all new users by default.)

It would be possible to add tiered access levels, so instead of a binary OPs/everyone choice, the choices could be:

1. Everyone
2. Authenticated users
3. Operators

The lock new user tiers could be: lock everyone / lock guests

The access control settings are pretty complicated already, so I'm not sure about adding user groups to the mix. However, a similar effect could be achived by adding a new `TRUSTED` user flag. Then the tiers would be:

1. Guests (unauthenticated users)
2. Authenticated users
3. Trusted users
4. Operators (not necessarily authenticated)

The TRUSTED flag could be assigned via the user account editor, the way HOST and MOD flags are assigned now. It could also be assigned via the ext-auth mechanism.

I am working on a feature on the website that will allow server admins who use drawpile.net's ext-auth to define a user group for their server. The user group will make it possible to override various settings, such as permitting only a subset of users to log in, limiting hosting privileges and selecting group specific moderators. It would also provide a way to set the TRUSTED flags.

>Lastly, is there any possible way to add a 'forbidden names' list?

A name blacklist could certainly be implemented. Although in practice, it is quite difficult to catch all the variations of offensive names, especially without false positives. This is further complicated by the fact that Drawpile allows Unicode characters in usernames, which enables all sorts of trickery with confusable characters.

On the website I've implemented some guards against names that look deceptively similar. A profanity filter could be added as well.

Probably the easiest way to counter the offensive name problem would be to require authentication to join the room... And this actually gave me an idea. When both guest logins and ext-auth is enabled, the server will query the ext-auth server to see if a name is reserved or not. At this point, the auth-server can also check if the name contains any offensive words.

**Comment by tincancrab** [comment]
> I considered adding a session option that only lets authenticated users in, but I was not sure if it would actually provide much added value. However, now that I think about it, I can imagine trolls being focused on a specific popular group on a server, with smaller groups and random sessions not affected to the same extent. Does this match your experience?

Yes, this is the case 75% of the time. Trolls generally target rooms that have a larger crowd, though it's not surprising for them to go into a room with 2 users and scribble all over it.

>  Currently, these features can be restricted to session operators only:
> - Layer creation/deletion and reordering
> - Image pasting and fills
> - Annotation creation
> (Also, there is an option to lock all new users by default.)
>
> It would be possible to add tiered access levels, so instead of a binary OPs/everyone choice, the choices could be:
> 
> 1. Everyone
> 2. Authenticated users
> 3. Operators
> 
> The lock new user tiers could be: lock everyone / lock guests
>
> The access control settings are pretty complicated already, so I'm not sure about adding user groups to the mix. However, a similar effect could be achived by adding a new TRUSTED user flag. Then the tiers would be:
> 
> 1. Guests (unauthenticated users)
> 2. Authenticated users
> 3. Trusted users
> 4. Operators (not necessarily authenticated)
> 
> The TRUSTED flag could be assigned via the user account editor, the way HOST and MOD flags are assigned now. It could also be assigned via the ext-auth mechanism.

I know this is asking a lot of you. I've tried delving through the code myself to see if I couldn't add a usergroup that you could have separate permissions for. We lock all features by default to prevent anyone from editing posted rules, pasting huge/lewd pictures, using fill, and deleting/moving/renaming layers. Unfortunately, if a user wants to move, resize, or paste a drawing to another layer, they must have OP status. This is a lot of power for someone who just wants to move to a quieter portion of the board, and renamed/missing layers and edited rules occasionally happen as a result. We also like to restrict outside picture pasting as it bloats the session size, even after reset.

I also understand asking for layers to be restricted from certain groups (guests/unauthenticated users is what I have in mind) is a lot to ask for. I honestly wish I could help more on the coding side of things.


I will be implementing a user system soon, but I was unable to build the website you provided from the github successfully about a month back. I spoke to a acquaintance who deploys websites, and he said there were possibly dependencies missing in the list. I may have to manually build one and hope it matches what Drawpile is looking for in a database.

**Comment by callaa** [comment]
I can add the option to limit session logins to authenticated users in the next release.

However, the tiered access levels require backward incompatible protocol changes, so those will have to wait until 2.1. (Which I'll probably start working on after the next release.)

Adding the same tiers to layer access controls is possible too.

Feel free to email me if you have questions about integrating the user accounts.
