### ISSUE TITLE
Recordings sometimes save with no canvas or layer data

### ISSUE THREAD

**Issue by weylin6** [drawpile/Drawpile#561]
Several recordings I've made won't produce a canvas or layers when opening them. It just plays through slowly without showing a thing. Oddly, if I index the recording, thumbnails will show up that are appropriate for the recording, but nothing shows up otherwise.

Additionally, if I go to resize the canvas on these, it says it's 1x1
If I expand the canvas, nothing happens, because there's no layers, it just shows transparency.
If I add several layers before starting the playback, the recording DOES start to play out properly.

This seems to happen to specific files, as in, a file that does this once will always do this, while other files will be perfectly fine and never have this issue.

**Comment by callaa** [comment]
Can you send me a sample of a broken recording? Just the first 100kb or so is enough. My guess is that there is a session ownership message missing and the initial canvas size setting message gets filtered away.

**Comment by callaa** [comment]
I think I now know how this bug happens. You should be able to fix the broken recordings like this:

1. Convert it into dptxt format with dprectool
2. Somewhere at the beginning of the dptxt file, there should be a line like `n resize`, where `n` is a user number
3. Add `0 owner users=n` (where `n` is the number number from the resize line) before the resize
4. convert the dptxt file back to a dprec file with dprectool (Optional step: Drawpile can read dptxt files as well)

The cause of the bug is that the recording files are unfiltered and Drawpile filters them when they're played back. If the initial messages that control filtering are not included, important commands like the initial canvas size setting get filtered away.

I will change the way recordings are made so that the content is pre-filtered. That should eliminate this and any related bugs.

**Comment by callaa** [comment]
I've now implemented the change. Broken recordings opened with the next version should now work, although messages that should have been filtered away may now render. It is still possible to manually repair these recordings by inserting the appropriate permissions, as described in the previous comment.
