### ISSUE TITLE
Exporting animation as image series causes duplicate/skipped frames

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#563]
This can't be reproduced consistently.

Sometimes when you export an animation as an image series, it saves 3 of the same frame then skips 2 and so on, happens on Windows more often but it also happens under Linux. You need to export repeatedly until it produces the expected output and sometimes it never does.

It should not try to factor FPS at all when it comes to exporting the layers as image series. My guess is that the FPS setting is causing the duplicates.

**Comment by callaa** [comment]
Hmm, this is a mysterious one. The image series exporter doesn't use the FPS setting, so that can't be it.

The exporting is performed by the `AnimationExporter` class, which has a `saveNextFrame()` function. This function is connected to the video exporter's (image series exporter in this case) `exporterReady` signal with a queued connection.

The saveNextFrame function calls the image series exporter's `saveFrame` function. The frame counter is incremented after the saveFrame call.

At the end of the saveFrame function, the exporterReady signal is emitted. If the signal/slot connection were direct, this would cause a recursive loop that would keep writing the same image until until the program ran out of stack space. However, if for some reason the signal would sporadically get delivered immediately, it would cause the symptoms you describe.

I was just going to write that I don't know how that could happen, but actually I do have a suspicion... Before the frame counter is incremented, there is this line: `emit progress(m_currentFrame)`

This is connected to the `setValue` function of the progress dialog. I just checked Qt's source code and that function spins the event loop if the dialog is modal... That would explain how saveNextFrame slot gets called before the frame counter is incremented!
