### ISSUE TITLE
Feature : Fill Selection Opacity

### ISSUE THREAD

**Issue by shadowcopalypse** [drawpile/Drawpile#564]
Making a suggestion to add opacity controls to 'Edit -> Fill Selection' command.

**Comment by askmeaboutlo0m** [comment]
Since adding controls to a menu option isn't really feasible, there's instead an opacity slider in the fill tool now instead and you can set it to fill the entire selection.

It's available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for suggesting!
