### ISSUE TITLE
Mac OS X El Capitan can't run drawpile because of "problem"

### ISSUE THREAD

**Issue by car-ciofi** [drawpile/Drawpile#569]
I used the most recent version available on the website and followed the instructions to ignore Apple's warning and open the program anyway. However, I got another error warning that reads as follows:
Drawpile cannot be opened because of a problem.
Check with the developer to make sure Drawpile works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.

I have reinstalled it to no avail. Are there any fixes to this issue?

**Comment by callaa** [comment]
Can you try running Drawpile through the Terminal? You can do it by starting the Terminal app then switching to Drawpile's installation directory. E.g. if you copied Drawpile to the Applications folder, you can run it by typing this into the terminal:

    cd /Applications/Drawpile.app
    ./Contents/MacOS/Drawpile

It should print out some extra debugging information about why it doesn't run. (My guess is that since I built it on High Sierra, some library not available on older macOS versions is being referenced.)

**Comment by notfood** [comment]
![image](https://user-images.githubusercontent.com/5370107/36822631-0ec0a658-1cc7-11e8-98f3-50bdebf69acc.png)

I got Mac user having the same issue. Missing lib?

**Comment by callaa** [comment]
Probably the same problem as in issue #570. Since the previous version works, I most likely messed up the packaging somehow.

**Comment by car-ciofi** [comment]
> I got Mac user having the same issue. Missing lib?
> 
> Reverting to 2.0.8 is the workaround for now.
> 
>  
>  Owner

How can you access version 2.0.8? I'm not seeing it on the older versions page.

**Comment by notfood** [comment]
Over here: https://drawpile.net/files/osx/
