### ISSUE TITLE
Persistent Sessions closed when server restarts

### ISSUE THREAD

**Issue by KnicKnic** [drawpile/Drawpile#571]
Start server with --sessions and persistence = true

Kill server and start it again. Sessions still exist but are closed, titles are lost, creator is lost.

Expectation is sessions still exist and everything is still up and running.

I noticed a few things. When I change information about the session it is not flushed to the .session file. (I do not know if you lazily flush, or have some timer)

Also not sure if it makes a difference but my architecture is an armhf container.

**Comment by callaa** [comment]
You're right, the file isn't being flushed. I'll add the missing flushes and try if it fixes the problem.

**Comment by KnicKnic** [comment]
Can’t wait till the PR. Many thx!

**Comment by callaa** [comment]
The session journal is now flushed after every write (since those writes are uncommon,) and the actual recording file is now flushed every 30 seconds. Also, the server now refuses to load blank recordings.

However, if you're encountering this problem often, you're killing the server in a wrong way. Normally, SIGINT or SIGTERM should be sent so the server can shut down gracefully.

**Comment by KnicKnic** [comment]
Thanks, everything worked. 
I was "killing" the server the wrong way because of how the Dockerfile is written... I will submit an update soon.
