### ISSUE TITLE
Layers dock refreshes too much

### ISSUE THREAD

**Issue by notfood** [drawpile/Drawpile#593]
This issue particularly jumps when you are animating or you are using many layers, more users cause more updates.

It's easy to reproduce, merely create many layers then try to rename any or scroll down. The Layer list will refresh returning you to your selected layer and cancelling any rename. 

Makes it difficult to rename, reorder or just glance at other layers.

Perhaps it should remember what you were doing instead of canceling everything or simply delay those updates until you stop dragging, renaming or scrolling.

**Comment by callaa** [comment]
I'm unable to reproduce this bug. I created a many layers, then started renaming one. At the same time from another computer, I tried reordering, deleting and creating new layers. Only when I reordered or deleted the layer I was editing at the moment did the rename operation fail. (However, I did find a bug: the program will crash if a user is dragging a layer that gets deleted.)

Can you be specify the exact steps to reproduce this behavior?

**Comment by notfood** [comment]
Ah, it requires someone else to be drawing.

I tried again alone and it doesn't reproduce.

**Comment by tincancrab** [comment]
I see this often, but I mainly am in rooms with 30+ users. Is it possible to attempt to reproduce this bug in a room with many users drawing?

**Comment by tincancrab** [comment]
Oh. You'll have to be op for these rooms. Callaa, you may want to try testing by letting people know you need op in the Discord server.

**Comment by Wade821** [comment]
After reading comments here, yeah I can say that the live updating/refreshing of the lists makes the most sense as the cause of this issue. Reposting my comments from Discord as well below.

> One other thing that has bugged me and I've never really been able to figure out what triggers it... but in Drawpile if I'm renaming a layer, sometimes it will complete the changes before I've finished typing as if something triggers it to say it's completed. As of the immediate moment, I've also noticed there's a problem with boards that have a lot of layers. If I'm trying to scroll down the layers list, it'll sometimes go back to the top unprompted so I have to scroll back down again. It can also be prompted to scroll back down as well, unprompted.
> 
> It's beginning to be a real bother so I figured I'd mention it.

**Comment by speewee** [comment]
I can confirm this bug too. It is nearly impossible to rename a layer, when several people are on the server. Taking care of this bug would be nice.

**Comment by Petschko** [comment]
Yes thats a big issue, dragging layers/renaming isnt possible (or just super hard) even with just 4 people
Its caused the refresh when someone is drawing. Wouldnt make it more sense to just update, when something in the layerlist was updated (layername, density/visibility)

**Comment by Wade821** [comment]
Documenting here for a visual reference. 

Drawpile Layer Rename Bug - Clears out before able to finish typing name at random as people are drawing on the board
https://cdn.discordapp.com/attachments/544996573600284675/647669518704836628/bandicam_2019-11-22_22-21-16-618.mp4

Layer menu jumps back down to active layer when trying to scroll through list bug
https://cdn.discordapp.com/attachments/544996573600284675/647669626104446997/bandicam_2019-11-22_22-25-59-073.mp4

**Comment by askmeaboutlo0m** [comment]
I've been looking into this bug.

The issue occurs only when an undo happens. Any other layer operations (other than the layer itself getting deleted by another user while you're renaming it) don't trigger it.

Undoing involves Drawpile rolling back to a previous savepoint and then replaying the things that happened since then. The rollback involves resetting the layers to be the way they were at the time of that savepoint. This reset triggers a model reset, which causes Qt to close the edit control.

I've had various approaches to fixing this:

* Ask Qt to please keep the edit control open. Doesn't seem to be an option due to lack of control. There's a persistent editor that stays open, but it's terrible in every other way, so I kinda gave up on that for now. Maybe a Qt guru could figure out how to do it though.

* Remember the editor widget state and then restore it after the reset happens. This is an absolutely terrible hack that ended up looking ugly as sin about halfway through, so I also ditched that.

* Avoid the model reset when doing a savepoint. Don't update the UI model when replaying the events. Then apply the difference between the state before and after the undo via the normal operations. I haven't tried this yet, but it seems like the best bet so far. I guess there needs to be a way to detach the UI model from the internal stuff, or maybe Qt provides for something like that. Computing the difference between the two states takes effort, but should be possible. Maybe I'll get to that sometime, or someone else can continue from here.

After the model reset is performed, Drawpile also restores the selection, so if you were scrolling around, your scroll position gets yanked to the currently selected layes. That's pretty easy to fix though: just don't do that.

**Comment by askmeaboutlo0m** [comment]
I think I've solved this now. #971 removes the errant scrolling. #973 resolves the renaming getting cancelled by moving the functionality to a separate dialog altogether, which won't be affected by a model reset on the layer list.
