### ISSUE TITLE
Can't Draw

### ISSUE THREAD

**Issue by muppettss** [drawpile/Drawpile#594]
This hasn't happened before. Whenever I use drawpile, it won't let me draw. I used the tablet tester, and it's receiving my strokes fine. I've tried it with both my Monoprice tablet and my Wacom tablet, as well as my mouse, and nothing's working. My current version is 2.0.10.

![image](https://user-images.githubusercontent.com/37987317/38178063-e4097696-35c7-11e8-98cd-230f3445aa85.png)

**Comment by callaa** [comment]
What happens when you try to draw? Do the brush strokes just not show up? If that is the case, can you make a sample recording like this:

1. Select "Record" from the File menu and "Text recordings" as the format
2. Draw a short stroke on the canvas
3. Stop the recording (from the File menu)
4. Open the recording file with notepad and copy&paste it here (it should be short enough.)

**Comment by notfood** [comment]
Very likely a blending mode issue. Stale, no response from submitter, closing.
