### ISSUE TITLE
Debian 9 Linux server: compiling with -DTOOLS=on fails at 95%, but the tools are built fine.

### ISSUE THREAD

**Issue by f2d** [drawpile/Drawpile#598]
I'm compiling Drawpile server on Debian 9 Linux 2.6.32-042stab123.3 on i686.

I installed these packages, a list from the Docker file:
`apt-get install wget cmake make qtbase5-dev libkf5archive-dev g++ qtm qtmultimedia5-dev libqt5svg5-dev libgif-dev libkf5dnssd-dev libmicrohttpd-dev libsodium-dev`

The following command finishes fine:
`cd build && cmake .. -DCLIENT=off -DSERVERGUI=off -DINITSYS=systemd`

Result: **drawpile-srv** executable, no problems.

Next, the following command fails at [95%]:
`cd build && cmake .. -DCLIENT=off -DSERVERGUI=off -DINITSYS=systemd -DTOOLS=on`

Result: **fatal error: QGuiApplication: No such file or directory** while trying to build drawpile-cmd.
Completed **drawpile-srv** and **dprectool** executables, fully working (which is all I wanted anyway).

I attached the last command output log.
[cmake.log](https://github.com/drawpile/Drawpile/files/1885907/cmake.log)

**Comment by callaa** [comment]
I'll improve the documentation. In the meantime:

 * -a: this controls whether to include annotations (text boxes) in the output image
 * -e: here "sequence" means the sequence of commands between undopoints (e.g. an entire brush stroke)
 * -m: "message" is the primitive drawing command, often a piece of a brush stroke
 * -A: this should be used when rendering recordings made by the server. The client (since version 2.0.9) makes prefiltered recordings.

If `-e` or `-m` is not specified, just the final canvas from the end of the recording is output.

Tip: when running drawpile-cmd in a headless environment, you can use the argument `-platform offscreen` to avoid the need to have an X server. (The platform plugin can also be selected with an environment variable, but I don't remember what it is.)

**Comment by f2d** [comment]
Same for Ubuntu 16.04 LTS, by the way: [libkf5archive5 is version 5.18.0-0ubuntu1.1 at most](https://launchpad.net/ubuntu/+source/karchive).

Same workaround applies, build finishes, drawpile-cmd and dprectool are working.

I completed most of my archival scripting, although web folder itself looks pretty rough for now.

Old server did not have enough RAM (512 MB total) to render a 5000x4000px 30000-stroke session to the end. With image every 1000 strokes it exited while creating 28th. So I'm going to a new server right now.

**Comment by notfood** [comment]
This has been fixed for a while now.
