### ISSUE TITLE
Multiple monitors messing with UI

### ISSUE THREAD

**Issue by Derpydoo** [drawpile/Drawpile#605]
I have a multiple monitor setup, I have a standard 4k monitor and a tablet monitor.

When I open Drawpile it's UI is scaled for the 4k monitor so when i drag it over to the tablet monitor the ui is huge and takes up most of the screen meaning I have very little room to draw on.

I cannot find any UI scaling option in the settings, am I missing something?

**Comment by callaa** [comment]
I think by default a single scaling factor is used for all screens. (Relevant Qt documentation page: [High DPI Displays](http://doc.qt.io/qt-5/highdpi.html))

This behavior can be overridden by setting an environment variable or via a settings file. Since you didn't specify which operating system you're using, I'm going to assume Windows. I'm not sure how you can set an environment variable for a single application on Windows, so using a configuration file to override it is probably easier. Here's what you can try:

Create a text file (using notepad for example) named "qt.conf" in Drawpile's installation directory.
Copy & paste this into the file:

    [Platforms]
    WindowsArguments = dpiawareness=2

Other values you can try: 0 means no scaling, 1 means single scaling factor for all screens.

Can you report back whether this works? If it does, I'll make this setting the default.

**Comment by notfood** [comment]
Stale, no response from submitter, closing.
