### ISSUE TITLE
Persistent sessions by default (server side config)

### ISSUE THREAD

**Issue by KnicKnic** [drawpile/Drawpile#606]
Would it be possible to have a server side option that when the user creates a session on a private server that the session will default to be persistent?

**Comment by askmeaboutlo0m** [comment]
This has come up in a discussion recently again. The conclusion was that it would be pretty confusing to users, because they wouldn't know if their session was persistent or not without having to go into the session settings to check how this particular server behaves, and also requiring them to know that they have to uncheck that option for their session to actually terminate. So I don't think it makes sense as a general feature.

If you *really* need it, a workaround would be to just run a shell script like the following in a cronjob, which will persist each non-persistent session it can find once and alerts the session members that it did so, with instructions on how to un-persist them again.

```sh
#!/bin/sh
set -e
cd "$(dirname "$0")"

# Fill these in with the correct values.
API_URL='http://localhost:27780/api'
USER='admin'
PASS='password'
MESSAGE='This session has been made persistent. You can change this by going into Session > Settings and unchecking \"Persist without users\".'

# Grab currently running sessions.
sessions="$(curl -fsSu "$USER:$PASS" "$API_URL/sessions")"

# Don't persist sessions that were already persisted before, to allow users to
# un-persist them without fighting them on it.
filter_already_persisted_ids() {
    if [ -e persist-ids ]; then
        sort | comm -23 - persist-ids
    else
        cat
    fi
}

# Make all non-persistent sessions persistent and warn the users.
echo "$sessions" \
    | jq -r '.[] | select(.persistent | not) | .id' \
    | filter_already_persisted_ids \
    | while IFS= read -r id; do
        echo "Persisting session $id"
        curl -fsSu "$USER:$PASS" -X PUT -H 'Content-Type: application/json' \
            -d '{"persistent":true,"alert":"'"$MESSAGE"'"}' \
            "$API_URL/sessions/$id" >/dev/null
    done

# Remember the sessions we've seen so we don't persist them again.
echo "$sessions" | jq -r '.[] | .id' | sort >persist-ids
```

Requires `curl` and `jq`, evidently. Other stuff like `cat`, `comm` and `sort` should be part of coreutils.
