### ISSUE TITLE
[mac] tablet tester does not pick up my tablet activity

### ISSUE THREAD

**Issue by cerosxxy** [drawpile/Drawpile#615]
my tablet is an EasyPen1405x. i have reported this issue before but only got now to try it out.. yet it doesn't pick up my tablet. Also, I cannot find the bug workaround mode. Hopefully this gets fixed soon UvU

**Comment by callaa** [comment]
I removed the bug workaround mode from the latest version, since it's generally not needed anymore and tended to cause more problems than it solved. (In this case, if the tablet is not being detected, it wouldn't have helped anyway.) Currently, there is nothing I can do to fix this, if this tablet is not supported by Qt.
