### ISSUE TITLE
New layers

### ISSUE THREAD

**Issue by XPandoraX** [drawpile/Drawpile#630]
Even when layer controls and allow own layers are locked, people are still able to make new layers. It gets pretty annoying when people make like 5 extra layers. Even when you can't insert a layer you are still able to press the 3 bars next to the lock layer button and click new.

**Comment by notfood** [comment]
Under what circunstances? Any steps to reproduce? I tried to get around the layer locks with a normal user and I was unable to.

**Comment by tincancrab** [comment]
Its confusing, but you actually need to leave the box "Allown own user layers" unchecked. Checking it actually ENABLES users to create their own layers. Not well explained, i know, considering its under the "locked features". Just check layer controls box and you shouldn't have this problem.
Side note: users given # can use locked features.

**Comment by notfood** [comment]
It appears that when hosting a room initially setting the option "Lock layer controls" in this panel does nothing:
![image](https://user-images.githubusercontent.com/5370107/41808417-c9285a42-76a2-11e8-8459-610141b22281.png)

But if you go to settings after you created the room, the layers actually get locked.
![image](https://user-images.githubusercontent.com/5370107/41808408-9f3ed4d6-76a2-11e8-9a9e-0e38f4a00b3b.png)

Confirming bug in the initial settings panel.

**Comment by tincancrab** [comment]
Oh, that's a bug alright. But they are managing it from session settings. "Even when layer controls and allow own layers are locked..." leads me to believe they're under the assumption that checking that option means users can't create their own layers, but it actually enables them to create layers. This is more of a poor placing of an option box (or wording), since that setting is under the "Locked features" header.

**Comment by callaa** [comment]
Since version 2.1 contains a big rewrite of the permission system, I'm going to fix this there. (Or at least I'll try to make the option more descriptive)
