### ISSUE TITLE
Add drawpile to ios

### ISSUE THREAD

**Issue by allyzdooodez** [drawpile/Drawpile#655]
I happen to be a procreate user who draws on IOS and some of my friends draw on it too. I think it would be great for drawpile to be available on mobile hardware.

**Comment by tincancrab** [comment]
Wouldn't that be great?

Unfortunately, it would probably be very far on diwn the line in terms of development goals. iOS uses a different coding language from what Drawpile is built off of. Drawpile relies on open source tablet code.

However, if you or someone you know has familiarity with writing art iOS apps, I personally hope you could give some pointers, as I use procreate as well.

**Comment by blurymind** [comment]
Maybe the krita devs might have some

**Comment by tincancrab** [comment]
Dunno. Apple uses a different code than C++, which is literally 95% of Drawpile code, according to Github. That'd be amazing for on the go art socializing. I dont think anything like that currently exists mobile wise.

**Comment by callaa** [comment]
Qt is available for iOS as well, so it would be technically possible to to an iOS version, however due to Apple's licensing policies, it wouldn't be possible to distribute it in the App store. Apple's licensing terms are incompatible with the GPL license, so I would have to get a commercial Qt license (which is really expensive) and remove or rewrite all the parts of Drawpile that use someone else's code.
