### ISSUE TITLE
Overscrolling

### ISSUE THREAD

**Issue by panhartstuff** [drawpile/Drawpile#676]
Right now, there's a limit to how far can you pan the canvas off-screen. There should be an option to turn this off.
This is useful for, say, when you're drawing in a far corner of the canvas. Without an overscrolling feature, you can't centre that drawing area to the centre of your screen, making it really awkward to draw.

**Comment by callaa** [comment]
Hmm, this turned out to be a bit more difficult than I thought. It seems that with the current graphics system, removing the scroll limit is very difficult if not impossible. I'll be able to fix this when I rewrite the canvas. (Something which I'll have to do anyway at some point.) In the meantime, I tripled the padding around the scene so you will be able to scroll more.
