### ISSUE TITLE
New build issues

### ISSUE THREAD

**Issue by JamesDelaneyyy** [drawpile/Drawpile#684]
Have a couple issues with the new build. I'm not sure if it's due to a compatibility or something but I can't seem to host servers anymore.
![1](https://user-images.githubusercontent.com/31395047/52735786-03cdcc80-2fd1-11e9-98c0-427c6fdd5155.JPG)
It shows me the same thing now on the previous version as well.
Also  this thing,
![2](https://user-images.githubusercontent.com/31395047/52735831-1a742380-2fd1-11e9-81bd-88e22f52b149.JPG)
I'm guessing is where you can put your avatar for the chatbox, but it doesn't let me do anything about it. I assumed it was drag and drop but once on that tab, it locks the program and you can't alt-tab to get an image. 
That aside I can't see any of the servers in the server list whatsoever.

**Comment by callaa** [comment]
Are you hosting on your own server or drawpile.net? The "Hostname does not match client IP" is returned by the listing server when the server name (given by the `--local-host` parameter) does not resolve back to the IP where the request came from.

Avatars can be added from the settings dialog. (Although I'll probably implement drag&drop support for it too at some point.)

The server list is most likely empty because people aren't hosting many 2.1 sessions yet.

**Comment by JamesDelaneyyy** [comment]
I'm using the drawpile.net server. 
I checked the compatibility list but it seemed a bit confusing to me. Does it mean that I can't access /people can't see my server  if we're both not on 2.1 ?

**Comment by callaa** [comment]
The "Hostname does not match client IP" error is now fixed. (It was a bug in the listing server that was triggered by the way I deployed the new server.)

Yes, versions 2.0 and 2.1 are not compatible with each other. For this reason, you can (and should) run both until things have stabilized again.
