### ISSUE TITLE
MacOS Mojave night mode incompatibility

### ISSUE THREAD

**Issue by Charmandrigo** [drawpile/Drawpile#687]
No need for explaination
![captura de pantalla 2019-02-19 23 10 40](https://user-images.githubusercontent.com/30424766/53067884-cb7c3180-349b-11e9-97b6-6b0735853239.png)

I have MacOS Mojave night mode enabled

**Comment by callaa** [comment]
Support for macOS night mode was added in Qt 5.12, but currently I'm still stuck with Qt 5.9 because there is a very noticeable performance regression in newer Qt versions. This appears to be a known bug and will likely be fixed in some future release.

For the time being, as a workaround I disabled night mode support in Drawpile. Once Qt 5.12 becomes usable, I will re-enable it.

**Comment by callaa** [comment]
Version 2.1.8 now supports Dark Mode in Mojave.
