### ISSUE TITLE
Eraser and brush rubber banding

### ISSUE THREAD

**Issue by Nujiao** [drawpile/Drawpile#693]
In 2.0.11 after a session reset the brush and eraser would occasionally rubber band from their last position but now in 2.1.2 after rapid use of of brush and eraser hot key it will rubber band and get worse after a session reset. I will add a gif so you can view what I'm talking about.
![ezgif-3-a62b5bbc4f25](https://user-images.githubusercontent.com/39990590/54085513-6a66b180-4315-11e9-9538-fefec26d1d79.gif)

**Comment by callaa** [comment]
I believe I found the bug. When switching tools mid-stroke, the newly selected tool is in an uninitialized state. This can cause the program to crash if that tool has not been used yet, or that rubber banding effect if it has been, because the previous end point was still in memory.

That bug is now fixed in commit feb23789.
