### ISSUE TITLE
Two suggestions for 2.1.2

### ISSUE THREAD

**Issue by Nujiao** [drawpile/Drawpile#694]
Could you make the drop down say "drawpile.net" by default instead of "nearby", and make the locked room filter toggled on by default too.
![156324 2019-03-10_23-56-47](https://user-images.githubusercontent.com/39990590/54100786-a55cf980-4396-11e9-9791-ef3ab647ffb1.png)
Also could you make this context menu persist after clicking on it, it's much harder to undo someones drawings now.
![306027 2019-03-10_23-56-39](https://user-images.githubusercontent.com/39990590/54100833-db9a7900-4396-11e9-8b2e-e80a476df983.png)

**Comment by callaa** [comment]
I prefer to leave "Nearby" as the default. You only need to change it once, and this way users learn that the feature exists.

I'm not sure making the menu persistent is the right way to fix it. The moderation features (undo override and banning) need a better UI. Right now, they suffer from one huge flaw: a user can come in, make a mess of things and immediately leave and the operators won't be able to undo or ban them because they disappear from the listing.

A new user list view is needed that shows past users as well. This view could have bigger buttons for undo, redo and kick+ban.

**Comment by Nujiao** [comment]
> I'm not sure making the menu persistent is the right way to fix it.
well, i wasn't really looking to "

**Comment by callaa** [comment]
Nevertheless, I think this is feature should be fixed properly. I removed the buttons from the user list box, because of complaints that they were too easy to hit by accident. Putting them back would therefore just bring back the other problem.

**Comment by Nujiao** [comment]
> Nevertheless, I think this is feature should be fixed properly. I removed the buttons from the user list box, because of complaints that they were too easy to hit by accident. Putting them back would therefore just bring back the other problem.

Nonono, I wasn't suggesting re-add the box, I like the context menu better than the buttons.
I just wanted the context menu to stay open after you right clicked and clicked on an option.
Like this one.
![context-menu](https://user-images.githubusercontent.com/39990590/54312943-89cc3b80-45ae-11e9-8865-cbf211bcd731.gif)
Not, like this one which is how it is currently.
![android_context_menu_example_diagram](https://user-images.githubusercontent.com/39990590/54313028-c13ae800-45ae-11e9-892d-faf85c3812df.gif)

**Comment by Nujiao** [comment]
just bumping

**Comment by callaa** [comment]
I did some investigating and there appears to be no (non-hacky) way of keeping the popup menu open after clicking. However, there is now the new user list tab in the event log dialog with buttons for undoing, which also works for users who have just left the session.
