### ISSUE TITLE
Unable to join session bug 2.1.2

### ISSUE THREAD

**Issue by Uboaaaaaa** [drawpile/Drawpile#701]
After updating to 2.1.2 some of our users cant join our public session which hosted with drawpile.net. They get a message that they were banned, though they never were and they are not in ban list. Some of us assumed it's because we banned a user who had  a "drawpile.net" username. They can join other sessions hosted with drawpile.net though. And so far don't have this issue with syntheticdream.net.

**Comment by callaa** [comment]
Bans are handled by the server, so it's unlikely the problem is caused by the client version.

A user with the name "drawpile.net" has been banned from two sessions. These bans are session specific, so they do not affect other sessions on the same server. (Unless the same user gets banned multiple times from enough different sessions, in which case the autoban script will promote the ban to serverwide.)

This user has an IP address that belongs to a block owned by SingNet. Do the users affected by the problem also use this ISP? If so, the problem may be that SingNet is using carrier grade NAT and many users are sharing the same IP address. They can check this by using something like [ipecho.net](https://ipecho.net) to check their addresses. If the last number is 103, then this is the problem.

**Comment by notfood** [comment]
Stale, closing.
