### ISSUE TITLE
Full Screen mode (usability)

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#707]
Hi,
In photoshop there is a nice way to use the canvas in full screen and toggling on and off the tools and docks in the UI, pressing TAB (to toggle the docks) or just pressing the f key (it has 2 full screen modes).

It will be nice to implement those shortcuts (or alternatives ones) to have an eficent way to take advantage of the entire canvas and toggling to access the tools options, layers etc. faster.

Here a useful link that explains some of the photohsop screen modes:

https://www.photoshopessentials.com/basics/photoshop-screen-modes-interface-tricks/

Greetings

**Comment by callaa** [comment]
Toggling the docks (and toolbars) with tab is now implemented.

The keyboard shortcut (along with the shortcut for fullscreen mode) can be customized via the settings dialog. Now that this feature is implemented, I changed the fullscreen mode so that the toolbars and docks are not automatically hidden. The menu bar appears when you bring the mouse pointer to the top of the screen.
