### ISSUE TITLE
Improvement in User Interface Icons (Suggestion)

### ISSUE THREAD

**Issue by leandro2222** [drawpile/Drawpile#716]
First of all, the Drawpile software looks great and has a nice icons set. Said that, the following suggestions are meant to let it's user interface even better and easy for new users.

**Original icons set:**
![original](https://i.imgur.com/IchzEB2.png)

**Suggestion 1:** Mirror the 'fill tool' to let it facing the same direction of the 'fill tool cursor' and the same direction of the rest of the tools aswell.
![mirrored bucket](https://i.imgur.com/KkWloYA.png)

**Suggestion 2:** The standard order of the things (at least in the west side of the globe) is 'from left to right'. So, example, we have the 'volume' growing from 0 on the left to 100 on the right, we have the brush size and opacity growing from the left to the right too. Said that, its counter-intuitive to let the 'more zoom' button on the left side and the 'less zoom' on the right side. So the suggestion number 2 is to let the minus zoom on the left and the plus zoom on the right:
![zoom in out position](https://i.imgur.com/Hjjpcqp.png)

**Suggeston 3:** The Zoom tool should be in the same group of the 'zoom in', 'zoom out' and 'normal size' zoom:
![zoom group](https://i.imgur.com/UNQgHnF.png)

**Suggestion 4:** The 'Annotation' icon could have the letter A to let it's keyboard shortcut easier remembered ('A' also represents text in general because it's the first letter of the alphabet). Since the letter A is easier recognized as a letter (compared with T), we could waive the serif.
![annotation](https://i.imgur.com/VoM1GbP.png)

**Suggestion 5:** Not a visual change, a behavior change: The Zoom tool should work in locked layers. So when a person join a session with a 'shield layer' the user would be able to check details around the whole canvas (with the zoom tool) without to switch layers.

**Final Result:**
![final](https://i.imgur.com/3qrHY3Z.png)

...
Link to download the redesigned icons (mirrored bucket tool and annotation tool): https://mega.nz/#!NNoCGaCS!BzTEaqdDDtJCjf3ZYu8qGoWDd6S3DxP7dtD9G2h8VfM

**Comment by erik90mx** [comment]
I agree with all the suggestions except suggestion 4, because the icon is referring to “text” creation in the canvas, here are some of the icons used in some design tools:
 
![image](https://user-images.githubusercontent.com/3485891/54886409-5b235000-4e4d-11e9-8344-94b250c76e1c.png)
(Krita)
 
![image](https://user-images.githubusercontent.com/3485891/54886412-61193100-4e4d-11e9-9fee-a101014c0eb7.png)
(Photoshop)
 
![image](https://user-images.githubusercontent.com/3485891/54886414-65dde500-4e4d-11e9-8832-52d6579b2209.png)
(Gimp)
 
![image](https://user-images.githubusercontent.com/3485891/54886421-6d04f300-4e4d-11e9-9466-db0fe65e0876.png)
(Blender)

The current one in Drawpile:
 
![image](https://user-images.githubusercontent.com/3485891/54886427-78f0b500-4e4d-11e9-9250-c587c0ead60e.png)

Regards

**Comment by Le2222** [comment]
expanding the references avaible, the Illustrator (from Adobe just like Photoshop) uses the letter T just like Photoshop:
![Illustrator](https://i.gyazo.com/bf91a4f1bc1bda60ca1483cbb5389ffc.png)
while its main competitor, Corel Draw uses the letter A for text tool:
![Corel](https://i.gyazo.com/6d203810c97a9564bab674a585da4b45.png)
and a free alternative, Inkscape uses A for text too:
![Inkscape](https://i.gyazo.com/ad7a8eb7331db950c98ac73be822b0d6.png)

**Comment by callaa** [comment]
Suggestions 1 & 4: I'm using icons from the KDE Breeze icon set. Changes to them should be directed upstream (https://bugs.kde.org/)

Suggestion 2: this is doable
Suggestion 3: I disagree. The zoom tool is grouped with all the other tools. The buttons in the other group all have an immediate effect, whereas the zoom tool is something you select.
Suggestion 5: Agreed. Other tools that do not affect the canvas (like the color picker and the inspector) should be usable on locked layers too.

**Comment by Le2222** [comment]
About the changes in the icons (Suggestions 1 & 4), the icons lie under the GPLv3 license, wich says: 

> There are four freedoms that every user should have:
 ...

> the freedom to change the software to suit your needs,
 ...

> the freedom to share the changes you make.
(source: https://www.gnu.org/licenses/quick-guide-gplv3.en.html)

and, by the way, changes like this were made in the post #540
ps: I can submit them upstream but I don't know how to proper do it.

**Comment by Le2222** [comment]
As an artist I realized that it would be more interesting to recreate the icons instead of read and argue about thousands of license terms in a language that isn't even our native one. So here are the suggestion 1 and 4 icons with every single line recreated from the scratch. 

**Suggestion 1:** Mirror the 'fill tool' to let it facing the same direction of the 'fill tool cursor' and the same direction of the rest of the tools aswell.
![facing left fill](https://i.imgur.com/a5URS7m.png)


**Suggestion 4:** The 'Annotation' icon could have the letter A to let it's keyboard shortcut easier remembered ('A' also represents text in general because it's the first letter of the alphabet). Since the letter A is easier recognized as a letter (compared with T), we could waive the serif. 4 variations:
![4a](https://i.imgur.com/pJAovRJ.png)
![4b](https://i.imgur.com/sQanXi4.png)
![4c](https://i.imgur.com/FumLy0j.png)
![4d](https://i.imgur.com/0R8PGYb.png)

If approved they all are free to use without restrictions, without attribution or anything).

**Comment by callaa** [comment]
> As far as I understand, it's ok to change the icons if the modified ones lie under the same license (wich is 100% ok for me since I don't want anything back).

Yes, this is correct. GPL is the same license Drawpile itself is licensed under too.

>By the way, changes like this were previously made in the post #540.

I'm not so sure anymore if I should have. Now when I update the icons from upstream, I need to remember which ones were modified so I don't reset them back to the way they were.

I can submit your suggestions upstream to the Breeze issue tracker, if you wish.

**Comment by Le2222** [comment]
> I can submit your suggestions upstream to the Breeze issue tracker, if you wish.
Yes, please, thank you.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been moved to the Breeze icon set it seems, so closing it.
