### ISSUE TITLE
Missing Zoom Slider and simple Userlist

### ISSUE THREAD

**Issue by AltySquid** [drawpile/Drawpile#717]
Please bring back the Zoomslider the exact same way it used to be.
![chrome_r3sExvQbBS](https://user-images.githubusercontent.com/48969903/55040757-24eef780-502a-11e9-943f-90222b2e00ba.png)

The same way there is a simple implementation of the chat, there should be a simple version of the online userlist.
Here's a screenshot with short explanations on how l use my drawpile. l'm mostly using drawpile on a Wacom Mobile Studio Pro and don't want to rely on an onscreen keyboard to type in the amount of % l want to zoom in. 
![dp setup](https://user-images.githubusercontent.com/48969903/55041155-16a1db00-502c-11e9-960c-644bcba6d298.PNG)

**Comment by Le2222** [comment]
I miss the zoom slider too.

**Comment by erik90mx** [comment]
We have a zoom slider in the Navigator dock
![image](https://user-images.githubusercontent.com/3485891/55048231-13e3bd80-500d-11e9-9e37-4aec757fcafb.png)

Regards

**Comment by callaa** [comment]
You mentioned the virtual keyboard, so I assume a physical keyboard is not available and the Ctrl+lower stylus rocker zoom shortcut is not usable.

However, there are still many other ways to zoom, such as a pinch gesture if you have a touch screen, the zoom buttons in the toolbar and the slider in the navigator.

How are you using the user list? I'm trying to get an idea how it could be improved.

**Comment by Le2222** [comment]
Maybe show the basic profile 'on mouse over' could be a good way to save space in the users list?

**Comment by AltySquid** [comment]
Thanks for the rather quick feedback from you guys. There are a couple of things l'd also like to add: l usually operate my tablet with just one hand, therefore l don't like to use expresskeys or the scrolling wheel, especially 'cause l have other things mapped to those buttons already.
l know that there's a slider in the navigation dock. The thing is, you'd have to change some good musclememory whenever you have the navigator on the left side of the screen just to use the scrollbar.
Changing the docks from the left border to the right one, so l can add the navigator to the bottom right is a workaround that l'm trying to get used to. This way, l'll have the bar close to it's original spot. The problem here is that l have to get used to the new placements of all the other docks. Musclememory is being a problem here as well.
There definitely are workarounds to this, it's just sad to see a tool being removed that did its job nicely, especially if you've gotten so used to it
Here's my workaround setup
![dp workaround](https://user-images.githubusercontent.com/48969903/55106961-6e921d80-50d0-11e9-97be-cdcec990f088.png)

**Comment by erik90mx** [comment]
These are some cases when the user list is used:

- When you want to send a private message to a specific user, you need to select him/her in the user list to click the option.
- When a troll come in a session and starts messing up with the canvas, drawing everywhere or erasing, we need to select his/her user name as soon as possible to ban or kick (the new users are fetching in the bottom), so we will need to scroll down (meanwhile the troll is messing up with the canvas) and select him/her name to do the task.
- When you are in a session and wonder if a friend or a person that you know, is inside, you need to scroll over the user list to find a familiar name or recognize him/her avatar now. Is a normal case when you first arrive to a crowded server and you are wondering “is my friend here?”.
- Using the inspector tool gives us the user name that created a drawing (even if he/she is not currently connected), if you are wondering "is this user still inside the session?" you need to search in the user list.

The normal ways to search somebody in the user list when a session is crowded is:

- Positioning the cursos (with the pen tablet) in the user list's scroll bar (which is very difficult to manage due the hand pulse, when is in a little area) and scroll down.

- First scaling up the chat size, to get a better view of the user list (an a bigger user list's scroll bar), then scroll down to search through the users.

I didn't have issues with the user list's scroll bar size, when I had a 28 inches monitor to display, but right now I'm using a laptop with an average screen size, so the layout seems to be closer, that's why I have to take better advantage of the size of the canvas (every extra pixel counts). This is a reason I'm very interested in test out this:
https://github.com/drawpile/Drawpile/issues/707

Regards

**Comment by Le2222** [comment]
Add an extra dock just to get the zoom slider is bad for me I have a standard size laptop screen so I have the natigator dock hidden. Most keyboard shortcuts are handy when you're using a mouse but not when you're using the pen. I can't understand the downgrade of a feature when it's supposedly to be evolving (it was just perfect before).

**Comment by erik90mx** [comment]
Well I’m a Wacom pen tablet user (not a display user), so I use a keyboard along the tablet and this change doesn’t affect me at all to be honest, I feel very comfortable using the shortcuts in the keyboard, even my tablet has gestures enable to facilitate the task.

Different hardware has different necessities, and I understand the annoying if you are a Display user (you need access to almost all features using the pointer straightforward), but here Mr. Calle Laakkonen developed a solution that doesn’t affect a lot of users (btw I never used that slider at all), which is a normal decision when you are evolving a project like this one (also a lot of trying and error).

I know the main vendor of tablets world wide is Wacom, so I wanted to know how many possible users can have the same necessity, and I got this investor free info in the web page (first to know their main products)

![image](https://user-images.githubusercontent.com/3485891/55121193-f111e180-50be-11e9-9c56-89c0d579d7b8.png)
 
And here is a pie chart showing the sales of those products (to get an idea of what kind of user by probability can use the software)

![image](https://user-images.githubusercontent.com/3485891/55121203-fc650d00-50be-11e9-9da4-d874edbfec65.png)

So probably this change doesn’t affect a lot of users, but as you mentioned, the software needs to evolve, is there any other creative and simple way to make zoom in the canvas than bring back the slider? 

Like an opinion, for me will be great to get rid of that bottom bar (as I mentioned) to have more free space for the canvas section, but that’s my opinion. Let’s try to explore ideas in this issue tracking.

Regards

**Comment by erik90mx** [comment]
A good idea can be left the zoom in and out task just in the scope of the Zoom tool (and remove some redundancy in the layout), remarking that it is perfect selectable trough the tools menu.  

One very good way to solve this issue can be implement a feature in Photoshop called **Scrubby Zoom**, where the left-click and drag to the right is to zoom in, and drag to the left to zoom out (it even maintains the normal click to just zoom in a step forward)

Here you can found a better explanation of the process:
https://www.designeasy.co/2013/11/what-is-doing-scrubby-zoom-in-photoshop.html

And here you can see it working in a video:
https://www.youtube.com/watch?v=gVAonIw55Tc

Regards

**Comment by callaa** [comment]
The new layout (moving the sliders to the navigator) was in response to a user request. But now, given that I've heard nothing but complaints about it, I'm thinking I'll just have to revert that change.

**Comment by erik90mx** [comment]
> The new layout (moving the sliders to the navigator) was in response to a user request. But now, given that I've heard nothing but complaints about it, I'm thinking I'll just have to revert that change.

This is a very common topic in Open Source projects, or even in other kind of projects where more people is involve, the decision taken process is very hard to do, because the split of opinions. 

To get some usability facts about a user interface, some projects (a lot of them from private development) focus in numbers or other "tools" to take a decision regarding the UI and some features:

- Make user focus group, to hear the direct and real opinion of the final users (not just one opinion that speaks for everyone).
- Make pulls/surveys to know what people thinks about a topic or decision.
- Implement analytics to see the UI usage in numbers and know the real behavior (it will give you a real tracking to know if a tool in the UI is actually being used)

Right now Drawpile has a Facebook page with 434 members, maybe in this kind of issues might be a good idea to hear the community opinion (a quick pull with an open post to read opinions)

Just remember that even in a house, if you live with more people, to accommodate the TV or a furniture in a specific spot, will be very difficult to please everyone at the first time (some of them prefer right, others the left, and others doesn’t even want a TV)… so maybe you can end with another issue telling you again “remove the zoom slider”, but it is complete normal (the important thing is to learn how to proceed).

As I mentioned in other issue, I'm a real admirer of your work here Mr.Calla, what you are doing with this proyect is not an easy task, and I can even imagine that it might feel like "having another job" (I had some similar experiences before), let's take it easy and remember that we all love Drawpile, and want it to shine :)

Regards.

**Comment by beenyuk** [comment]
@callaa 
I think the sliders on navigator is convenient too, and close to the other morden painting software.
It's alway will has some different opinions about the new feature, also peopel need some time for getting used to it.
![Snipaste_2019-03-28_19-28-02](https://user-images.githubusercontent.com/48846565/55155605-c7c28580-5192-11e9-99bb-ac72233709e8.png)

And i make two mockups for navigator layout.
![Snipaste_2019-03-28_19-28-27](https://user-images.githubusercontent.com/48846565/55155611-cd1fd000-5192-11e9-9a75-b0b268af4bcf.png)

For now, maybe the best solution is has it both? 
(keep having the sliders on navigator, and add the sliders back on bottom.)

**Comment by sciicee** [comment]
Personally, i like the new navigator with the sliders! 
It's more easy for me zoom in & out, and overview the canvas at the same time. Thanks a lot! 
It seems fine if put the slider back to bottom right corner, but can we still have the sliders on navigator? Because I really like it.

**Comment by sciicee** [comment]
> The new layout (moving the sliders to the navigator) was in response to a user request. But now, given that I've heard nothing but complaints about it, I'm thinking I'll just have to revert that change.

Personally, i like the new navigator with the sliders!
It's more easy for me zoom in & out, and overview the canvas at the same time. Thanks a lot!
It seems fine if put the slider back to bottom right corner, but can we still have the sliders on navigator? Because I really like it.

**Comment by callaa** [comment]
Yes, it's possible to leave the sliders in the navigator, but if I'm putting the zoom slider back in the status bar, I'd rather remove it from the navigator then for two reasons: it's extra code to maintain for a redundant feature, and it takes up vertical space that's always in limited supply. I suppose I could leave just the zoom slider in and take out everything else (similar to the photoshop example.) I'm not sure if the rotation slider is very useful at all.

**Comment by erik90mx** [comment]
I agree to maintain the sliders in the navigator, and try to avoid redundancy:
 
![image](https://user-images.githubusercontent.com/3485891/55182919-4fd56a80-5154-11e9-97ec-59e387ae32c1.png)

I really like this mockup, because it arranges the sliders in a horizontal way, leaving us with more visible area of the canvas.
 
![image](https://user-images.githubusercontent.com/3485891/55182926-549a1e80-5154-11e9-9128-867d21e1e88b.png)

Just 2 days ago, a user asked me “how I rotate the canvas”, and I ended up giving the shortcut CONTROL + SPACEBAR and drag with left click. I don’t remember if the Navigator dock is in the default layout when you first install de application, but that user was new and didn’t saw it, but he/she need it for drawing. 

Regards

**Comment by Le2222** [comment]
About the rotation slider, my personal opinion, as a non-professional artist:

Its harder to do lines in some angles, so in traditional art some newbies usually rotate the paper to draw them easier... This is a "hack" or even "cheating" to do it the easiest way but... if your art professor see you doing that, hes probably going to fix your paper on the table with a 'scotch tape' forcing you to learn how to draw lines in every angle without to rotate in paper.

With that in mind, even when I know it would be easier to rotate and do a line in a certain angle, I refuse to rotate the canvas to improve my progress as an artist. My professors are not here but i remember and respect their advice to avoid this 'hack'.

**Comment by beenyuk** [comment]
@callaa 
> I suppose I could leave just the zoom slider in and take out everything else (similar to the photoshop example.) I'm not sure if the rotation slider is very useful at all.

It sounds nice!  

As to me, i don't use rotation slider often, mostly just zoom slider and mirror. Besides the basic zoom tool, i want to add one more tool of mirror. It's a very useful tool for user overview their works while drawing! 

Here is a quick mockup with your idea：with zoom slider and ps style.
![Snipaste_2019-03-29_02-24-00](https://user-images.githubusercontent.com/48846565/55184040-25bf8f00-51cc-11e9-8858-a84984268b9e.png)

**Comment by Le2222** [comment]
If you play with the 'zoom tool' time enought you'll realize that it often gets stuck in the 150% when youre right clicking do decrease the zoom and it dont get lower than that no matter how many times you do a right click. It's a minor issue, since if you keep playing with it like slecting an area, increasing the zoom, etc, it will eventually work properly again, but it's still an issue.

**Comment by callaa** [comment]
I've now reverted most of the changes to to the status bar.
