### ISSUE TITLE
watercolor brush acting strange

### ISSUE THREAD

**Issue by WinterVermillion** [drawpile/Drawpile#728]
this is more of just a small issue, but the blending or watercolor brush (the brush with the droplet on the icon) doesn't work the same as it did before, I use it for blending, and in previous versions it worked perfectly, and now it doesn't blend right, its all splotchy and uneven. and I used to use this brush for blending hair (brush settings in the image), and when blending with that in older versions it would blend really but show the strokes, and now it just smudges
 it around a bit without actually blending it right. it's not the worst problem in the world cause I still have the old version I can use for blending and all, but it would be nice if this little issue was fixable, other then that the program is great and is still my favorite drawing program to use in general. (example of the brush differences in the image linked)![brush comparison](https://user-images.githubusercontent.com/47613282/55296500-4e23d500-53e8-11e9-902b-4f8a8c6dfb97.PNG)

**Comment by callaa** [comment]
I assume the previous version you're using is version 2.0.something, and will write the following under that assumption.

There is an architectural change in version 2.1 that affects how the watercolor brush works. It's not really something that can be fixed, and arguably, the way it works now is more correct.

The watercolor brush works like this: every n:th dab (controlled by the color pickup slider) the canvas color is sampled and mixed with the brush color. The amount of mixing is controlled by the smudging slider.

In the old version, dabs were drawn immediately after sampling the color. When your smudging is 100%, pickup 1/1 and spacing 1%, this means the effective smudging is actually very low, since most of what is picked up is actually the color of the previous dab!

In the new version, the dabs are not drawn until (at least) the whole line segment has already been sampled. This means that the brush now picks up much more of the original color. As far as I can tell from reading the code, this is how the color pickup mode works in MyPaint, from which I originally copied this feature, and the way it was meant to work.

So, I believe you can still achieve a similar result as before by decreasing your color pickup interval and/or lowering your smudging strength.
