### ISSUE TITLE
Improve the watercolor mode

### ISSUE THREAD

**Issue by sciicee** [drawpile/Drawpile#732]
![Snipaste_2019-04-02_07-15-13](https://user-images.githubusercontent.com/49031545/55365247-65f97700-5516-11e9-9925-c60d73b58776.png)

As i know , drawpile got some inspirations from opencanvas 1.1. Seems like there are much commons between drawpile and opencanvas 1.1.
In opencanvas1.1, people can create a smudge brush without color value by using three sliders under watercolor mode, so people can use it as a smudge tool.
The situation in drawpile, we only can create a similar smudge brush with color value, which it's more like a brush than a smudge tool.

Currently，there is no actual smudge tool in drawpile yet, but it will be nice if we can achieve it by using the watercolor mode create a highly similar smudge brush as smudge tool. Since we have some sliders in drawpile's watercolor mode already. I wondering that do we have the same function slider in drawpile?
If yes, why we can't create a smudge tool by using drawpile's watercolor mode like the way in opencanvas 1.1?
If no, is it possible for you make it happen?  Maybe adding something or increase the max smudging limit? 

Also i noticed the minimal value of color pickup only can be 1. Is there any reason make it can't be 0? Because it can be 0 in the other painting program.

**Comment by callaa** [comment]
I'm not sure how smudging works in openCanvas, but a real smudging tool works slightly differently. The watercolor brush simply picks up the average color under the brush from the canvas, but a smudge tool captures a small brush shaped image. This is much more difficult to implement.

However, I suppose it would be possible to add a mode where the brush has initially no color and gets it from the first point it touches.

The minimum color pickup value (or maximum, depending on whether you think of it as an interval or a frequency) is 1, because at 1/1 pickup rate, it samples the color at every dab. I don't know what the value means in other programs.

**Comment by sciicee** [comment]
> However, I suppose it would be possible to add a mode where the brush has initially no color and gets it from the first point it touches.

I don't know how it works like under the watercolor mode, but it sounds cool and nice! Please do it!
Thank you and i can't wait to have a try!

**Comment by callaa** [comment]
I added the new mode. It actually works with all brush types, not just the watercolor one.

**Comment by sciicee** [comment]
> I added the new mode. It actually works with all brush types, not just the watercolor one.

Thanks! 
Here is another issue, since the brush max size limit and max spacing limit both been increased , is it possible for you increased max smudging limit too?

**Comment by callaa** [comment]
Smudging can't go any higher than 100%, because at 100% the old brush color is entirely replaced by the sampled color. If it's not picking up enough color, try increasing the dab spacing.
