### ISSUE TITLE
SUBMIT to GALLERY feature in Drawpile client.

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#733]
Hi,

The idea comes up, while I was submitting this issue to the Drawpile web page issue tracking:
https://github.com/drawpile/website/issues/15

Maybe it is related to this issues too, in some way (I was thinking in them when I get the idea):
https://github.com/drawpile/Drawpile/issues/451 (The gallery idea begun)
https://github.com/drawpile/Drawpile/issues/714  (Because we can use the inspector in the future to get a user gallery info, besides is a custom tool created for Drawpile only, I don't know another painting software that has something similar)
https://github.com/drawpile/Drawpile/issues/726 (It is the social part, and the "don't leave Drawpile to still interacting with friends")

Currently if you want to share an image in the Drawpile Web page:
- You need to print screen.
- You need to crop the image to take only the part that you want to share.
- Or you can avoid those steps downloading a third party application to crop sections in a print screen.
- You need to save the resulting image in your file system.
- After that you need to access the web page (which involves minimize Drawpile, pausing what you were doing, and open a navigator): https://drawpile.net/
- Use one of this options to get into the gallery:
![image](https://user-images.githubusercontent.com/3485891/55377676-3f661c80-54d3-11e9-941c-ee3f231d21e3.png)
- Click the submit content button:
![image](https://user-images.githubusercontent.com/3485891/55377693-5ad12780-54d3-11e9-9e53-e9df27a6ba5e.png)
- Choose a file:
![image](https://user-images.githubusercontent.com/3485891/55377718-7a685000-54d3-11e9-89c6-07235be27131.png)
- Upload it:
![image](https://user-images.githubusercontent.com/3485891/55377775-c1eedc00-54d3-11e9-8cb9-779dfae76a2b.png)
- Fill this form and click the save and publish button:
![image](https://user-images.githubusercontent.com/3485891/55377822-ecd93000-54d3-11e9-94f6-5b45c9217890.png)

The idea is to have a "Submit to Gallery" feature inside the Drawpile client application, in order to:
- Reduce the time consumed in the task "upload an image to your gallery"
- Don't use external applications to share content from the canvas.
- Achieve more user adoption and usage of the gallery.
- Keep it simple to use.
- Don't leave the actual Drawpile user's dynamic paused to do this action. (chating, drawing with other person, watching someone drawing etc.)
- The joy to get to your Drawpile gallery and discover after a while "I did a lot of drawings", because you don't were focus in the actual action of upload content, just in "share" in a pair of clicks.
- Have a more strong merge/integration between the web application and the client application (sometimes I think people forget about it and its potential).

Regards

**Comment by Wade821** [comment]
Unfortunately, I don't think this will fly as an option due to concerns with European law of General Data Protection Regulation (GDPR). Since European citizens have a right to control their data and remove it at will, putting up art and dealing with requests to be compliant to remove art would not only be difficult, failing to abide by these rules could put Calle in financial ruin and destroy Drawpile as we know it. I'm not sure how it would apply to Drawpile given he isn't a business and doesn't collect money for it, but the fines for failing to comply are steep (4% of company revenue or $20 million, whatever is greater).  I'd watch the video below on it for more info. But unless we can get a more solid answer on how GDPR applies to Drawpile, I don't think this will become a reality. 

P.S. I hate the voice for this but I think it explains it pretty well in a short period of time. 
https://www.youtube.com/watch?v=GXIbbkNwBHA

**Comment by callaa** [comment]
I'm not sure if GDPR applies in this case, although there are other laws that do, I think.

However, I'm inclined to reject this request because I don't want to create any integrations that are specific to the drawpile.net website. (Yes, there is the list server and the user account registration, but other list servers can be added via the settings dialog and the user accounts are an opt-in feature that others can implement too.)
