### ISSUE TITLE
Please set server listing to drawpile.net as default instead of nearby

### ISSUE THREAD

**Issue by Nujiao** [drawpile/Drawpile#742]
Having it set to nearby as default is so difficult for people to understand how to join the server, also hiding Private servers by default makes it even worse. Hiding NSFW servers is fine I do agree, but Private servers not being default only creates more explanation to the person experiencing drawpile for the first time.

**Comment by callaa** [comment]
I feel having it default to the "Nearby" option is useful, because it lets people know that there are options there that can be changed. However, I do see that this might be confusing.

So, perhaps this dialog should be redesigned a little. Instead of having a dropdown box for selecting the list server, maybe results from all servers should be listed with little section headers separating them? This way, the use would not have to make a selection and the "Nearby" sessions would be more discoverable.

**Comment by callaa** [comment]
![new-joinlist](https://user-images.githubusercontent.com/464576/55826726-50d1a900-5b11-11e9-9d85-d221bfe8daf3.png)

Something like this perhaps?

**Comment by beenyuk** [comment]
> ![new-joinlist](https://user-images.githubusercontent.com/464576/55826726-50d1a900-5b11-11e9-9d85-d221bfe8daf3.png)
> 
> Something like this perhaps?

Here is my opinion about this:
![Snipaste_2019-04-12_00-57-31](https://user-images.githubusercontent.com/48846565/55976226-41dc2980-5cbe-11e9-8c3e-f1d9856c3254.png)

- 1&4: Unused space.
- 2: Not enough space for title, people barely can see what title is it.
- 3: Not enough height for join page, user used to can see more rooms at the same time. Also the list server is taking some space and making the inside box complex.
- 4: I think the three most important and necessary information is: title, users and owner.
About the server adress, because it'will showing on the bottom. So i think it's unnecessary showing it in two different place in the same page.


And here is my mock up:
![Snipaste_2019-04-12_01-20-47](https://user-images.githubusercontent.com/48846565/55977507-92a15180-5cc1-11e9-9f0d-d72a5f76475f.png)
![Snipaste_2019-04-12_01-22-23](https://user-images.githubusercontent.com/48846565/55977514-97660580-5cc1-11e9-8455-367a6d6b187a.png)

**Comment by callaa** [comment]
Thank you for the ideas.

Yes, moving the filter options to the same row as the filter input box looks good. That will free up some vertical space.

I'm not sure about removing the Server column. It wasn't originally there and I have a faint recollection there was a good reason I added it. Having a status column would be nice, though, as it would allow sorting.

The settings button I don't agree with. It's the same as the dropdown there is now, and brings back the problem this issue was about in the first place: what should be the default one. I like that "Nearby" is the default because it shows users that the option exists. I still think the tree view is the best solution to that.

**Comment by callaa** [comment]
![joindialog-mockup-2](https://user-images.githubusercontent.com/464576/55979978-19dbce80-5c9c-11e9-817e-2f9289534cb4.png)

Here's an updated mockup.
I moved the checkboxes and fixed the column widths.
I also realized the "closed" button was unnecessary, because whether a session is closed or not is not shown in these listings. (I suppose the idea was that there is no point in listing a closed session at all.)
So, the "status" column would not be very useful, since the only possible statuses are "open" or "has password" and there is already a filter for passworded sessions.

**Comment by beenyuk** [comment]
![Snipaste_2019-04-12_02-19-22](https://user-images.githubusercontent.com/48846565/55981567-92a54f80-5cc9-11e9-8e12-ee341b2ba7ed.png)

It looks much better now.
But still have some small issuses:

- 1. It's better make the upper lay out more compact by making the filter box more close to filter tags.

- 2. The whole join page is all using square shape now, which i think it's better has some circle shape.
And here is the mock up:
![Snipaste_2019-04-12_02-19-40](https://user-images.githubusercontent.com/48846565/55982048-9edddc80-5cca-11e9-80f8-b21eb7ffa039.png)


- 3. As i say "I think the three most important and necessary information is: title, users and owner."
We already have 5 column there, which kinda crowded now and fill with long sentence. Because the server column is trying fit the whole server address.

Personaly, i think the server column isn't that necessary, also user can check the server address via the bottom box by click the room title.

- 4. How can we knowing which room is NSFW room? Because i didn't see any icon or flag there yet.

- 5. Is the "nearby" option only showing when it's available？

**Comment by notfood** [comment]
No circle shaped for toggles please. That doesn't look like a toggle but a [radio](https://en.wikipedia.org/wiki/Radio_button) button (denotes options).

Another suggestion: Have a button to toggle the visibility of the whole thing, sometimes you just want to connect to a known address and you don't need the lists.

**Comment by callaa** [comment]
> It's better make the upper lay out more compact by making the filter box more close to filter tags.

Are you sure? I tried both and the one with a little space between looks a bit nicer to my eye. Less crowded.

> The whole join page is all using square shape now, maybe we can have some circle shape.

A circle means it's a radio button, not a checkbox, which means you can filter either by password or NSFW, but not both or neither.

> Personaly, i think the server column isn't that necessary

I asked on the Discord server and others would like to keep the server column. It lets you sort the sessions by server. Also, I think I now remember why I added it in the first place: there's a great deal of confusion among users about what is a server (for hosting) and what is a list server (and I don't blame them.) By having the server column there, it makes it more clear that the *list server* is not where the sessions are actually hosted.

> How can we knowing which room is NSFW room from the room title? Because i didn't see any icon or flag there yet.

Oh yeah, I had the filter on when I took the screenshot. It's the black blocky icon. I replaced the old red icon with the letters "NSFM" with it, mainly because I was using that icon for censored layers, so it's just one less icon to package. I realize it's not immediately obvious what the icon means, but neither was the old one.

> Is the "nearby" option only showing when it's available？

Yes. If you don't have Bonjour installed, that option won't show up.


>Another suggestion: Have a button to toggle the visibility of the whole thing, sometimes you just want to connect to a known address and you don't need the lists.

Yeah, I'd like to have this too. I just have to figure out a good place for it.

**Comment by callaa** [comment]
I'm releasing version 2.1.7 today and I decided to go with layout like in my last screenshot.

I also made it so the dialog now remembers its size. Making the window shorter now automatically hides the listing box.

**Comment by beenyuk** [comment]
> I'm releasing version 2.1.7 today and I decided to go with layout like in my last screenshot.
> 
> I also made it so the dialog now remembers its size. Making the window shorter now automatically hides the listing box.

![Snipaste_2019-04-13_20-41-05](https://user-images.githubusercontent.com/48846565/56079930-85a17100-5e2d-11e9-80e0-6d9a76b395fc.png)

After a quick test for 2.1.7, i think the join dialog is over compact.
The whole view kinda makes me feel intense, at least to me.

And here is my suggestion mockup:
![Snipaste_2019-04-13_20-46-56](https://user-images.githubusercontent.com/48846565/56080097-47a54c80-5e2f-11e9-8278-aee9c0623d95.png)

By the way, since  there isn't much change yet, don' you think it's a little bit early for releasing 2.1.7? Maybe you can make it as a pre-released version in case anyone needs it?

**Comment by callaa** [comment]
Yes, it's a bit early for 2.1.7, but I need to get it our early because it contains an import tablet fix for Windows users.
