### ISSUE TITLE
tiny short brush strokes, create max pressure dots

### ISSUE THREAD

**Issue by Nujiao** [drawpile/Drawpile#743]
Just like the title says, drawpile is preventing me from drawing extremely small

![761677 2019-04-06_13-48-21](https://user-images.githubusercontent.com/39990590/55699278-1690cc00-5998-11e9-886e-a36254097752.gif)

**Comment by erik90mx** [comment]
I recently saw some users with the same problem. They continue drawing and those dots are all over their continue strokes (I even experiences this 3 or 4 versions ago, when I tried to draw with low pressure and with fast brush strokes), some of users have few dots after several brush strokes, but I have seen some cases like the one that Nujiao is showing, where Drawpile gets unusable for them.

Regards

**Comment by callaa** [comment]
If you're using version 2.1.6, try this test build: https://drawpile.net/files/win/drawpile-2.1.6-tablettest.zip

**Comment by Wade821** [comment]
This issue should be fixed by now. Please respond with an update if you're using the newest version (2.1.10) so we can either close the issue or move forward with addressing it. 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed.

**Comment by notfood** [comment]
Stale, closing.
