### ISSUE TITLE
Continuing Animation

### ISSUE THREAD

**Issue by TheSeaFloorQueen** [drawpile/Drawpile#745]
I began an animation, then saved it as both an animated gif and an image slideshow. When I opened the animation to continue it on Drawpile, the onion skin made it purple, and I could not see my work. I also cannot find a way to import the images as separate layers. Could someone tell me how to continue my animation?

**Comment by callaa** [comment]
The best way is to save as an OpenRaster file, which preserves the layers.

What do you mean by onion skin making it purple?

**Comment by notfood** [comment]
It was all purple because all layers were white, there was no transparent pixels because it became a final GIF.

You don't save your work as GIF, GIF format is for final renders. If you want to save to continue later you **MUST** use ORA files.

To salvage your work you will have to open each frame and remove the white.
