### ISSUE TITLE
Crashes when I try to join.

### ISSUE THREAD

**Issue by Teeps-** [drawpile/Drawpile#763]
After the most recent update, I am unable to join my friends in drawpile, or any drawpile session for that matter. It will load in up until about 1/3 of the loading bar, and the navigation tab will glitch out and look like television-snow, and it will crash out. 

I have attempted to restart drawpile, my computer, and my internet, none of these work. 

I have also uninstalled DP 64 bit nd reinstalled it, to no avail. The same goes fr the 32 bit.

For now i am going to try and use the older version, but this is an issue pertaining only to the latest update.

**Comment by callaa** [comment]
If you can make a session recording that crashes Drawpile, that would help me figure out what causes it.

**Comment by bananapotsticker** [comment]
I'm having a similar issue, actually. Half the servers I try to join just crash.

**Comment by callaa** [comment]
How much RAM do you have and are you using the 32 bit version? There is a problem in 21.8 and 2.1.9 that causes excessive memory usage, especially when joining a big session. I'm releasing a new version that should fix that issue very soon.

**Comment by Wade821** [comment]
I believe this issue was resolved with the update to 2.1.10. Please respond if you've tried the update so we can close the issue or proceed accordingly. 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed.

**Comment by notfood** [comment]
Stale, no response from submitter, closing.
