### ISSUE TITLE
Issue #568 still present?

### ISSUE THREAD

**Issue by Topodic** [drawpile/Drawpile#766]
Hello. My friend and I both seem to be running into this jagged line issue. The latest info I could find on this was that it was reported fixed in 2.0.10 but it seems to be occurring once more. I've tried the various settings for Windows Ink and the relative mouse setting but in any instance it still seems to be present.
![drawpile_Qk6rki9fXu](https://user-images.githubusercontent.com/43795565/58395292-481f2e80-7ffc-11e9-96c9-8a91216e2c72.png)

**Comment by Nujiao** [comment]
try upping the smoothing in the input tab, if its not find-able click VIEW > DOCKS > INPUT and the window will be find-able.

**Comment by Topodic** [comment]
Appreciate the tip. I do know about the smoothing feature, but it's not something I'd prefer to use all the time. It does help as a temporary workaround, but it's still affected by this when zoomed out as well as not working too well with slower strokes.

**Comment by Wade821** [comment]
Well, which mode do you get pen pressure in? Windows Ink on or off? And if it's off, have you tried the Wintab hack? What brand of tablet do you have? Do you have issues with smooth lines in just Drawpile or all programs? 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings.

**Comment by Drawfriend** [comment]
It's the problem i had with Drawpile since always (i don't really remember with which version i started using, but let's say 1.0.0 since i definitely was using Drawpile since then)

my lines in GIMP (2.10), disabled line smoothing/stabilizer
![image](https://user-images.githubusercontent.com/18752607/60545566-a9cd6980-9d1b-11e9-9561-1cfab55a8355.png)
(similiar results in Krita, so it's probably not a Qt issue)

my lines in some online drawing program that probably does not use line smoothing ( https://galactic.ink/sketchpad/ )
![image](https://user-images.githubusercontent.com/18752607/60545689-ea2ce780-9d1b-11e9-8b51-6c80d227c426.png)

and finally my lines in Drawpile (2.1.11) with line smoothing cranked to 0
![image](https://user-images.githubusercontent.com/18752607/60545783-2f511980-9d1c-11e9-8a7e-ad8d91cf2118.png)

I know can up the smoothing, but i consider it a temporary workaround and not a real solution. It gets annoying when i try to draw the details and it's just more comfortable to have more control of the line. I'm using Wacom Intuos 4 on Linux with up-to-date drivers.

**Comment by Wade821** [comment]
@Drawfriend I'm not too sure about Linux's implementation of how the tablet works exactly. At least in Windows, there's Wintab and Windows Ink. The reason I mention this is that wintab apparently uses the mouse cursor as its positioning system, which is less accurate than the coordinates the tablet can provide. When I was talking with some Krita developers in [this thread here](https://bugs.kde.org/show_bug.cgi?id=383407), Callaa had jumped on board and discovered something interesting.

> Looks like there was a good reason the mouse mode hack was left out of Krita. If the tablet coordinates are offset from the mouse coordinates so that the offset is very close to the m_absoluteRange threshold, it will result in random jagged lines being drawn when the threshold is crossed.

This, I feel, sometimes is responsible for the issues users are facing. I also know that some other programs will hijack the tablet and impose their own stabilizer system which cannot be turned off (Paint Tool Sai in Windows).  But without knowing the more detailed specifics of how the tablet works, I'm not sure what to do with your problem. In Windows, there is an option to turn it off and I know in Linux, there is no such option (picture below). Wish I could do more, but I just don't have a Linux system to really try myself besides a Raspberry Pi, and wanted to give you some information that might help enlighten you. I may look into this further when I can set up a virtual machine with Linux to try some things out. 

![image](https://user-images.githubusercontent.com/18544575/60549539-0dcf3e00-9cda-11e9-81a6-639aec0964fb.png)

The funny thing is, Calla doesn't have much knowledge in the way of Windows API development from my discussions with him. This means that the code used for tablet support is actually a mixture of info pulled from QT and Krita's code base. I would thus assume that the same is true of Linux and Mac operating systems in terms of where the support is pulled for tablets. 

Anyway, I was asking @Topodic for that information even though they said they've tried both, because I need to know what settings they use normally. I myself, being the pain in the butt that I am about using mouse/wintab mode, have noticed some weird issues and noticed patterns that may be able to fix them. However, I can't do that though without knowing specifics of their setup. If the option Windows Ink is enabled in Drawpile, "Enable relative pen mode hack (Wintab only)" should not be enabled. The same is true in reverse, if "Enable relative pen mode hack (Wintab only)" is enabled, Windows Ink should not be enabled. These settings are completely different from one another.
