### ISSUE TITLE
Alternative color wheel and condensed chat

### ISSUE THREAD

**Issue by Nujiao** [drawpile/Drawpile#768]
1. Add an alterative color wheel that is in the settings or the color window as a tab and it looks like the photoshop color wheel? (this is drawpile vs photoshops at smallest size)
![image](https://user-images.githubusercontent.com/39990590/58698451-4ee5d280-8369-11e9-9f21-5938408f6f46.png).

2. Can you make a more condensed and squeezed version of the chat, the normal chat has an extreme amount of empty space. Is it possible to make it like the second image.
![image](https://user-images.githubusercontent.com/39990590/58700182-632bce80-836d-11e9-8fda-87ac117eecb4.png)

**Comment by callaa** [comment]
The chat box is a bit difficult, because the widget I'm using to render it supports only a very small subset of HTML and CSS, so the amount of styling I can do is quite limited. You can enable a compact mode by right clicking it that makes it look the way it looked in 2.0.

**Comment by Wade821** [comment]
Since dock space can be sometimes limited for people with smaller screens, I would also suggest a sort of hover color selection pop up set via shortcut key. In photoshop, this is done by doing Alt + Shift + Right click and holding the right click. A small color dialogue appears, positioned by the mouse cursor. You first move to the hue bar to select an appropriate hue and then hover over the desired color. Releasing one of the keys and/or right click sets the color for immediate use, as illustrated in this video (it's in Spanish).
https://youtu.be/aGpGjSnZg3k?t=35

In photoshop, the type of color select which appears can be configured to several different styles, so if it gets to be nearly screen sized, it is just centered in the screen. It'd provide a neat way to select colors, and useful for users that have tablets which can program shortcuts into a tablet button in order to simplify the process. 

Another example here:
![image](https://user-images.githubusercontent.com/18544575/59671680-ec674180-9172-11e9-8f72-a3e65f280028.png)

**Comment by askmeaboutlo0m** [comment]
Split into #1208 for the chat and #1210 for the color wheel, so that these features are more visible individually and maybe are more likely to get worked on.
