### ISSUE TITLE
in-progress transformation is treated as committed and applied to wrong layer

### ISSUE THREAD

**Issue by deliciouslytyped** [drawpile/Drawpile#778]
I ..think I figured out how to reproduce this?:
Is this a bug or just nonintuitive behavior? I feel like there could be multiple things wrong at once here.

1) draw a grid, horizontal lines on one layer, vertical on another
2) go to the horizontal layer
3) make a selection and drag it somewhere on the grid (make sure its not aligned so you can see changes), do not cancel or commit the move. you will have some pieces of misaligned horizontal lines.
4) change to the vertical layer, do not cancel or commit the move
5) do not cancel or commit the move, just click outside (I'm not sure if this is supposed to be a cancel or a commit or what)
6) the preview showed the moved horizontal lines, but after step 5 you now see the committed result of moving vertical lines.

**Comment by deliciouslytyped** [comment]
I'm guessing the problem is basically that the transformation looks at the current layer, not the originating layer. I'm not sure committing a transformation when you click outside is the most correct behavior either.  The question also comes up of whether an operation like this should be considered a move between layers, but probably not - or at least it would probably lead to a lot of foot shooting.

**Comment by callaa** [comment]
Confirmed. This is what causes the problem:

When you make a selection, a selection object is created. The source layer ID is not stored in the selection object. Originally, this was fine, because the selection buffer did not need to reference the source layer at all. However, in version 2.0, I added new command for moving and transforming layer content. This was to optimize the common use case of simply transforming a selection without using cut/copy & paste.

Now, the problem is that the client sends the MoveRegion command, which includes the target layer ID, but the selection object does not contain the source layer ID, so the currently selected layer is used. Usually, these are the same, but when they're not, it leads to that unexpected result that the transformation that was supposed to be applied to the original layer is applied to the newly selected layer.

This should be easy to fix, I just need to add the source layer ID to the selection object.
