### ISSUE TITLE
Docked items/Navigator refuse to stay the same size

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#783]
Using Windows 10. 1920x1080 resolution laptop with 125% size difference (text, apps, and other items).

With every new window of Drawpile I open, it always reverts to Navigator shrinking to the most minimal size, so I would need to drag it down and fix the other dock items every time I open/use a new window (even with them locked). I have a feeling it's the size difference, but I'm not sure. It's been happening ever since I started using it.
![Screenshot_2](https://user-images.githubusercontent.com/51433534/59641020-d2971180-9114-11e9-9f90-70d79ab0b9a2.png)

**Comment by Wade821** [comment]
This is somewhat similar to issue #755. However, it isn't entirely either. I believe that this is an issue by design, as changes to the docks in terms of layout and settings are not saved until the last Drawpile Window that is opened is closed. So if you're leaving open Drawpile windows open and never closing them all, it might explain some of the issue you're seeing.

When I have more time later tonight, I'll test it myself later by altering the scaling to 125%. I'll get back to you as soon as I can.

**Comment by Wade821** [comment]
Alright, so I had a chance to review your issue. It has nothing to do with the scaling on your display, the same behavior occurs whether or not using scaled mode. 

This is actually an intentional design feature and not a bug. The reason being is that the freehand dock must always have a certain amount of space when Drawpile is opened, because the freehand dock does not have a scroll bar to go down. Even though the round brush setting is selected and doesn't take that much space vertically (as you can see you have space in there to adjust your docks), the watercolor brush does have more sliders to adjust. As such, Drawpile opens with the assumption that the Freehand dock must always be this size, in order to accommodate all brush settings to keep them visible. If we set it to a lower value than the max, you might have an issue where the waterbrush color settings weren't visible to even be adjusted. So what now? We might be able to make improvements to the way Drawpile handles some of the docks in order to improve it's usability, though I'll discuss that later. 

For now, you may want to try having the navigator below the freehand dock and try making your color selection dock smaller. Or perhaps decide to merge some docks together if that's an acceptable trade off for you. 

**For improvements, here's a few ideas.** 

1. Make a smaller option for the color picker, as noted here in issue #768 ... please feel free to comment on it if you like the idea or have other possible options to display for color selection. I'll be making a possible idea to reference here as well in a bit. 

2. Create an option in Drawpile for a minimum size to set the navigator to by the number of pixels tall one wishes to keep it. This helps keep it within a somewhat reasonable limit, as of course at that size as displayed in your screenshot, it becomes rather useless. 

3. Callaa has gotten some feedback for a dockerized chat and/or users list, so that could be moved around. Functionally, it would make sense that possibly some dock could be moved down to the bottom so it'd make the chat box a bit smaller but keep more docks visible. This might be a great way to have more options for placement!

4. Re-arrange the freehand dock perhaps a bit like this... with a new button that says "More Settings". I'd probably end up conducting a survey on the Official Drawpile Discord, but the idea is to move less commonly used settings into that area that would appear as a pop up menu when clicked. For the water brush, that might be things like smudging and color pickup. Personally, I think a lot of the pressure variable items for the pen can be put under there too, as I don't think most people would mess with those settings much once they're configured. This could also be used for additional settings people may want to configure, such as minimum diameter and max diameter, and so forth. 
![image](https://user-images.githubusercontent.com/18544575/59670508-ec664200-9170-11e9-98fb-0a9115e0ef7a.png)

**Comment by notfood** [comment]
Is this still an issue?

**Comment by Wade821** [comment]
This is still an issue, I can reproduce the bug.

**Comment by Wade821** [comment]
Oh, right, nevermind. There is an issue open for this already. Woops.
