### ISSUE TITLE
An example for "salted hash" user password please.

### ISSUE THREAD

**Issue by Lovewyrm** [drawpile/Drawpile#787]
I'm too much of a brainlet to get this, apparently.

I just want this stupid thing to work without giving myself six million deep vein thromboses because I have to sit on my ass for a quintillion years painstakingly fiddling with "sha1sum" BS which I don't even know is right.

GIVE ME AN EXAMPLE AAHHH.
Edit: I mean the 
[users]
saltyuser:s+sha1;DEADBEEF;SOMEBULLSHIT:MOD,HOST

Thing.
C'mon, mannnnn. I don't want no fancy ass third party auth, just something for my friends that isn't plaintext, dude. Bro. Dudebro. Plz. Man, come on, man. Plz. Don't do me dirty like this, man.

**Comment by Wade821** [comment]
**Note:** RIP, I'm too slow. Good to hear. 

I can't help much, given that my Drawpile server is set up with the database file instead of the configuration text file. I also don't know that I'd worry about keeping user passwords in a SHA1 format, given that the end users can save their password to their computer which is in a plain text format as it currently stands, and SHA1 isn't hard to reverse into plain text. We'll give it a shot though, just forgive me if I don't have the idea right. I'm busy and don't have time to properly test out this response, unfortunately.

At first glance it seems you're already using the correct format, if I was to take a guess based [on this page](https://drawpile.net/help/server/) under the [users] section. It states the correct format is `username:password:FLAGS`. You [can generate a SHA1 sum ](https://stackoverflow.com/questions/15626073/sha1-password-hash-linux)with the following command in a Linux terminal (I'm using Raspbian for Raspberry Pi currently), `echo -n "DEADBEEF" | sha1sum | awk '{print $1}'` which generates `a837eb90d815a852f68f56f70b1b3fab24c46c84`.  The `| awk '{print $1}'` is appended to the end to avoid the dash output that is generated by using the first two. Now if we're going to talk about salt, there's some issues there to consider.

[All a salt is in terms of hashing](https://crackstation.net/hashing-security.htm), is an element of randomness in order to secure the password. So you could repeat the earlier command with a random string, perhaps `echo -n "DEADBEEFSOMEBULLSHIT" | sha1sum | awk '{print $1}'`... which generates `4af45b39cf6d0a1b06a6ec135df64e50dfbdc7d9`. 

So your earlier example of 
`saltyuser:s+sha1;DEADBEEF;SOMEBULLSHIT:MOD,HOST`

Becomes
`saltyuser:s+sha1;a837eb90d815a852f68f56f70b1b3fab24c46c84;4af45b39cf6d0a1b06a6ec135df64e50dfbdc7d9:MOD,HOST`

Please see if that works and let me know. I'm curious. :)

**Comment by Lovewyrm** [comment]
Yeah, it works, thanks for the response, even if I spotted the mistake before you finished. 
This will most likely be indexed by google and your in depth answer shows the process, well, in depth.

I was doubting my sanity for a while though, whew. Funny how computer stuff can do that sometimes.
That sheer helpless confusion when one thinks "this should work, damnit!" but it doesn't...hehe.

**Comment by Wade821** [comment]
No problem, been there and felt the same way. Glad you got it figured out.
