### ISSUE TITLE
Selection scales when you select outside canvas

### ISSUE THREAD

**Issue by Drawfriend** [drawpile/Drawpile#788]
How to reproduce:
- Select area including area outside canvas
- Drag selection

Result:
Selection gets scaled and stretched

I think right now when someone selects 300x300 area, but the data is only 200x300 (with remaining 100x300 outside of canvas) when you drag it to move, the 200x300 area gets stretched to fill 300x300 (because that's the size of the selection)

Expected
Selection of the same scale as selected area, excluding area outside of canvas

**Comment by Wade821** [comment]
Tested in Drawpile 2.1.11, verified the bug is reproducible. 

The stretch occurs in the direction for the side of the canvas the selection over bounds... so if the selection was made on the right or left of the canvas, the stretching occurs horizontally. If the selection was made on the top or bottom of the canvas area, then the stretching is vertical. If the selection occurs on multiple edges, then it is stretched in both directions.

**Comment by callaa** [comment]
This is now fixed in the dev version (will be included in the next release.)
When creating a selection, the selection will be clipped to the canvas, preventing this problem from occurring.
