### ISSUE TITLE
Session is closed message when trying to join a room

### ISSUE THREAD

**Issue by enigmatic8** [drawpile/Drawpile#792]
I'm trying to join a room on drawpile, and when I click on the "ok" after it shows me my screen name, it says "Could not connect to server Session is closed!" 
I went back to try entering again, and the same thing happened. If anyone knows how to fix this please let me know!

**Comment by callaa** [comment]
If you're connecting with a session URL (the long address with the session ID after the server name,) then the most likely cause is that the session is indeed closed (not accepting any new users.) Try connecting to the server with just the server name (e.g. `drawpile.net` instead of `drawpile://drawpile.net/xxxxxxxxxxxx`. You should then see a list of active sessions. If the session is greyed out, it's closed.

**Comment by notfood** [comment]
Stale, no response from submitter, closing.
