### ISSUE TITLE
Can no longer join friend's room/they can't join mine

### ISSUE THREAD

**Issue by clowntowne** [drawpile/Drawpile#793]
Hello,
I have read thread after thread, official guides and other things on server hosting, joining servers, etc. For a while it worked, me and a friend (from another state) were able to join each other's rooms and draw using LogMeIn Hamachi and it worked great, but then suddenly one day neither of us could join either room. It would load for a painfully long time until it finally said something along the lines of "couldn't connect to room" or something like that, and I can't figure out what happened :(. Does anybody have any idea what happened, and how we might fix this? Want to see if we can get it working tonight again.... thanks!

**Comment by Wade821** [comment]
Hello! I'm happy to help you out with your issue, but unfortunately I don't have enough information about your connection situation to offer any possible solutions yet, so I'll open up with a few questions for you.

When a room is being hosted, are you hosting using the "This Computer" or "Built In" option? Or are you using "Remote:"? If using "Remote:", what server are you using to host (examples include: drawpile.net, syntheticdreams.net, etc...)? 

Also, please verify which version you are using of Drawpile under Help, About Drawpile (most recent version is Drawpile 2.1.11). While this shouldn't be a version issue with your particular problem, I suggest you verify both are up to date as this may fix other issues you've experienced as well. This also provides a new version of the server client starting in Drawpile 2.1.9 for Built in/This Computer sessions that no longer requires session resets. 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Comment by clowntowne** [comment]
> Hello! I'm happy to help you out with your issue, but unfortunately I don't have enough information about your connection situation to offer any possible solutions yet, so I'll open up with a few questions for you.
> 
> When a room is being hosted, are you hosting using the "This Computer" or "Built In" option? Or are you using "Remote:"? If using "Remote:", what server are you using to host (examples include: drawpile.net, syntheticdreams.net, etc...)?
> 
> Also, please verify which version you are using of Drawpile under Help, About Drawpile (most recent version is Drawpile 2.1.11). While this shouldn't be a version issue with your particular problem, I suggest you verify both are up to date as this may fix other issues you've experienced as well. This also provides a new version of the server client starting in Drawpile 2.1.9 for Built in/This Computer sessions that no longer requires session resets.
> 
> _**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.


Hi there-- I use the "This Computer" option and have it listed at drawpile.net as public, but I always put a password on it and give it to my friend. And I am using version 2.1.11! I am not sure if I always was, but just in case, a few days ago I uninstalled Drawpile and reinstalled it to make sure. I will be checking later if my friend can do the same or check their version.
I usually start sessions by opening LogMeIn Hamachi and having my friend open it as well, as we area already connected in a server there together which I guess links our computer networks or something. I'm not an expert on server stuff so I never really know haha, but once that's up, I will make a Drawpile server with the settings I mentioned, and give my friend my IP address to type in or the url that you find at the bottom right of the room. She enters that, and the server password, her username, but after loading for a while now we get the connection error, even when I try joining her room.

**Comment by Wade821** [comment]
Using the "This Computer" option is great, but it has limitations. Namely that when used, the session is only up as long as the person who hosted the session is there... the moment they leave, everyone is forced to leave. Secondly, using LogMeIn Hamachi is completely unnecessary, provided you forward the ports to your computer when hosting. It only becomes necessary if you don't know how to do that. 

The short story is to simply figure out your computer's MAC address, go to your router's configuration page, set up a DHCP IP reservation for your MAC address and IP address, and then set the IP address to receive a forwarded port (27750). By doing this, you can be assured you can host Drawpile sessions from your computer. 

The cases in which this may not work is if you are behind a firewall or carrier grade NAT (Network Address Translation, used because IPv4 is completely saturated by devices accessing the internet and we need to desperately switch to IPv6). Some universities and businesses have such things in place to prevent connections in order to reduce bandwidth usage. 

Anyway, I'm not super familiar with LogMeIn Hamachi so I'd rather not troubleshoot that particular setup. If you wanted to continue trying to set it up this way with the Built in option, a call via Discord with voice and video would probably be best for me to walk you through the process. If not, there may be an easier option for you.

Simply host by going to "Remote:". Do not use LogMeIn Hamachi. Type in, without quotes, "drawpile.net" and fill out the other information as desired. You can elect to make it a private session with a password or set it with a room code instead of publicly listing it. This scenario should work most times, unless there are too many sessions being hosted on Drawpile.net... so that's why using the Built in session can be advantageous... or you can simply use another server which allows public sessions to be hosted (syntheticdreams.net is one of them). 

Please let me know which way you want to go with this.

**Comment by Wade821** [comment]
I realize that my earlier question was a tad sleep deprived, given that using LogMeIn Hamachi is for local network connections so it would be "This Computer". But I wanted to make sure. :)

**Comment by callaa** [comment]
You can check the log file (via help menu) to see more details. From your description, it sounds like the other side is not responding at all, so you eventually get a timeout. This is typically caused by a firewall application (either Windows' built-in, or a separate one.)

**Comment by notfood** [comment]
Very likely connectivity issues. If you're still experiencing this issue, feel free to reopen it.

Stale, support request, closing.
