### ISSUE TITLE
pressure sensitivity won't work

### ISSUE THREAD

**Issue by AzureSkiesEmma** [drawpile/Drawpile#794]
i've tried all of the other fixes i've seen (i disabled and enabled windows ink and restarted, i fiddled with settings that indicated pressure fixes, etc) and i still can't get drawpile to register any pressure
it does not register in the tablet testing screen, nor on the canvas

these are the logs i receive upon opening the app:
![Screenshot (181)](https://user-images.githubusercontent.com/53626792/62398045-77f43080-b56f-11e9-84ff-63b2fd82864b.png)

my tablet is always plugged in so there are no issues with plugging in after opening the app
are there any other solutions i may have missed?

**Comment by Wade821** [comment]
Hello! It seems you might have a problem with the driver installation as I was [reading here in this reddit thread](https://www.reddit.com/r/krita/comments/aac7sp/help_with_pressure_sensitivity/), which indicated that if the Wacom Desktop Center doesn't see your tablet (assuming you have a wacom), that there's something wrong with the driver itself. Take a look into updating your tablet driver accordingly.

I would also try drawing in other applications that you know are pressure sensitive and see if you can get it to work there. If you don't have any other applications, Krita and GIMP also work with pen pressure, and I've got a nifty installer you can [download here from Ninite](https://ninite.com/gimp-krita/) that will automatically install them easily!

Also, please verify you're using the latest version of Drawpile by going to help, about Drawpile and verifying the number in your program matches 2.1.11! There have been a lot of changes so if you haven't updated in the last couple of weeks or months, there may be an update available for you as well.

And you're right as far as messing with Windows Ink. However, your tablet settings need to match Drawpile settings. In that if you have Windows Ink on in your tablet configuration, it should be on in Drawpile. If it's off in your tablet, it needs to be off in Drawpile. Even if you're using your tablet in mouse mode, the setting under "pen mode" will affect how your tablet functions! Please verify what your tablet is configured to use via the software!
![image](https://user-images.githubusercontent.com/18544575/62404668-c93df900-b54a-11e9-9341-ed2364a83702.png)


_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.

**Comment by AzureSkiesEmma** [comment]
hey! thanks for the help
i don't believe i have a wacom tablet, and my pressure sensitivity works well inside programs like clip studio paint
i downloaded drawpile the same day i created the post and it does appear to be running on version 2.1.11! 
my device appears to automatically be running windows ink (it's a screen tablet and so is registered by the computer as a second screen as well as a tablet); i'd have to look into finding out how to disable if if that would be a necessity - however, drawpile does not work when it is set in an on nor off state when i change the settings within the program

**Comment by Wade821** [comment]
No problem. As far as your tablet is concerned, we shouldn't need to disable windows ink. It's newer and more accurate than the older Wintab so if that's what you're using already, lets keep it that way.

Do you happen to have Windows 10? If so, please hit the Windows key on your keyboard and the letter R. Then type in "winver" (without quotes) and hit enter. Please verify which version of Windows 10 you are using. In particular, I've now had two users of Windows 10 version 1803 who had problems with pen pressure (Windows Ink and the older Wintab mode) who resolved the problem by updating Windows to version 1903. It was a bit of a strange issue because the first user reported that everything would pan instead of drawing in any program, while the other could draw in other programs with pressure but not in Drawpile.

You can try to update it a few different ways. Make a shortcut on your desktop by right clicking, go to new, and shortcut. Type in *ms-settings:windowsupdate* in the box, hit next, type in "Windows Update" for the name, and next/complete. Double click your new shortcut to run it and check for updates.

You can also try to force the upgrade via the upgrade tool. Main website here: https://www.microsoft.com/en-us/software-download/windows10 ... Update Tool is the first blue box to click there with "Update now". Follow the on screen prompts. 

You may however, get a message about not being able to update because your drivers are out of date, specifically it seems the Intel Rapid Storage Technology Driver has delayed some computers from updating. You can attempt to get driver updates directly from Intel if you have an Intel based processor, or look driver updates by your computer's mode. Use the Windows key + r, type in *msinfo32* and hit enter. You should see some model information in there for which you can use to then search up applicable drivers from the manufacturer of your computer.

**Comment by erik90mx** [comment]
Hi,
Same issue here.
**OS:** Windows 8.1 64 bits
**Tablet:** Wacom Intuos CTL-4100WL
**Driver:** “WacomTablet_6.3.35-3”

The Windows Ink option is disabled:
 
![image](https://user-images.githubusercontent.com/3485891/63076732-d3bda280-befb-11e9-9226-fc9ae7be4190.png)


The sensitivity is working fine in Krita 4.2.5
This is the log from Drawpile 2.1.11

 
![image](https://user-images.githubusercontent.com/3485891/63076745-dd470a80-befb-11e9-96ba-561916bda0bf.png)

I attach the log file:
[drawpile-2.1.11-2019-08-15.log](https://github.com/drawpile/Drawpile/files/3504498/drawpile-2.1.11-2019-08-15.log)

When I use the Table Tester in Drawpile, it seems to be working fine.
 
![image](https://user-images.githubusercontent.com/3485891/63076752-e20bbe80-befb-11e9-84c6-ebed4fb3023b.png)

These are my preferences

![image](https://user-images.githubusercontent.com/3485891/63076802-049dd780-befc-11e9-8d33-99c85f9085d1.png)

Regards

**Comment by Wade821** [comment]
@erik90mx In the Freehand dock (which should be in the upper right corner of Drawpile, you may have to click a tab that says freehand to do so),  you should have at least one box checked under the pressure option as depicted below. How many options are available to you depend on the brush type you're using.

Given what you've described so far, it should be working so we'll check this first!

![image](https://user-images.githubusercontent.com/18544575/63101864-cff74380-bf2e-11e9-9bad-64f3ec643b66.png)

**Comment by callaa** [comment]
If pressure works in the tablet tester, the problem is most likely in the brush or tool settings. As Wade821 pointed out, make sure you have the pressure checkboxes checked. Also check that in the "Input" dock, the pressure source is set to "stylus", rather than "distance" or "velocity".

One other thing to try is that if you've updated from an older version, certain settings might be invisibly out of sync. Go to the preferences dialog and just click Ok. This should rewrite the settings.

**Comment by erik90mx** [comment]
Hi,

The issue is there with my current brush setup:
![image](https://user-images.githubusercontent.com/3485891/63660247-32481380-c77b-11e9-8472-3226703ce903.png)

After press the Ok dialog as @callaa mentioned, the problem seems to be solved in my case.

![image](https://user-images.githubusercontent.com/3485891/63660277-560b5980-c77b-11e9-985f-7cd10bf32dbb.png)


Regards

**Comment by notfood** [comment]
Stale, closing. Tablet handling has been changed in recent versions. If you're still experiencing this issue feel free to re-open it.
