### ISSUE TITLE
stabilizer when?!?!?!

### ISSUE THREAD

**Issue by TempaFloof** [drawpile/Drawpile#797]
oh my god, i love this app, but the lack of a stabilizer is weighing it down so much, please do consider adding it soon,,,,

**Comment by Wade821** [comment]
I think the addition of a more full featured stabilizer (since drawpile just has smoothing at the moment) would be a long ways away, truthfully. Because it would have to rely on hardware specific information to some extent and various tablets, as well as specific API programming on different operating system platforms (Windows, Linux, Mac). 

I already know from talking with Callaa that he doesn't have much in the way of Windows specific API and such, so doing this would be a rather time intensive task. Not saying that this isn't a valid suggestion or anything, it'd be great to have more control! I just lack the programming knowledge to help and I know people have been recently asking for things like expanded brushes and a Drawpile version for Android. With so much to do, I think it'd be off in the distance.

In the meantime as a sort of stop gap solution, it may be better to consider an external program like [Lazy Nezumi](https://lazynezumi.com/) for pen stabilization. It's already an incredibly full featured program with a free 15 day trial and can be used with multiple drawing programs. It costs $30 and comes with 1 year of free updates before needing to buy it again for newer version. That's about all I know off hand though, and hopefully this would help with keeping you held over in the meantime.

**Comment by callaa** [comment]
A stabilizer is not OS specific, I think, it's "just" a matter of implementing a better algorithm. Right now, Drawpile has a simple rolling average based smoother (which works surprisingly well considering how simple it is.) That I haven't implemented a better one yet is not due to me considering the feature unimportant, but rather because I don't know how and haven't studied up on the topic yet.
