### ISSUE TITLE
Stuck in Eraser Upon Startup

### ISSUE THREAD

**Issue by theArigoth** [drawpile/Drawpile#798]
I've been having on going trouble with Drawpile for a while, where it was either switching to eraser mode on it's own while I was drawing and I'd have to switch back, now it is simply stuck in eraser mode even after closing and restarting the program as well as uninstalling and reinstalling, neither seem to be a solution.

I've tried tampering with the preferences and switching both Windows Ink on and off, resetting each time with a no go for either option as well. I've also tried both available versions of Drawpile, the 32 and the 64 bit with still the same issue.

I'm using a Huion tablet, but it works fine with any other art program I have.

**Comment by Wade821** [comment]
Please make sure that when you're in brush mode, that the eraser icon in the freehand dock is not selected! 

![image](https://user-images.githubusercontent.com/18544575/64058425-cd683100-cb5f-11e9-91a2-ebb8caad5534.png)

Also please verify you're using the most up to date version of Drawpile, you can check your version by going to help, about Drawpile. The number in there should read 2.1.11. I believe there was something about the eraser in a previous version, but I cannot immediately recall off hand. 

Alternatively, a lot of Drawpile settings (in Windows anyway) are stored in the registry. If you're comfortable with editing that, you could open it and remove the entries for Drawpile. Specifically this: `Computer\HKEY_CURRENT_USER\Software\drawpile`, however, before explaining that I'd rather find out the information I provided you first. Editing the registry can harm your computer if done incorrectly and require you to reinstall the operating system. 

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed.

**Comment by theArigoth** [comment]
Yep I'm using the most up to date Drawpile download. It was working fine the first few times I had used the program when I had first downloaded it, now it just will not deselect the eraser tool.
I've tried switching to the brush tool from the right hand menu, as well as the top tool bar, but neither option is working for me unfortunately.
No matter which tool I select to use, the eraser stays stuck in select with whatever tool I try and use.

**Comment by Wade821** [comment]
This was noted in Discord. Perhaps this might help? Also, can you show me a screenshot of your settings? 

![image](https://user-images.githubusercontent.com/18544575/64059810-2e9bfe80-cb78-11e9-88a7-0667e121df1f.png)

**Comment by theArigoth** [comment]
![drawpile](https://user-images.githubusercontent.com/54721781/64203489-5f19bc00-ce48-11e9-9bff-ff16176806fa.png)

Here's a screenshot, I'm not sure if this is what you're looking for?
But the note in Discord that you sent me has helped me out, I'm able to get the brush to work as long as I follow those steps, so I appreciate that so much. Thank you!
I'll be saving that in case I run into problems again.
Unless there is something wrong with my settings that is causing the problem?

**Comment by Wade821** [comment]
I'm not completely convinced you're actually using the newest version, simply because the bug that you seemed to experience was actually fixed in 2.1.9. Rereading Discord chat history, I found more of the chat referencing the inconsistent state issue.

![image](https://user-images.githubusercontent.com/18544575/64238396-2fec6480-ceb3-11e9-953f-cdca7705d6d0.png)

And this is the [news release for 2.1.9](https://drawpile.net/news/release-2.1.9/) indicating that issue was fixed. I don't mean to be obstinate or anything, but I hope you're actually checking the version number in Drawpile's help, about Drawpile menu (this has happened before after going over all kinds of things to try and fix the issue just to find they just believed they were up to date). 

![image](https://user-images.githubusercontent.com/18544575/64239773-b144f680-ceb5-11e9-8dff-2b0af1afd207.png)

If you are, then if you manage to cause the problem or it keeps happening, anything you can write down on how the issue is reproduced would be great so it can be fixed. 

As far as your settings are concerned, no, I don't see any issues there. That was the screenshot I was looking for, I just wanted to see that info to confirm. 

Only thing that comes to mind that it could be related... has to do with what version of Windows 10 you're using (Windows Key + R, type winver, look for version). Some people reported some weird drawing tablet issues in Windows 10 1803 and 1809. Newest Windows 10 version is 1903. That might be a stretch though, one user was using Wintab like you and just kept panning when they tried to use their tablet... and another user was using Windows ink and had some weird stuff going on as well. Regardless, if you're using an older version of Windows 10, you want to update anyway just so your system is supported. Again, this is a **_real stretch of the imagination here_** because this is either a new bug, an old bug cause it's not up to date, or something related to your system.

You can try to update it a few different ways. Make a shortcut on your desktop by right clicking, go to new, and shortcut. Type in *ms-settings:windowsupdate* in the box, hit next, type in "Windows Update" for the name, and next/complete. Double click your new shortcut to run it and check for updates.

You can also try to force the upgrade via the upgrade tool, Main website here: https://www.microsoft.com/en-us/software-download/windows10
Update Tool is the first blue box to click there with "Update now"

**Comment by theArigoth** [comment]
![Drawpile 2 1 11](https://user-images.githubusercontent.com/54721781/64240586-fa497a80-ceb6-11e9-89af-1ca1183ae565.png)
![Windows 10](https://user-images.githubusercontent.com/54721781/64240592-fcabd480-ceb6-11e9-8a73-bbffd2779166.png)

I'm up to date on both, unfortunately. If I experience the issue again, I will report on it and see if I can find out what is causing the issue. This is the second time it's fully locked onto eraser and that information from the Discord chat helped me out of it. The first time it was stuck on eraser mode for a while and eventually one load up of the program later, it was working again.

**Comment by Wade821** [comment]
Thanks for being patient and confirming both. It may be that it was retaining the prior incorrect state before you updated to a newer version and doing the steps I provided earlier helped bring it out of the state, though I'm not sure entirely as that depends a lot on how the bug was eliminated. It's either that or it's a new bug. 

I'd ask for the time being that you mark this issue as closed/resolved, and if it pops up again you can always re open it. Just try to remember to provide steps as to how you got stuck in the first place if possible! Recreating bugs is important to figuring out how to fix them. 

Anyway, I'm sorry I wasn't of more help with this! At least you seem to have figured it out with some screenshots from Discord. :)

**Comment by theArigoth** [comment]
Yes, I'll see if I run into that bug again and see what I did or how it's coming across if it does at all appear again. (Hopefully not.)
Also you've helped me out plenty, thank you! Very much appreciated. :)
