### ISSUE TITLE
Rotating Selection Cause Blur

### ISSUE THREAD

**Issue by HaloRings** [drawpile/Drawpile#803]
When rotating a selection, it cause the image to look blurry/pixelated after.

[http://sendvid.com/hf7s9juo](url)

**Comment by Wade821** [comment]
This is due to interpolation, something that must occur in order to rotate images. It's even a problem that exists in other [drawing programs since it is pretty much expected behavior](https://procreate.art/discussions/4/10/15411).

As such, sure this is already well known to Callaa, and fixing it isn't a simple matter unfortunately. When you rotate an image, the drawing can't be exactly replicated because it won't fall into a perfect alignment, unless you happen to rotate exactly in 90 degree increments. Some of this also has to do with the [anti-aliasing that goes on near the edges](https://graphicdesign.stackexchange.com/questions/92870/blurry-rotated-triangle-both-illustrator-and-photoshop) of the drawings themselves. Some of the solutions for this also requires using more RAM memory in the computer to potentially resolve this issue....

So I think what would be better here is a discussion about how to approach the problem. [One such thing I was reading](https://wiki.wesnoth.org/Rotate_Pixel_Art_Without_Blurring) suggested first resizing the selection to 4x the original size, rotate, and then scale back down to original size. However, this would not work in Drawpile as currently there is an issue with scaling something larger while holding shift, as it will distort the drawing. Until that's fixed, not really a viable potential solution. On a side note, it'd be nice to have the ability to scale something up a specific percentage amount.

Another option would be to have the ability to set different types of scaling when resizing and rotating images, as is present in Photoshop to best tweak the drawing according to what looks best with the drawing being used. Example below (not my art by the way).

![image](https://user-images.githubusercontent.com/18544575/65660421-7d0bb400-dfe3-11e9-8225-55818fa33d2c.png)

That being said, we also can look at Krita which is open source! So that means we could use some of their code to improve rotating selections as well by having different options available for interpolation.

![image](https://user-images.githubusercontent.com/18544575/65661008-5484b980-dfe5-11e9-8c50-bcc1a5cc6c8b.png)

Anyway, these are just some possible ideas. Borrowing from Krita is probably the easiest way to implement those improvements.

**Comment by callaa** [comment]
When a selection is rotated, smooth interpolation is used, because the nearest-neighbor mode looks terrible. A smarter algorithm, like in Wade's comment, would help here.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This is implemented and will be coming with Drawpile 2.2.


https://user-images.githubusercontent.com/13625824/227437872-10936051-2b8c-4752-805f-c946a36e34be.mp4
