### ISSUE TITLE
Portable Version in Windows

### ISSUE THREAD

**Issue by erik90mx** [drawpile/Drawpile#804]
Hi,

I used DrawPile in my daily job to draw diagrams and easy to understand sketches about processes for developers when we are on a meeting.

Right now the company just renew all the laptops, and a lot of them are very restricted in terms to install external software. In my job I don't connect ( and the network is restricted too) to external sessions, so a lot of the time I just need a simple canvas to draw the explanations and to be honest I'm very used to DrawPile interface and tools, that's why I always choose it to do this.

It will be very helpful to have a Portable Version for Windows in the Download section, in case that more people have a similar scenario (there are even people that like to use applications in that way on their personal USB).

Regards

**Comment by callaa** [comment]
Yeah, this should be possible. The installer is not strictly needed, since it is possible to just copy the entire folder from program files to a USB stick and use it from there. Although, I think a true portable app is one that doesn't even write to the registry or user local folders, so you can carry it with you, settings and all. This too should be possible with (maybe?) just minor changes to the code.

**Comment by callaa** [comment]
An update on this: You can now start Drawpile with a command line argument like `--portable-data-dir portabledata`, in which case Drawpile will store all its data files and configuration (includes the ones it would normally store in the Registry) in `portabledata/` directory.
This should make it fairly easy to package Drawpile with the portableapps.com launcher.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Drawpile 2.2 will be offered as both an installer and a portable ZIP.
