### ISSUE TITLE
FR: Autoconnect after sleep

### ISSUE THREAD

**Issue by gerroon** [drawpile/Drawpile#805]
Hi,

Is it possible to autoconnect a session after the computer wakes up from sleep mode? At the moment the session is always disconnected and requires reconnecting which is a bit confusing, if the artist  is not careful about what is going on. 

thanks

**Comment by callaa** [comment]
A simple auto-reconnect is possible, but it would open a new window, since it's currently not possible to reconnect an existing session. This is not impossible, the server just doesn't support it at the moment. (What would be needed is a way for the client to say "I already got everything up to this index, skip to the new part" so it wouldn't have to reload the entire history. But this can be quite difficult and fragile.)

One thing that would be easy to implement and generally useful, I think, would be a notification bar that pops up whenever the connection is lost. It could have a "reconnect" button that opens a new window and connects back to the same session.

**Comment by gerroon** [comment]
I think that as long as the previous session csloses automatically, that  could be a work around?

**Comment by Wade821** [comment]
Cleaning up duplicate issues. Please comment on older issue #287 for further discussion.

**Comment by Wade821** [comment]
Added in 2.1.16.

https://drawpile.net/news/release-2.1.16/
