### ISSUE TITLE
New update removed tools

### ISSUE THREAD

**Issue by daddddddddd** [drawpile/Drawpile#806]
The new update removed the watercolor brush as well as reset all brushes. It also caused the eraser to no longer work, but a reset fixed that. I uninstalled and reinstalled the version before the update so I have at least fixed it for myself, but I just wanted to let you know that the new update has this issue.

**Comment by Wade821** [comment]
Drawpile removed the watercolor brush specific tool, because now it's combined with the other tools. 
So the tool is still available, it's just set up in a more flexible way so all brushes can make use of it if desired.
![image](https://user-images.githubusercontent.com/18544575/67209185-c2958400-f3cb-11e9-8801-fe224be92c6f.png)

The resetting all brushes is, I'd imagine, unintentional. However, this new version addresses a long standing bug of keeping preset brush settings in the Windows Registry and moves it into a specific file. This way if you were to go to edit, preferences, and reset your settings your brushes would not also be lost as a result of doing so. Those files are located below (just written in two different formats, both should work)

`%localappdata%\drawpile\drawpile\brushes`

`C:\Users\%username%\AppData\Local\drawpile\drawpile\brushes`

As far as the eraser is concerned, it works, it's just that this new version reintroduced an old bug that was fixed in 2.1.11. You fix it by simply selecting a color on the color wheel dock while using the eraser. You'll notice that the freehand dock is pure white before selecting a color, and then shows the checkered pattern after selecting a color. After that, you shouldn't have to do this to get the eraser to work again in the future, it's a one time deal to initialize the tool with a color setting (since the eraser can also erase specific colors from the board if desired). 
![image](https://user-images.githubusercontent.com/18544575/67209902-063cbd80-f3cd-11e9-9fec-0287dc497267.png)
