### ISSUE TITLE
Installers are not working

### ISSUE THREAD

**Issue by KaisoArt** [drawpile/Drawpile#815]
I have a Windows 10 64 bit computer, I downloaded version 2.1.12 installer for windows 10 64 bit, when I click on the installation file, it does the loading animation on my mouse and nothing happens. Since it says if you have problems with the 64 bit, I tried the 32 bit installer, and it had the same result. Each time I clicked the installer, windows explorer would become unresponsive, and nothing would happen. The zip version for 2.0.10 works, but I would like the newer version, just can't seem to get the installer to work for some reason?

**Comment by Wade821** [comment]
The installer does work, as I've installed it myself and several others. Perhaps consider checking to see if your Antivirus is on and disable it temporarily. Some Antivirus software programs will proactively prevent the installation of programs just because the program is uncommon, even if it doesn't detect anything wrong with it. 

If you're concerned about doing so, you might want to try using something like [VirusTotal.com](https://www.virustotal.com/gui/home/upload) to first check it for viruses as it puts it up against multiple antivirus programs. As long as a large majority of them do not detect anything, it's usually safe as those that do detect something are false positives. Meaning that they're essentially false alarms. When I just ran it, 2 out of 69 scanners detected a concern, specifically McAfee-GW-Edition ( BehavesLike.Win32.AdwareFileTour.wc ) and Trapmine ( Malicious.high.ml.score ). Last I checked this for Drawpile 2.1.11, Trapmine was the only false positive here. I will send this for review to those two companies later so they can correctly identify it as safe.

**Comment by KaisoArt** [comment]
Only antivirus I have is windows defender, I restarted my PC and it worked perfectly after but I still have no idea what caused the issue in the first place. It was a very weird bug, never experienced something like that before. Thanks anyways
