### ISSUE TITLE
2.1.12 - Haven't been able to host/join private sessions since the update

### ISSUE THREAD

**Issue by divinecervine** [drawpile/Drawpile#818]
A friend of mine and I use drawpile very casually, but frequently. We host private sessions via their computer using drawpile.net's listing, use the IP as the room code, and enjoy drawing together from there. 
Since the update, every attempt has resulted to a timed out connection. We've checked both of our internal firewalls and drawpile is an allowed app on both of them. We aren't doing anything differently in this process. I'm aware that there is an incredibly indepth description about firewalls on their site, but it isn't a very beginner's-friendly approach by any means; none of it makes sense to me or my friend. I can't tell where the problem is. 

Is there something that we're missing? Is it just us experiencing this problem? Any and all help is very appreciated.

**Comment by callaa** [comment]
If you upgraded from 2.1.11, there shouldn't be any changes in the client that I can think of that could explain this. Assuming it's not a coincidence that the problem occurred right after upgrading, my best guess is that an application firewall is recognizing the updated version as a different app and blocking it. Try if you can remove drawpile from the firewall's list and then add it again.

**Comment by divinecervine** [comment]
I personally only use Windows Defender, and the application has been and still is on my allowed apps list. As per your suggestion, I've removed and re-added it. Maybe it'll make a difference! My friend has also stated that the application is explicitly allowed through their firewall, and I'll suggest that they take the same measure.
I'm just not sure what it is that's going wrong. It's frustrating, to say the least. 
Thanks so much for the help so far!

**Comment by divinecervine** [comment]
2.1.13 dropped, and... nothing. Nothing at all has changed about this situation. We haven't a clue of what to try, and on whose end the hangup is on. Maybe there's a checklist of ways to troubleshoot that someone out there may have? I'd be beyond grateful at this point. 

As an aside, we're in the middle of attempting to host a session on drawpile.net instead of my friend's computer, and it requires a drawpile.net account to access. But, despite how many times I know that I'm typing it correctly, it insists that it's incorrect. I even changed the password on the website, relaunched the computer, etc. So, that's a fun additional problem to experience. :(

**Comment by Wade821** [comment]
It might be an easier problem to address in chat format rather than here. I've copied and pasted the info for Drawpile's official Discord channel just below from my other posts here. I think it'd be interesting to see if a third party could join your session to see if the issue lies on one side, the other, or perhaps even both sides. There's a lot of potential issues here that would be best addressed in real time, I think.

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed.

**Comment by notfood** [comment]
Still an issue?
