### ISSUE TITLE
Pen and mouse clicking at the same time when using tablet pen?

### ISSUE THREAD

**Issue by markie1239** [drawpile/Drawpile#819]
I noticed that when drawing in Drawpile, occasionally, my pen would click as if I was double tapping on the screen with my pen and leave behind a dot on my drawn line- especially smaller lines when working on details or dotting the canvas. I checked the tablet tester and apparently drawpile is registering that I am drawing with my pen AND mouse at the same time.
![dp problem](https://user-images.githubusercontent.com/57303428/68077747-6ce3b300-fd9f-11e9-9bc5-dc6615d2f7a9.PNG)

![dp problem 2](https://user-images.githubusercontent.com/57303428/68077777-2a6ea600-fda0-11e9-952a-35d45be8b7b8.PNG)

I tried turning on the WinTAB option and resetting DP but the problem would still be persistent and the wintab option wouldn't be checked! I am using a XP-PEN screen tablet and have checked to see if it was actually my tablet? I messed with the settings, but I didn't see any setting that would be related to the problem. I also believe it isn't my tablet since this doesn't happen in any other drawing program and only in drawpile.

**Comment by Wade821** [comment]
When opening Drawpile, both the tablet and mouse will show up in the tester. This is normal behavior. In Drawpile and under the help menu, about Drawpile, what version are you using as well (just to confirm). 

When you say "Wintab" option, are you saying you tried turning on "Enable relative pen mode hack (Wintab only)" and that option wasn't staying on? If you were turning on that option, is the option above it "Use Windows Ink (requires restart)" checked? If Windows Ink is enabled, the option below it should be disabled. If the Windows Ink option is disabled, you may choose to have the Wintab hack option enabled or disabled according to how it works for you. What mode you should use depends entirely upon your tablet configuration and if Windows ink is on in there. I suggest using Windows Ink if possible (especially if you're already using your tablet in pen mode/absolute mode), since it's much newer than the older Wintab mode. 

![image](https://user-images.githubusercontent.com/18544575/68091753-feefc800-fe40-11e9-9989-d1f7a94c40f6.png)

**Comment by markie1239** [comment]
Hello! My apologies for not responding sooner. 

I am using the 2.1.5 version of Drawpile. Yes, when refering to the WinTab, I am refering to the relative pen mode hack.

![penmode](https://user-images.githubusercontent.com/57303428/68094296-e4cbdf00-fe6c-11e9-8102-b80c6a74e121.PNG)

Yes, when I would attempt to check it and restart my DP, it would not stay checked. I attempted not restarting my DP and it still went back to being unchecked. I supplied an image of what I see when I go into preferences on DP.

I currently have Window ink disabled? I think it is disabled. 

![wi 1](https://user-images.githubusercontent.com/57303428/68094353-8eab6b80-fe6d-11e9-9e1e-a81edfb0fdd1.PNG)
![wi 2](https://user-images.githubusercontent.com/57303428/68094357-93701f80-fe6d-11e9-861c-c0e7965b9f44.PNG)

I also checked my XP-PEN tablet settings and the set up is also not quite the same?

![xp 1](https://user-images.githubusercontent.com/57303428/68094378-d9c57e80-fe6d-11e9-8308-d637ff7a4dbc.PNG)
![xp 2](https://user-images.githubusercontent.com/57303428/68094380-dcc06f00-fe6d-11e9-85d3-9bc15409507c.PNG)
![xp 3](https://user-images.githubusercontent.com/57303428/68094387-dfbb5f80-fe6d-11e9-9ca8-87214cfa7bfc.PNG)
![xp 4](https://user-images.githubusercontent.com/57303428/68094389-e1852300-fe6d-11e9-8a17-ffedbfdace7a.PNG)
![xp 5](https://user-images.githubusercontent.com/57303428/68094391-e34ee680-fe6d-11e9-970f-db2e31f5b371.PNG)

There seems to be an option missing from what you are explaining to me that my DP should have. I am unsure if maybe I do not have the latest update? I will try going to the DP site and manually download the application again to see if it will force an update.

**Comment by Wade821** [comment]
Yep, you're definitely out of date. And I remember hearing issues like this in that version that you described in the official Discord channel for Drawpile. Try updating. 

Also, Windows Ink does appear to be on in your tablet settings, I'm guessing it's that "Supports Digital Ink" setting that turns it on or off. Once you update Drawpile, you could test that idea by having Windows Ink on in Drawpile and in your tablet setting as you have it now. You should have pen pressure. If you turn it off in Drawpile, you should *not* have pen pressure. If you turn off the "Supports Digital Ink" setting in your tablet, you should have pen pressure again.

**Comment by Wade821** [comment]
**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.
