### ISSUE TITLE
Building from sources (Windows, Qt Creator)

### ISSUE THREAD

**Issue by Banderi** [drawpile/Drawpile#824]
So after many tears of pain I managed to finally set up Cmake and Qt and it finally was able to compile; from what I understand noone likes Windows and building/maintaining for it is a pain, so understandably the steps on the Wiki are ambiguous/outdated/broken/imply omitted steps which require years of Linux experience to discern and apply correctly.

After a bunch of trial and error, I have managed to get the code to compile even though I am not able to make the program 100% function correctly yet.

Before editing the wiki, I'm gonna take the time and take note of all the steps that actually seem to work.
Here's what I've done so far:

1) Download CMake from [here](https://cmake.org/) and the _Open Source_ version of Qt from [here](https://www.qt.io/download-thank-you?os=windows) or from the homepage, here:
![image](https://user-images.githubusercontent.com/16541079/68560879-83df7080-0443-11ea-9218-3c48753fb2a2.png)
2) Download _MinGW Installation Manager_ (mingw-get) from [here](https://osdn.net/projects/mingw/downloads/68260/mingw-get-setup.exe/)
3) Choose the following packages from the manager:
![image](https://user-images.githubusercontent.com/16541079/68557710-f4cc5b80-0436-11ea-8ed6-42ca89c621df.png)
4) Download the required additional modules for the project from the official repos [here](https://github.com/KDE/extra-cmake-modules) and [here](https://github.com/KDE/karchive) as well as Zlib from [here](https://github.com/madler/zlib/)
5) Open ECM's `CMakeLists.txt` with _Qt Creator_, select "Release" from the build configuration dropdown, wait for it to load the kit's settings, hit the Build button on the bottom left or hit CTRL+B to build the project
![image](https://user-images.githubusercontent.com/16541079/68561296-467be280-0445-11ea-97ec-308df713da2e.png)
6) Navigate to ECM's extracted repo's folder's parent, open an elevated command prompt into the new folder which contains the release built, and type: `cmake -P cmake_install.cmake`
7) With ECM correctly installed, close and reopen _Qt Creator_ and perform the same #5 and #6 steps for Zlib and Karchive
8) Open the Drawpile master in _Qt Creator_; before building, right click on the MinGW kit, hit "Manage Kits..", select the kit from the list and hit "Change.." near the Environment setting; in the textbox, add in this line: `KF5ARCHIVE_DIR=C:\Program Files (x86)\ECM\lib\cmake\KF5Archive`
![image](https://user-images.githubusercontent.com/16541079/68562199-e8e99500-0448-11ea-9305-2825ffdb5ac1.png)
9) Open the `CMakeLists.txt` inside Qt Creator's editor and add this line right after the "add_definitions" line: `add_definitions(-U__STRICT_ANSI__)`
![image](https://user-images.githubusercontent.com/16541079/68562336-7d53f780-0449-11ea-8d4a-f4fdf97c2b73.png)
10) Build the project and wait for the compilation to finish
11) Notice how the program cannot be run like this. It fails because it's missing necessary libraries which aren't deployed automatically inside the build folders, and are distributed with Drawpile's setup. Instead of spending a million years tracking down every single file, you can quickly test if the program runs by dropping the executable inside the proper Drawpile installation folder (careful not to overwrite the original) and run it from there - or copy the necessary files over to the build folder.
![image](https://user-images.githubusercontent.com/16541079/68562543-737ec400-044a-11ea-9a75-a5f3ad54c570.png)

It will now run correctly, and retain the original installation's saved settings, however pressure sensitivity does not work. If you copy over the original executable inside the build folder, you can run that just as easily and pressure will work just fine.
![image](https://user-images.githubusercontent.com/16541079/68562877-dde43400-044b-11ea-9163-1525c8071155.png)

You can also notice how the executables clearly do not match in terms of size, but I thought this would be because of optional packages that are mentioned in the Wiki, like Bonjour.
![image](https://user-images.githubusercontent.com/16541079/68562853-c60cb000-044b-11ea-867e-1051644a11cf.png)

I assume the Wiki's section is knowingly very outdated by now so I'm sure there's some stuff missing, but I'm struggling to find anything else at this point that I need to do to make things work properly.
Any clue as to what that might be, maybe something that was changed to the pressure's code or tablet drivers' handling sometimes along the road? Additional libraries that were added in later on?

**Comment by callaa** [comment]
Thank you for the writeup.

Some notes and questions:

It shouldn't be necessary to manually install mingw. It should come bundled with the Qt SDK. I suppose what's missing from the wiki page is where to find it. (It just says "Add gcc and cmake binary directories to your PATH environment variable", which probably isn't helpful if you don't know where it got installed. It's been a while, but if I recall, it's in C:\Qt\Tools\)

The required additional libraries can be downloaded from the links included on the wiki page, although you can get them straight from github too.

Building/installing the deps is easier from the command line, in my opinion, but I guess you can do it from Qt creator too. However, if you're using Qt creator, manually running cmake shouldn't be needed. Also, when running from the command line, you can run `mingw32-make install` so you don't need to manually add the directories in the "Managet kits" section. This also makes it so you can run the produced drawpile.exe without copying all the libraries to the same directory. (Although you still need to do that to make a distributable package, and you need to copy the icon theme folder for icons to show up.) 

What happens if `-U__STRICT_ANSI__` is left out? I haven't encountered that before.

Regarding the missing tablet pressure: Did you enable the `KIS_TABLET` option? If so, that would explain it. On Windows, that option needs a modified version of Qt to work correctly. (The two patches needed can be found in the source package directory `pkg/win`, but recompiling Qt on Windows is such a task I found it easier to just crosscompile the entire thing on Linux.)

The size difference between the two executables is unexpected. There is more stuff compiled in in my version, but I wouldn't have expected it to make such a big difference.

But in summary, I believe the wiki page is still mostly up to date. My guess is that if you didn't put mingw and cmake in the system path, you had to go through a harder route to build the deps.

**Comment by Banderi** [comment]
Hello there, thanks for the response!

I did notice Qt came with a MinGW installation if you select it in the setup's settings, and the default auto-detected kit is indeed that one:
![image](https://user-images.githubusercontent.com/16541079/68624092-5abbf000-04d6-11ea-9219-678691fe8201.png)
If that's the case, I guess installing MinGW separately with the manager is an unnecessary step, yeah.

I agree the command line would be much faster and I tried to use that to build and install the modules, but it didn't seem to work unfortunately. There were lots of issues, some of which I was able to get past with Google and some got me stuck, which probably would be much more trivial to see through if you have more experience of CLI/Linux than me, I wasn't able to get past them and decided to build from Qt to be 100% sure. I might try again and see exactly what the errors are so I can say for sure though.

The `-U__STRICT_ANSI__` option is to set the `<cmath>` inclusions to work properly; I can't say if this is strictly a Windows problems or my Windows 10 version - `<cmath>` does not include math constants correctly, and it complains about `M_PI` being undefined. Surfing around I saw a couple different solutions, but that one seemed to be the simplest and least intrusive.

I did notice the `KIS_TABLET` flag was off from the kit's options, and I tried rebuilding with that turned on but I didn't make any difference. I was looking around for linking Qt statically and did read about having to re-compile Qt on Windows, is that the same headache you mentioned?

**Comment by callaa** [comment]
I don't have a Windows computer at home currently, so I can't verify the steps. But Microsoft does seem to be offering a free virtual machine image that I could probably use.

It appears that the `M_PI` constant is not defined in the C standard, which is why undefining __STRICT_ANSI__ is needed on Windows. I could replace all `cmath` inclusions with `QtMath`, which does always define M_PI.

If you have KIS_TABLET switched off and pressure sensitivity still doesn't work, I'm not immediately sure what the problem could be. Qt's own tablet support is kind of buggy, but it should work at least partially.

Yeah, building Qt from scratch is a ridiculous amount of work. On Linux it's not so bad, because all the dev tools and other dependencies are easy to install or are already present. That's why I didn't even try to build it myself on Windows and found it easier to crosscompile it on Linux. (Thanks to MXE, mainly. It automates everything, including the application of custom patches.)

**Comment by Banderi** [comment]
I have looked into it more and I realized the issue; on the build configuration, you need to check `KIS_TABLET` _and_ hit "apply configuration changes" for it to actually work. I noticed this since the setting wasn't kept on between sessions.

![image](https://user-images.githubusercontent.com/16541079/68722286-4569c300-05b5-11ea-9b55-aa716fac0eed.png)

I have rebuilt the project with the setting enabled, and pressure seem to work correctly this time!
I will test about if I see any more issues and report here if I have any more, and if I can get around to it I'll try the commands again to see which errors in particular I was getting. Thanks for the help so far!

**Comment by notfood** [comment]
Support issue appears resolved.
