### ISSUE TITLE
User Icons and names too big/blurred [2.1.13 update]

### ISSUE THREAD

**Issue by ObsidianFoxx** [drawpile/Drawpile#827]
![image](https://user-images.githubusercontent.com/57693479/68726709-978ff180-057f-11ea-9c09-89175f8db453.png)
User icons are gigantic, and names are too large and blurred. The whole thing is much too large for itself, I can't fit my set-up as it is.

**Comment by Wade821** [comment]
This is probably due to scaling issues set in Windows, as the new version updated with high DPI icons to accommodate such screens. Right click your desktop, go to "Display Settings", and under the section "Scale and layout", check what the % is set to for the scale. After setting this to a lower value, you may need to sign out and sign back into the computer for the settings to fully take affect. Try that and let me know how that works for you.

**Comment by ObsidianFoxx** [comment]
Ahah! Sizing it down fixed everything. Very bizarre, though, that I have to do it that way. I'll have to get used to everything being smaller, but.
