### ISSUE TITLE
Assets library and plugin system?

### ISSUE THREAD

**Issue by excitedbox** [drawpile/Drawpile#840]
I was wondering if it would be possible to add an assets library panel. Along with a grid it would allow people to design circuits together for instance. Or you could do level design. Basically anything that requires using the same pieces repeatedly. 

I think maybe making a plugin system would be a good feature to have. It would make it easier to add features, it lets you pick and choose features you want, speeds up development because anyone can make a plugin instead of having to do a deep dive into the project.

**Comment by callaa** [comment]
An asset library sounds like an interesting feature. Can you point to any examples from existing software to draw inspiration from?

A plugin system would be useful as well, but it's nontrivial to implement. It could be done in two ways:
1. Extension DLLs. This is probably not the best way, since the plugin author would need to write the plugin in C++, in which case it would be easier to just modify Drawpile's source code directly.
2. Extensions written in Javascript. This way would be more accessible to plugin authors, at the cost that you're much more limited in what you can do. To design an extension mechanism like this, I'd need some input about what sort of plugins people would like to be able to write.

**Comment by excitedbox** [comment]
I was thinking just a panel that displays a small thumbnail for all images in a certain folder. Then you can click and drag them onto your work area. Kind of like how Adobe Flash let you group lines etc into an object and then you could reuse them. That would also be an important feature to have. Click and drag to select things on canvas and group them into an object/asset.

That way you can put all your assets in that folder. For circuit diagrams for instance you would have a small image for all the electrical component symbols like resistors or chips and can click and drag them wherever you want them. Then you rotate/flip them and draw a line for the wires.

Or for game level design you would have  all your 2d sprites or objects such as trees and jump platforms and you could quickly sketch out a level as a team by clicking and dragging components.

I think it would expand the usefulness of Drawpile even if you didn´t use it as a team because it lets you work fast and efficient.

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

I don't think the asset library thing makes too much sense, since Drawpile is a drawing program, not a circuit designer or level editor. You could just put those assets in a separate area of your canvas to copy and drag them over, so it would still be usable in that way, but having a special user interface is outside of its scope.

With regards to plugins, the major issue there is the huge abuse potential. I don't want to deal with people complaining that Drawpile crashed their computer because they hooked in some shady DLL or scripts, or have mods deal with script kiddies griefing sessions.
