### ISSUE TITLE
Brush spacing limit in slider

### ISSUE THREAD

**Issue by calmnivore** [drawpile/Drawpile#847]
spacing is soft locked at 50%. while you CAN use the keyboard arrows to raise it above that, it's kind of annoying and the value in the bar itself resets to 50%. I'm not sure why this was done but I am not a fan.

**Comment by callaa** [comment]
IIRC, the spacing slider has always been capped at 50%. However, since version 2.1.2, it has been possible to set the spacing up to 999% using the spinbox. The rationale for this behavior is that when you're using the slider, you typically want to adjust the spacing within its "normal" range, where the dabs still overlap. If the slider's range is too great, it is difficult to make fine adjustments. I suppose increasing the slider's range to 100% would be reasonable, though, since at 100% the dabs still just barely touch and anything above creates disconnected dabs. (Which can still be useful for special brushes, which is why the spinbox can go over the slider's limit.)

What is the range you typically use, or would like to use via the slider?

**Comment by calmnivore** [comment]
to get the spacing I like I set it at like 150%. If you want precision you can just use arrow keys anyways.
