### ISSUE TITLE
Brushes are textured with pixels - like color erase and behind.

### ISSUE THREAD

**Issue by Leonzo-o** [drawpile/Drawpile#863]
Okay so Im having some problems with really the majority of my brushes. They do something like this. The normal brush less of it all. But the rest of the options for the brushes such as recolor, behind, etc do this. This is just a more clear view of what its doing. At leas the others aren't this noticeable though.  Idk if this is a bug or not, it didn't do this to me on version 2.0.11 of drawpile from what I remember. It's done this to me on all computers I've used, idk if this is something others have, but from what I've been told its not. I've also recently done a factory reset on my pc, and the issue is still present. So just posting it here to see if there is a solution or if its just a bug.   Im very very late to actually posting this, I've had it for a while.  
![unknown](https://user-images.githubusercontent.com/60681820/73809899-48321980-479a-11ea-91e2-8b59dba641f4.png)
![hgfhfg](https://user-images.githubusercontent.com/60681820/73809900-48cab000-479a-11ea-8589-7bf3dbe433ff.png)

**Comment by notfood** [comment]
Does it still happen if your spacing is set to 10?

**Comment by callaa** [comment]
That's definitely a bug, but I'm unable to reproduce it myself. You're using the Windows version, I assume? Are you using the 32 or 64 bit version?

One thing that has changed between 2.0 and 2.1 series is that pixels are now stored in premultiplied alpha format, so it might be related.

**Comment by notfood** [comment]
They have reported it on the discord one month ago, I notice it's the exact same picture. We need Drawpile version and more details please.

I tried to reproduce with no success either.

**Comment by Leonzo-o** [comment]
Sorry for the late reply. I'm using windows 10. I've also tried changing the spacing with the same result, it doesn't change with really any brush setting I use. 
The one had had taken before was still on drawpile 2.1.15. Though it had still done this before that update, it was on the first update of 2.1.12, as in when the formatting had changed over.  The only difference in the pic was the first pic was before resetting my pc, and the second was it was just the effect it gave even after resetting it, its the same bug.

**Comment by callaa** [comment]
Are you using the 32 or 64 bit version?

I noticed I can reproduce color artifacts like that when using the color eraser with very dark colors. I'm not sure if there's anything that can be done about it, though, since the color eraser only works best with very bright red, green or blue anyway.

However, I still can't replicate the problem for any other blending mode.

**Comment by Leonzo-o** [comment]
I am using 64 bit.

**Comment by Leonzo-o** [comment]
As for it doing it was darker colors, that is definitely more obvious on them yes. But its also a bit of static with other brushes, but I'm not sure if that's just normal.

**Comment by callaa** [comment]
One thing that could explain why this problem appeared in the 2.1 series is that the special blendmodes operate with non-premultiplied color, meaning the pixels have to be unpremultiplied before the operation is applied. This leads to precision loss in dark colors.

Can you show an example of the artifacts you get when using some mode other than color-erase? Some color glitching is expected when using very low-opacity colors, due to the 8 bit resolution.

**Comment by notfood** [comment]
Closing due to no response from submitter.

**Comment by Leonzo-o** [comment]
I'm so sorry for my really late reply.  I got busy and had forgotten about
it.  It still continues to do this. I've tried just about everything.
Turning the spacing up or down.  I'm surprised you haven't been able to
recreate it.  Idk if it's just for me or not.

**Comment by notfood** [comment]
Please, respond to this:
> Can you show an example of the artifacts you get when using some mode other than color-erase? Some color glitching is expected when using very low-opacity colors, due to the 8 bit resolution.
