### ISSUE TITLE
Text tool not working at all

### ISSUE THREAD

**Issue by djpsyc** [drawpile/Drawpile#875]
Hi I've brought this up a few days ago in the DrawpileNet discord #help_client channel.
I haven't been able to even select the text tool in drawpile recently, the icon for the tool does not react to any amount of clicks, nor does the shortcut work for accessing the text tool. This behavior is happening both while offline and whilst connected to a session as an operator.
I have tried re-downloading re-installing and downgrading from 2.1.17 to 2.1.15 and i have uninstalled the program each time before reinstalling or downgrading. Rebooting my computer did not work either. I was working through this issue with the help of Liz and they told me I should write a bug report here so here we are.

**Comment by Wade821** [comment]
Is your issue like this? [Bandicam Video - Text Tool not clickable](https://cdn.discordapp.com/attachments/546260997703467009/722717841685741648/bandicam_2020-06-17_00-41-46-345.mp4
)

If so, and you have Windows, it may be that you used an older version of Drawpile that was a standalone version in order to play an older session recording made. I managed to create this problem myself.

To fix it, I had to go in the registry (Windows key + R, type in regedit, and hit ctrl + shift + enter to run it as admin), navigate to this key:
`HKEY_CURRENT_USER\Software\drawpile\drawpile\window\actions`

And edit the below value from 'false' to 'true'. 
`showannotations=false`

If you need more help on how to check this, message back or join the official Drawpile Discord. Invite link is on Drawpile.net in the bottom left corner!

**Comment by notfood** [comment]
The origin of this issue is crashes during load into boards with limited features. The limited features stick on the settings even after multiple restarts. A solution would be to reset the features on program load.

**Comment by kloete** [comment]
@Wade821 sorry for the very late reply but I could confirm this works for me!
Thanks!

**Comment by askmeaboutlo0m** [comment]
I think this has been resolved a long time ago? These settings don't get remembered anymore anyway. If the issue persists, feel free to reopen it.
