### ISSUE TITLE
One server is extremely slow to load

### ISSUE THREAD

**Issue by vipperz** [drawpile/Drawpile#876]
Idk why or when exactly it started, but the rooms on the Entiti server have been loading so slow for me whenever I go into one _and_ when it resets for some odd reason. Even if the room had just reset after I go into one, each layer loads one by one slowly and then loads the activity of the board to the present. Doesn't matter if 1 person could be in the room, it'll take minutes to fully load.

I've tried doing a compatibility troubleshoot on drawpile as a whole, checked the firewall, searched why a server is slow, uninstalled and reinstalled drawpile, checked the properties of my wifi, etc, but i'm not seeing what is causing only one to be slow. Other servers (pub.drawpile/syntheticdreams) don't react like this when I go to them so it has been baffling me to no end for a month or 2 now.

Any help with it is appreciated. ;;

**Comment by Wade821** [comment]
The fact that it doesn't happen on other Drawpile servers is indicative the problem is with the server itself. This can be caused simply by having a busy server with a poor upload internet speed. As such, it's outside of my ability to assist with it. You should contact the owner of the Entiti server. Github is intended primarily for problems regarding use of the program, bugs and so forth. Not really support requests. 

Alternatively, I would suggest joining the Drawpile Discord server (link is available on Drawpile.net in the bottom left corner). The owner of the Entiti server is available there, Emii (Kotriaba#9739) I believe. This way the issue can be discussed better there.
