### ISSUE TITLE
Keep getting disconnected

### ISSUE THREAD

**Issue by 1nfinite3** [drawpile/Drawpile#879]
I'm trying to drawpile with a friend of mine, but every so often we get kicked off the server for no reason, as we have steady internet as well. Is this like some kind of bug or glitch? I'd really appreciate if this were fixed, we spent hours rejoining just to get kicked off again for no reason.

**Comment by notfood** [comment]
Issues with particular servers should be taken to the particular server.

What server are you trying to connect?

**Comment by Wade821** [comment]
Github is not intended for help with issues like this. The primary function is for reporting bugs and suggesting features. And while there are some issues we deal with in regards to the program, this is too user specific for this particular case. There are also a lot of factors that can influence connectivity, such as type of internet, wired or wireless, how many people or programs are actively using the internet while you use it, and many more. As such, I'll be closing this issue.

I suggest joining the Drawpile discord. Best because it's real time and helps keep GitHub focused. 
https://discord.gg/M3yyMpC

Alternatively, the Facebook group is also an option.
https://www.facebook.com/groups/drawpile/
