### ISSUE TITLE
Start of stroke stuck

### ISSUE THREAD

**Issue by IcicleTF** [drawpile/Drawpile#886]
![Untitled](https://user-images.githubusercontent.com/7268836/78339145-03401e80-7562-11ea-9cd4-9a69f212205e.jpg)

While I'm aware that this issue has been brought up here: #238 (and suggests that it has been resolved), I'm having no such luck.
Only as of the last few patches I've started having this issue, which is exclusive to Drawpile.

Things I have tried to resolve the issue include: 
Enabling/disabling windows ink, enabling/disabling the pen mode hack, restarting my computer and the program, reinstalling my drivers, closing other programs, changing input smoothing, etc.

I'm not sure why this would only start happening as of the past few updates, so I'm assuming it's a bug. I was wondering if anyone has any other suggestions because I'm not sure what else I can try from here to stop it.

**Comment by notfood** [comment]
There is no pen mode hack in Drawpile at current version. What version are you running?

**Comment by IcicleTF** [comment]
2.1.17.
![image](https://user-images.githubusercontent.com/7268836/78341515-d857c980-7565-11ea-8e72-90176d578b6e.png)
![image](https://user-images.githubusercontent.com/7268836/78341576-f1f91100-7565-11ea-9b94-9541f944a98e.png)

**Comment by Wade821** [comment]
Does the problem happen in Krita also? I suggest installing it for two reasons...

A) You'll get a preview of ORA files on your computer!
B) It's a good test since Drawpile uses some of the source code from Krita regarding the implementation and use of Windows Ink. 

Download and install here https://krita.org/en/download/krita-desktop/ or here https://ninite.com/krita/ ... let me know.

**Comment by IcicleTF** [comment]
Hey Wade, thanks for the suggestion!
It does indeed happen in Krita as well.
![image](https://user-images.githubusercontent.com/7268836/78524570-556f8280-77a2-11ea-9d5a-2992659f67e6.png)
My usual tools of trade are Photoshop and CSP, so I guess it's something specific to Windows Ink then, as you suggested.

What suggestions would you make? I think I've tried enabling/disabling Windows Ink before, but I hadn't noticed any changes.

**Comment by Wade821** [comment]
It might not have been Windows Ink specifically, what I was saying earlier is that Drawpile pulled tablet support from Krita for Windows Ink so that might have some impact. I don't know all the specifics however, so there is something I could be missing regarding that. I think Krita has made some improvements to the Windows Ink API so importing it into Drawpile might be helpful, though last I knew they were also waiting on patches to QT to be accepted... which Drawpile also uses. 

Anyway, glad you figured it out. I've seen some weird tablet issues like that where I had to try updating, reinstalling, and/or going to an older version with Wacom. At least it works now!
