### ISSUE TITLE
ip ban anybody cause nobody can join with kubernetes

### ISSUE THREAD

**Issue by pansx** [drawpile/Drawpile#887]
when server in kubernetes,ban anybody will cause nobody can join session,maybe that because sever run in pod resolve the client ip to load balancer's ip

**Comment by Wade821** [comment]
There's nothing that can be done to fix this. If multiple users are behind a single IP address, banning that IP affects everyone using it. There's really nothing that can be done about the IP situation if the load balancer you speak of isn't making the end user's IP address public. 

@callaa is eventually going to implement a feature where registered usernames can still be allowed to use the server even if the IP address in question is banned, so that would take care of part of the issue.
