### ISSUE TITLE
Can't list others servers

### ISSUE THREAD

**Issue by sxnmi** [drawpile/Drawpile#889]
I've been trying to host a session on multiples servers like syntheticdreams.net and Cloudywave, but even if I've added then, I can't list them. They just don't appear.
![image](https://user-images.githubusercontent.com/64449983/80439231-049c0700-88d4-11ea-8425-f1fa1aefbbf3.png)

**Comment by Wade821** [comment]
This is due to the configuration of the Drawpile server's listing server. Liz/TinCanCrab configured it so no listing is required. The List server automatically will list any session hosted on the server regardless of whether or not you use the listing option. As such, I'm going to close this issue. If you have further questions, I suggest you join the Drawpile Discord server! Invite link available on Drawpile.net in the bottom left corner. 

At best, this might be best put up as a new issue regarding how the interface lets the end user know why this is happening if the situation is known.
