### ISSUE TITLE
Locking users from hiding tagged layers

### ISSUE THREAD

**Issue by Nintennerd** [drawpile/Drawpile#894]
The idea is that Operators can choose to prevent their clients from using the show/hide function for a layer of their choice. Ie. Pick a Layer->Select the "Lock Show/Hide" tag->pick user exclusivity.

The suggestion derives from conducting battle encounters in my potential Dungeons and Dragons campaign. Right now, I can already create my own "mask" layer, to hide an image underneath it (like a map) and by erasing that mask layer bit by bit, I can create a "fog-of-war" type effect for my players. The problem with this method, however, is that my players could easily just hide the layer and take a peek of the map whenever they choose, and without my knowledge. Obviously we could go by an honour system of just avoiding that possibility, but users of Drawpile should already understand the importance of restricting non-trusted clients.  

Please no comments questioning why I would choose to host a tabletop game on Drawpile. I have my reasons. Thanks :)

**Comment by Wade821** [comment]
Well, I'm tempted to ask questions anyway! Mainly because I question the necessity of such a feature when there are existing sources outside that do this already for free and much better. 

Part of the reason for this is because adding features that aren't useable for this program's purpose as an art collaboration tool opens it to "scope creep." Scope creep basically is that the original planned purpose changes to supports a lot of things that aren't actually useful for its original intended purpose, cluttering the program's features and leading to confusion. A program that was once pretty darn good at one thing starts to become clunky feeling instead. 

In addition, if we add one thing... what other features might you think of that would prompt you to suggest features that might work better for D&D. Such as keeping said layer visible only to specific users where other users cannot see it. Where do we draw the line? I can't think of a good reason, even to include this feature as a means of censoring NSFW art, as there is already a specific auto-censor feature in Drawpile (granted it can be toggled off as well, provided parental controls don't block it). 

Personally, I'd be tempted to say that this isn't a needed thing because it's really outside of Drawpile's purpose. Don't get me wrong here though. I love and play D&D myself, though I do so on [roll20.net](https://roll20.net/). I've been thinking of how to justify this feature for a general use art drawing and animation collaboration program, but the features already exist in place are more than sufficient.

And while there is of course the importance of not trusting everyone, I think there's already enough features in place that work quite well for that purpose. This is simply very feature specific and adds clutter without being useful for everyone. 

Furthermore, I think in order for that to work, it'd require a [server protocol change](https://drawpile.net/help/compatibility/), meaning that drawpile couldn't implement this feature even if we wanted it to happen at least until Drawpile 2.2.x series, the 2.1.x series won't handle it.

**Comment by notfood** [comment]
It's a flawed idea. The user who wants to cheat would just select the layer below, copy it and paste it somewhere else and they'd get to see everything, the purpose of your idea got defeated... And we are stuck with wacky board owners forcing a mask on their canvas cutting your drawing area.

It's very niche use, you'd be the only user. It'd also conflict with some features like Solo Layer, Animations, Onion Skin... It'd be a lot of work to handle all the strange cases for something so niche that doesn't even fulfill the purpose.

My suggestion is to keep open another drawpile instance with the same canvas size, then just copy things over as they reveal. Unless it's many layers, it's not that difficult.

**Comment by Wade821** [comment]
Yes, that! Also it bears mentioning that all a user would have to do is disconnect from the session "on accident" and they'd have a perfectly usable full copy that wouldn't be bound by those rules any longer. Therefore making the option useless in its intent.

**Comment by Gabuzomeuh** [comment]
I do use Drawpile for roleplaying too but only for games with lightweight systems ; along Jami (https://jami.net) for audio/video chat, it's just perfect for illustrations during friendly party. For heavy systems, like DnD, Drawpile is not usable.
For these kind of "serious games", I recommend the use of Rolisteam (https://rolisteam.org). It's FOSS, dedicated to roleplaying and actively maintained. Imo, Roll20 is an absolute piece of .... : resources killer, proprietary and they sell users data... Awful.
That said, a better dice roller (like the one from Rolisteam) for Drawpile would be great for drawing challenges, but it's not a priority.
... Just my two cents...

**Comment by Nintennerd** [comment]
Well if I must compare the two:
Roll20 is a D&D program, with mediocre drawing and fog of war mechanics. You can only hide/show fog of war in boxes, and it tracks lines drawn as individual objects which make moving, and deleting/erasing them frustrating. Draw pile is a drawing app, with zero D&D centred features (understandably) but I can easily supplement the D&D features I lost from Roll20 by using a different app for die rolling, compendiums, and character sheets and such. 
A grid is maybe the only thing that may be tedious to replace, but I'm not here suggesting a grid feature, because that would need things like snapping, and storing image pastes as their own later, etc.
I understand the notion of rejecting an idea because someone wants the app to be something it's not, but that's not what this is. This isn't just an RPG tabletop feature. It can be used for a multitude of creative things like colouring books, connect the dots, puzzles, guessing games, blind drawing, etc. The options are up to the imagination of the user. But if all you want the app to be is exactly what the devs intended without any room for creative freedom on the users part (which could be expanded by adding features) then I don't understand the purpose of this discussion board. As a game dev myself, scope [should be] determined by the devs at the beginning of development or at design milestones. A line should already be drawn as too how far they stray from original intentions. There should be no question of where to draw it until they ultimately deem it necessary to cross it.

In terms of the flaws of this idea, well firstly, I don't know if shutting it down at first glance is not very supportive. No idea is perfect on the first inception.
If there's the issue of copying layers or "accidentally" disconnecting to avoid restrictions, that seems like something that should be fixed across the app. Why is it possible to ignore restrictions of locked layers in any capacity? That defeats the whole purpose of the locking function. My idea is to add an additional method for Operators to lock usage on their server. I don't think shutting down new ideas because the existing design is flawed is very healthy for the development of the app. If anything comes out of this discussion, it should be to fix THAT. Be it next patch or next 2.2.x series.

**Comment by Nintennerd** [comment]
Thanks, @Gabuzomeuh for the suggestion  on Rolisteam. I'll definitely take a look at it!

**Comment by notfood** [comment]
It's not about supportive or not, the idea clashes with Drawpile core which is sharing a canvas. To go out of the way to hide things from the users is very very difficult. It's not impossible, you can go through a lot of length to make sure the user can't save the canvas, can't copy underneath, can't just disconnect and get their own offline copy, can't use the recording to re-assemble the image, can't just use an older version...

The list of things to do to accomodate your idea is way too big, borders overwhelmingly big for little to no benefit. If you can code it, go for it. Drawpile is open source. I feel you will run into a lot of corner cases that defeat the idea quite easily.

**Comment by Wade821** [comment]
You have some good alternative ideas for use, but I still think it's a fairly niche use case. No idea is perfect on the first inception, that is true. But this is not a problem that is easily fixable without causing more problems.

For your idea to be truly viable, you would have to prevent saving/exporting of any kind, be able to restrict copying of layer content, warn that the window will be closed when leaving this session since there are copy protected layers, have a protocol upgrade (Drawpile 2.2.x or higher, since you would need to be actively disabling certain features in Drawpile as a result of connecting to a session). Then, to prevent users from having issues, you'd have to enable certain users to be trusted to be able to copy, save, and leave window open on disconnect. 

That's a lot of work for one person (@callaa) with already a lot of things to do on their plate, and one that I don't think necessarily needs to be "fixed" per say. 

The problem here is even though those are good ideas for alternative uses for it, as @notfood said, there's a multitude of ways to get around that issue. If we're missing anything at all here, then it will defeat the purpose of your feature request.

**Comment by Wade821** [comment]
Closing due to lack of further discussion.
