### ISSUE TITLE
Improvement: increase canvas with bigger steps

### ISSUE THREAD

**Issue by tobiasBora** [drawpile/Drawpile#901]
Hello,

First, thanks a lot for this great software. I use it to teach, and when I reach the bottom part of my board, I usually press `Ctrl-k` to increase the size of the canvas. However, the step is quite small (like `10px`?) and unfortunately when I keep the key pressed the canvas does not keep increasing, so I need to press a lot's of time `Ctrl-k` to have a new page, which is a bit long and annoying to do.

So would it be possible to create a new shortcut (why not `Ctrl-Shift-k` for example) that expands the canvas with a bigger space, like a new screen/page? Ideally it would be nice to have an option to configure more precisely the size of such operation, but it's not super important.

Also, if it's possible to fix the repetition key issue, so that I can just press once `Ctrl-k` and wait a few second to have a bigger canvas, it would be cool.

Thanks a lot for the great job!

**Comment by notfood** [comment]
Possibly related to this issue
https://github.com/drawpile/Drawpile/pull/897

**Comment by tobiasBora** [comment]
Hum, I'm not really sure. For the first problem, it's just a minor modification of the UI by adding a new shortcut, for the repetition, I'm not sure, but I guess it's linked with some "autoRepeat" configuration that needs to be slightly changed.

**Comment by callaa** [comment]
The canvas size increment is 64 pixels (the size of one tile.) I could add a configuration option for selection the step size, but I wonder if it would be better to just hard code a bigger value. 64 pixels is almost always too little anyway, so 128 or 256 pixels might be better.

**Comment by tobiasBora** [comment]
If it's too hard to add a configuration, sure we can just increase this default value.

**Comment by seitokaichou** [comment]
Normal, working key repeat would be really nice to have.

**Comment by MorrowShore** [comment]
Directionally increasing canvas size has an active keybind.
When bigger adjustments are required, you can now use the "resize canvas" option which allows for much bigger changes.

**Comment by askmeaboutlo0m** [comment]
This is sort of implemented, but in a different way: hitting one of the expand shortcuts will open the resize canvas dialog and expand the canvas in that direction. The shortcuts continue to work in this dialog and have auto-repeat, so you can hold it down to get a bigger resize, then hit enter to apply it. Or also do whatever other adjustment you want, since you got the full resize dialog there.

Doing all the expansions in one go has much better performance and opening the dialog instead of applying the resize immediately also avoids all-too-common accidental resizes.

It's available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for suggesting!
