### ISSUE TITLE
Feature request: save selection

### ISSUE THREAD

**Issue by tobiasBora** [drawpile/Drawpile#902]
Hello,

I'd love to be able to save the selection into a file (or to be able to paste the selection into a new file with the canvas following the size of the selection). For now, I need to copy the selection in drawpile with `Ctrl-Shift-C`, and then paste it in a new file in Gimp using `Ctrl-Shift-V`, and then I save from Gimp, but it would be great to be able to do that directly from drawpile.

Thanks a lot!

**Comment by Wade821** [comment]
Adding in comment I made in the Official Drawpile Discord server, for a non-Discord user. 12 Votes were made for this feature with none against it (excluding 1 vote for and against just because I used emoji to make it votable). 

> ***Suggestion by Lentejota, 04/25/2020*** (Please react with Checkmark if you like the idea, X if not, since this is not my idea and I'm not sure how many might be interested in this. I think and hope it might be pretty easy to implement given all the necessary things exist pretty much already).
> 
> **Idea:** Save only the selected area, cropping the canvas to the designated area after using selection tool.  (Edit: This tool should discard layers from the saved file which do not have any pixels active within the selected area.)
> **Reason:** Good for multi-user canvases where you just want to save your work only.
> 
> (Edit)
> **Freeform Tool:** Since this would be non square, the program would approximate a square/rectangular canvas based on the max width and max height. Anything outside of the select is treated as empty pixels.

Regarding the comment you made *"(or to be able to paste the selection into a new file with the canvas following the size of the selection)"*, I feel that isn't a viable option. It would cause problems with canvas permissions possibly for online sessions, since usually only operators can change the canvas size. 

You can always save after you disconnect from a session online, but that doesn't help of course if you're making multiple drawings and need to clear up some space.

**Comment by tobiasBora** [comment]
Thanks for your answer.

Concerning the comment to create a new file, I'm not sure to see what would be the problem if the new file is created offline. It would be equivalent to open a new blank offline document, paste, and crop the canvas.

**Comment by notfood** [comment]
Under Linux with Dolphin you can paste it on the file browser and it'll create a file.

**Comment by Wade821** [comment]
> to paste the selection into a new file with the canvas following the size of the selection)

Because any feature in Drawpile is generally usable online as well as offline. Not making it act that way would cause confusion for users, and I don't think it's generally a good idea if we start making features that work that way (unless said features require being online, like an already implemented feature for a list of users who logged into the session to ban them).

**Comment by tobiasBora** [comment]
> Under Linux with Dolphin you can paste it on the file browser and it'll create a file.

Good to know, thanks!

> Because any feature in Drawpile is generally usable online as well as offline.

Well, when you create a new file with `Ctrl-N`, the file is local, isn't it? At least I just tried and it was, and the first think it asks it the size of the canvas. So why would it be confusing to map `Ctrl-Shift-N` to the same thing as `Ctrl-N`, except that the size of the canvas is set to the size of the selection, and that the first action on that new file is a paste?

**Comment by Wade821** [comment]
> > Under Linux with Dolphin you can paste it on the file browser and it'll create a file.
> 
> Good to know, thanks!
> 
> > Because any feature in Drawpile is generally usable online as well as offline.
> 
> Well, when you create a new file with `Ctrl-N`, the file is local, isn't it? At least I just tried and it was, and the first think it asks it the size of the canvas. So why would it be confusing to map `Ctrl-Shift-N` to the same thing as `Ctrl-N`, except that the size of the canvas is set to the size of the selection, and that the first action on that new file is a paste?

It appears I misread your statement somehow and I have just been going off of my first impression, rather than re-read it. My concern, I think, was that someone might use this from another session (offline or online) to pull to a online board (in order to simplify multi layer drawings) and change the board size. But if it's restricted to a new file creation only, I guess I don't see that as an issue. Sorry, I've been staying up lately working on 3D printing stuff! :)

**Comment by tobiasBora** [comment]
Ahah no problem ;-) Good luck with your 3D printer !

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

This has been implemented and will be coming with Drawpile 2.2.
