### ISSUE TITLE
Feature request: Compile for ARM64

### ISSUE THREAD

**Issue by Charmandrigo** [drawpile/Drawpile#926]
This is a pretty optional request but would be great to see.
I have a Samsung Galaxy Book2, a windows tablet that runs on a ARM64 processor, while Windows 10 on arm can already run x86 applications and it's possible to install Drawpile that way, it would be nice to see Drawpile properly compiled for Windows ARM64 so it runs natively on this version of windows without having to emulate the intel x86 architecture

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Windows ARM64 is not supported by the infrastructure we use to build Drawpile, so there's no sensible way for us to provide it. You can compile it yourself though, it should work fine since the Android version also uses ARM64.
