### ISSUE TITLE
Drawpile crashes due to large canvas size

### ISSUE THREAD

**Issue by Sothopery** [drawpile/Drawpile#930]
I've accidentally made a new canvas that was too big and now everytime I open drawpile it will crash almost immediately.

**Comment by Wade821** [comment]
Assuming you're using windows... Find a picture on your computer, right click, open with, if you see drawpile you can select it... Otherwise choose another app. You may need to expand the list that pops up, choose another app if you don't see it. Then go to this pc, C drive, program files, drawpile. Select drawpile.exe and open. Set the canvas size to something reasonable and then exit. Try opening drawpile again. 

If you can't find it, you may need to try program files (x86) to find the Drawpile program there.

**Comment by Wade821** [comment]
Closing due to no response.
