### ISSUE TITLE
Jagged lines on Drawpile

### ISSUE THREAD

**Issue by SnifitV** [drawpile/Drawpile#932]
Recently my old tablet pen for my wacom has been died recently. So I went with my portable huion tablet that is  H420 for my main computer. Mind you I use older OS, which is windows 7 (I can't really afford a new pc atm). How would you fix the janky/jaggeted lines? after installing drivers and uninstalling nothing seems to solve the issue. let alone going into the flick menu and turning it off.

It works for Krita, it's lot smoother there then DP.

![image](https://user-images.githubusercontent.com/72063330/94517295-a615e480-01f5-11eb-8422-088d31f23184.png)
I am not sure what exactly how to fix this.

**Comment by Wade821** [comment]
Github is primarily for reporting bugs or feature requests. Issues like this don't really belong here, and as such it's best to join the official Drawpile Discord Server (Invite link on the bottom left of Drawpile.net or you can use the link here - https://discord.gg/M3yyMpC ). Mainly because you can get real time help from multiple people all using the program or one of the moderators.

As far as your issue is concerned, Drawpile actually pulls some of the tablet support features directly from Krita. If you want to continue getting help here, please answer the following:

1. Provide a Screenshot of your input dock in the lower right.
2. What version of Drawpile are you using (Help, about Drawpile)?
3. Is Windows Ink Enabled or Disabled in Drawpile (Edit, Preferences)?
4. Is Windows ink enabled in your tablet settings? In some versions, the setting is called "Support TabletPC"... as there seem to be several different versions of this software, I can't give a definitive answer on where to look.
5. Have you updated your Tablet driver? What version of the driver are you using?

**Comment by SnifitV** [comment]
I do apologize on putting it here x.x i wasn't sure where to exactly go so aa.

Anyway I tried messing around with that but doesn't seem to work.
1. ![image](https://user-images.githubusercontent.com/72063330/94522741-1d4f7680-01fe-11eb-945d-d78158cb1290.png)
2. I did have older version of DP But recently I just downloaded the newiest one. 2.1,1.7 It still has the shakey lines
3. My computer doesn't have it does have flick which is off. I have older OS system that is windows 7
4. The driver that huion uses did have tabletPC support on 
![image](https://user-images.githubusercontent.com/72063330/94523014-9058ed00-01fe-11eb-8e5e-31f245f9c222.png)
5. As for the driver I used the CD that came with the model which is H420, friend of mine gave me site to huion that had updated drives for it. tried using that but didn't seem to work.

**Comment by Wade821** [comment]
1. Ok, good.
2. Figured, but wanted to make sure you had the most up to date version.
3. Incorrect. Windows 7 was the second operating system from Microsoft to introduce Windows Ink (starting with Vista I believe). Please open Drawpile, go to edit, preferences, verify if Windows Ink is enabled or Disabled, and report back here. 
4. Good to know, just need to know what Drawpile is set to (as asked in question 3).
5. By "Didn't seem to work", what do you mean? You weren't able to install it? You updated it but the problem still exists? Please clarify.

**Comment by Wade821** [comment]
Closing due to no response.
