### ISSUE TITLE
Forcing me to log in to join a session

### ISSUE THREAD

**Issue by sleepycin** [drawpile/Drawpile#935]
![image](https://user-images.githubusercontent.com/73966690/98166805-d9a2f900-1e9c-11eb-83a3-c1089fc17ed1.png)

I have been trying to join a friend's room for the past hour and it keeps giving me this. I have entered my correct password maybe ten times, I've tried changing it twice, I've reinstalled the program twice, and I've even tried restarting my computer. I've also tried to join other servers and it's refusing to let me log in. I can't figure out how to bypass it because when I try to press okay and skip putting in my password, it gives me this message.

![image](https://user-images.githubusercontent.com/73966690/98167029-43230780-1e9d-11eb-98ba-4f04c7184ff3.png)

is there any chance I can bypass this?? I cannot get past this for some reason, even with the correct password.

**Comment by Wade821** [comment]
Github is primarily for bugs and feature requests, which is why your issue is marked this way. It's easier and faster to get support on discord. The server invite link can be found on the drawpile.net website in the lower left corner.

When you say correct password, are you referring to the session password your friend made or are you talking about the account password for the username Dean?

Because it sounds like someone registered that name. You can't use it if you didn't register it. Try using a different name and registering it on drawpile.net.
