### ISSUE TITLE
How to use the configuration file?

### ISSUE THREAD

**Issue by jioujiou2018** [drawpile/Drawpile#956]
Hi I'm trying to set up a drawpile sessions hosted by a remote server I own. I followed the insturctions and started the server successfully.  But I wanna to config it further like adding some welcome message or server title. But while following the insturctions, I have problems with it. I have no idea which catalog to create the ".ini" file and how to using it. All I know is I need to create a configuration file and making it useful somehow.  Besides "drawpile-srv  -*"command is useless while using docker. It tells me that "command not found". Maybe I just dont know how to use it correctly. I also tried create a "myconfig.cfg"in the /dpserver catalog and using"drawpile-srv -c myconfigfile.cfg". But still, "command not found".

I've read some stuff about config files & databases in the guide on the website, but I don't understand how to make use of those.

Anyone knows how to use the configuration file in this case? thanks alot.

**Comment by Wade821** [comment]
I'd help but I know nothing of Docker, as I compiled from source. And personally, I'd say you'd be better off using a database file rather than an ini file. If you join the Discord as noted below, Cody (who I believe is @CodyEakins on Github) might be able to help out more with this issue. 

_**Discord Server**_, The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed.
