### ISSUE TITLE
weird pressure bug

### ISSUE THREAD

**Issue by v35pi** [drawpile/Drawpile#958]
Hi,
I just installed Drawpile. This is what happens when I try to draw something with pressure.
As you can see, there are weird pressure "spikes" that won't let me draw. It happens with every brush.
![](https://i.imgur.com/txarX17.png)
My preferences look like this. I've tried tweaking them all but none seems to fix the issue.

![](https://i.imgur.com/NteJTr7.png)
![](https://i.imgur.com/i7eJWbz.png)

.log file looks like this:
```
[13:21:38 INFO] Drawpile started.
[13:21:38 DEBUG] (null):0 ((null)): Win8 Pointer Input disabled
[13:21:38 DEBUG] (null):0 ((null)): Enabling custom Wintab support
[13:21:39 DEBUG] (null):0 ((null)): Opened tablet context  0xa1  on window  0xa056c changed packet queue size  32 -> 128
[13:21:39 WARNING] Cannot open file 'C:/Program Files/Drawpile/theme:list-remove.svg', because: The system cannot find the file specified.
[13:21:39 WARNING] Cannot open file 'C:/Program Files/Drawpile/theme:list-remove.svg', because: The system cannot find the file specified.
[13:21:40 DEBUG] (null):0 ((null)): qtDesktopRect = QRect(0,0 1366x768)
[13:21:40 DEBUG] (null):0 ((null)): wintabDesktopRect = QRect(0,0 1366x768)
[13:21:40 DEBUG] (null):0 ((null)): DVC_NAME = "Tablet, Port:HID, Dim:10000x6000  Model:160"

```
I also want to point out that when using CLIP STUDIO PAINT I don't usually get this bugs, unless I use a specific brush with high stabilization (aka "smoothing" here). Although it is very uncommon in CSP, I think it may be correlated to smoothing just because of this.

My tablet is an UGEE M708.

Thank you beforehand!

**Comment by Wade821** [comment]
Well your smoothing setting is completely off as dragged to the far left on your input tab. Try moving that over to the right. 

Also, if you go to help, about Drawpile, what version are you using? 

For faster help, join the Drawpile Discord (invite link https://discord.gg/M3yyMpC). Github is intended primarily for bug reporting, feature requests, etc... not so much for support issues. I wouldn't call this a bug because we haven't had this issue for a while, which is part of why I'd like to know what version you're using. :)

**Comment by v35pi** [comment]
Hi Wade!

I've tried doing that too (moving the smoothing all the way to the right) but it still doesn't work. I'm using version 2.1.17.

Sorry about writing here, I didn't know there was a discord server. I'm surprised that I'm the only one who has this issue.

Thanks for the response :-)

**Comment by Wade821** [comment]
Well, it's been a *long* time as I said. I know there was some issues previously that was affecting everyone at one point so it seemed, but that was several versions ago with an update to the Windows Ink API. And I was suggesting discord because it was real time help rather than possibly a few days. 

Anyway, few questions for you (assuming you have Windows 10, if you don't, the steps will be different):


Do you have multiple monitors or just one?


I doubt this is your particular problem given your screen resolution in the log, but it doesn't hurt to try. If you right click the desktop and go to "Display settings", is the "Change the size of text, apps, and other items" set to anything other than 100%? If so, try setting it to 100% and then restart your computer before attempting to use Drawpile. Some people have reported weird pen pressure problems that were resolved by adjusting this setting. 


In your tablet settings, do you have Windows ink enabled? It's called "Supports Digital Ink" in your tablet configuration software. 
![image](https://user-images.githubusercontent.com/18544575/109431001-62502280-79c1-11eb-9bfd-0a55cfd1315c.png)
https://f.ptcdn.info/084/040/000/o2i4jbdipWaA2Ie3ONC-o.png (image source)

If so, Windows Ink *must* be enabled in Drawpile. Software settings for the tablet must match program settings for Drawpile. After you make the change, exit and reload Drawpile.


Have you tried redownloading and reinstalling Drawpile? It might be worth doing also, given the log. Maybe your download was slightly corrupted...
