### ISSUE TITLE
Text box often loses focus when typing keys bound to commands and tools

### ISSUE THREAD

**Issue by leopardheart982** [drawpile/Drawpile#962]
If there's a key bound to some action, such as the number keys, it will sometimes perform that action instead of typing in the Annotation box, even if you have your textbox highlighted and have a cursor in the Annotation box. This also happens when trying to type a number into the text size box.

**Comment by MorrowShore** [comment]
Confirmed to be still present. Typing in annotation box is interrupted when putting in numbers.

**Comment by askmeaboutlo0m** [comment]
Finally managed to reproduce this so I could fix it. The problem was caused by the "press and hold" detection that's supposed to let you hold down a tool shortcut and then spring back when you release it. Except it didn't reset itself properly if you released the key quickly, meaning it would interpret the first letter you typed as you releasing a long-held key press and switching tools because of it.

The fix is available in the continuous release: <https://github.com/drawpile/Drawpile/releases/tag/continuous>

Thanks for reporting it!
