### ISSUE TITLE
Wrong ethernet device is selected in my network setup

### ISSUE THREAD

**Issue by jochen-giese** [drawpile/Drawpile#965]
It seems that, if multiple local network interfaces are available, no possibility to choose between them exists in the menu for hosting a session or in the settings. In my network a wrong interface will be selected (10.X.Y.Z instead of 192.168.A.B).

**Comment by Wade821** [comment]
Can you provide more information? Like what your operating system is and why you'd have multiple active network connections that would require being able to choose one specifically, as there may be a built in solution in the operating system. Is one of them a VPN and one is a local ethernet/wireless?

**Comment by jochen-giese** [comment]
I'm using Linux (opensuse). In my private and my professional notebook configuration, I'm using multiple networks. E.g. once is for VPN, ones for an virtual laboratory network, once a second private network for separated devices and/or the company network. Most of them work on IP addresses like 10.x.y.z and 192.168.x.y. Meanly I understood that drawpile pick the lowest address of private networks (10.... and 192....). I looking for a selector or a setting to set the IP or select the listen devices, or the setting, that the host is listen on all devices.

**Comment by Wade821** [comment]
Fair enough. Then yeah, I'd see where that'd be an issue. Was just trying to see if there was something that could be done if I knew more about your configuration and needs. It may be a bit before such a feature is implemented. Thanks for the additional details.

**Comment by callaa** [comment]
I just noticed this one as well. Fortunately, it's only a cosmetic problem, Drawpile still listens on all interfaces, it just needs to pick one address to show in the status bar. Since it's not possible to automatically choose the right IP to show in every situation, I suppose adding some option to select it manually would be best solution. (Maybe with some logic to prefer the manually selected subnet in the future to improve the chances of it guessing right?)

**Comment by MorrowShore** [comment]
Stale, doesn't cause an issue.
